Further gitstatus cleanup/fixes
jarun/nnn pull request #1046
Opened 2021-06-02 20:35 UTC by luukvbaal

Pending review of @crides (check https://github.com/luukvbaal/nnn/commit/aca2ad3c56ca9a39a7fe3008b382b2566d6f9536 for the actual diff).

2021-06-02 20:42 UTC, KlzXS commented on patches/gitstatus/mainline.diff
> -# Authors: @crides, Luuk van Baal
I think you mistakenly removed this.

2021-06-02 21:14 UTC, KlzXS requested changes
See comments. The memory leak needs to be fixed.

Sorry for mistakenly posting this on your fork, I forgot where I was. It did seem odd to me that it didn't offer me to start a review.

2021-06-02 21:14 UTC, KlzXS commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
Do we really need a ternary operator as a condition for an if?
Also what is the point in using `starts_with()` for a dir and `xstrcmp()` for a file? Can these not be merged into a single string comparison?

Red alert! We are leaking memory. `abspath()` allocates a string and returns that pointer! It's not an in-place operation.

2021-06-02 21:42 UTC, luukvbaal commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
> Do we really need a ternary operator as a condition for an if?

Need no, thought it was better than duplicating the if statement/assignment.

> Also what is the point in using `starts_with()` for a dir and `xstrcmp()` for a file? Can these not be merged into a single string comparison?

I've tried to but couldn't get the right behavior. Debugging the git status entries has proven difficult to me.

2021-06-02 21:49 UTC, KlzXS commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
Well I don't have anything smart to say about the ternary operator. Let's see if I'll have more luck with merging the two cases.

The call to `abspath()` needs to be saved in a new `char*`, maybe make one for the other argument so that the whole if can fit on a single line at least.

2021-06-02 21:56 UTC, crides commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
> Also what is the point in using starts_with() for a dir and xstrcmp() for a file? Can these not be merged into a single string comparison?

If it's a file, then either one of its parent directory is ignored, so it's ignored too; or its status is directly reported. 

If it's a directory, then (same applies) either one of its parent directory is ignored, so it's ignored too; or its status is directly reported; or, if its descendants has non default status, then those need to be squashed. 

These are needed as the `git_status_list_new()` call basically returns what `git status --short` shows.

2021-06-02 22:03 UTC, luukvbaal commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
Yeah, trying one more time. Thinking we should also use the preexisting `is_prefix()` instead of `starts_with()`.

2021-06-02 22:05 UTC, jarun commented
@KlzXS please squash and merge when done.

2021-06-02 22:05 UTC, KlzXS commented
Will do,

2021-06-02 22:21 UTC, luukvbaal commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
This seems to work as expected.
```
		if (git_statuses.len) {
			uint merged_status = 0;
			char *dentpath = abspath(dentp->name, path);

			for (size_t i = 0; i < git_statuses.len; i ++) {
				if (dentp->flags & DIR_OR_LINK_TO_DIR) {
					size_t dentlen = xstrlen(dentpath);

					if ((dentlen <= xstrlen(git_statuses.statuses[i].path)) && is_prefix(git_statuses.statuses[i].path, dentpath, dentlen))
						merged_status |= git_statuses.statuses[i].status;
				} else if (!xstrcmp(git_statuses.statuses[i].path, dentpath)) {
						merged_status |= git_statuses.statuses[i].status;
				}
			}

			dentp->status_indexed = git_get_indexed_status(merged_status);
			dentp->status_staged = git_get_staged_status(merged_status);
			free(dentpath);
		}
```

2021-06-02 22:26 UTC, crides commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
Oh I didn't know that function is there. 

Still, I don't think that resolves the bug, as it still doesn't compare path-wise. I _think_ we need to check 1) if `prefix` is a prefix of `path`, and 2) if the character right after the prefix is `'/'` or 0 (so that the 2 are the same). I'll try that when I get home, or you can try it now

2021-06-02 22:28 UTC, luukvbaal commented on patches/gitstatus/mainline.diff
> ++						: !xstrcmp(git_statuses.statuses[i].path, abspath(dentp->name, path)))
What bug are we talking about now? I don't see the `dir/nnn.1` vs `dir/nnn` false positive with the latest commit.

2021-06-02 22:50 UTC, luukvbaal commented
I think we are good, seeing the same output as `exa --git` now. Can be merged as far as I'm concerned after you have done a final review @KlzXS.

2021-06-02 22:57 UTC, KlzXS commented
I'll test it myself a bit and look through the code one more time tomorrow. After that I'll merge.
@crides do you have anything to add?

2021-06-02 23:25 UTC, crides commented
No I don't think

2021-06-03 09:01 UTC, merged

2021-06-03 09:03 UTC, KlzXS commented
Everything seems fine. Merged.

2021-06-03 09:30 UTC, KlzXS commented
@luukvbaal the compatibility patch :facepalm: ...
Do you think we can make a script to automate generating mainline and compatibility patches together? Otherwise I see us regularly forgetting to generate them. Especially if we get a lot of conflicting patches.

2021-06-03 10:08 UTC, luukvbaal commented
Not sure what would be best but something to automate it would be good yeah.

2021-06-03 10:16 UTC, KlzXS commented
Better yet, let's nip the problem in the bud. Let's ditch these hardcoded numbers relating to line width and use something better. That way we can avoid making a bunch of compatibility patches each time a new patch adds something else to print. With just one more it would grow to 4, one more after that and we have 11.

2021-06-03 10:24 UTC, luukvbaal commented
Yeah if you have something in mind that will work, be my guest.

Alternatively we could auto-generate the diffs from the Github .diff [url](https://github.com/luukvbaal/nnn/commit/f8c98ecb07867a3df2ebbc759b68a1166ca5473c.diff). That would require maintaining the fork branches, either on the main repo or on the patch author's forks.

Not sure what we would present on the repo in that case, perhaps move the patches page to the wiki.

2021-06-03 10:29 UTC, KlzXS commented
> Yeah if you have something in mind that will work, be my guest.

I'm looking at `adjust_cols()` right now and this magical `n -= 32`. Where does this number even come from? But if each patch updated it to it needs along with all other numbers which are related to it (like the 36 just above, it must be related) it would work, right?

> Alternatively we could auto-generate the diffs from the Github .diff url. That would require maintaining the fork branches, either on the main repo or on the patch author's forks.

That seems like a lot of work. At some point you might even need a patch1-patch2-patch3-patch4.diff and then you can say goodbye to readability in the Makefile.

2021-06-03 10:38 UTC, luukvbaal commented
Yeah `adjust_cols()` always needs to be updated for patches adjusting the detail columns. The `n -= 32` comes from time + size + perms + spacing columns. Indeed the comment is out dated. 

> it would work, right?

Not quite sure what you have in mind.

> That seems like a lot of work. At some point you might even need a patch1-patch2-patch3-patch4.diff and then you can say goodbye to readability in the Makefile.

Could relegate the patching to a shell script that is passed the make options which `curl`s the diff urls and applies the patches. But if you have something better in mind be my guest.

2021-06-03 10:45 UTC, KlzXS commented
I'll think about it. Update gitstatus compatibility for now since you know how to do that.

2021-06-03 10:46 UTC, luukvbaal commented
It doesn't require an update currently I think?