Add force-tty capability to spawn and set pagers to it
jarun/nnn pull request #1070
Opened 2021-06-12 15:50 UTC by annagrram

Addresses issue #1064

2021-06-12 16:01 UTC, kevinsjoberg commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
Could we use `freopen` here?

2021-06-12 16:05 UTC, annagrram commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
We could, but I wanted to keep it in the same "API set" as the already written code in this function.

2021-06-12 16:11 UTC, kevinsjoberg commented on src/nnn.c
> +			/* If stdout has been redirecet to a non-tty, force output to tty */
Minor typo here. `redirecet` should be `redirected`.

2021-06-12 16:12 UTC, annagrram commented on src/nnn.c
> +			/* If stdout has been redirecet to a non-tty, force output to tty */
Thanks :)

2021-06-12 16:21 UTC, kevinsjoberg commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
Perhaps unnecessary here, but we could use `ctermid()` to avoid hard coding `/dev/tty`.

2021-06-12 16:25 UTC, annagrram commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
Changed.
I'm not that strong in my POSIX functions :)

2021-06-12 16:26 UTC, kevinsjoberg commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
No worries, thanks a lot! 👍

2021-06-12 16:27 UTC, kevinsjoberg approved these changes
LGTM. Thank you for this. 🎉

2021-06-12 16:27 UTC, annagrram commented on src/nnn.c
> +				int fd = open("/dev/tty", O_WRONLY, 0200);
My pleasure

2021-06-12 17:10 UTC, jarun commented
@annagrram CI fails. Please check.

2021-06-12 17:11 UTC, luukvbaal commented
CI fails due to https://github.com/jarun/nnn/commit/69926a8eff971655112d950150802f92f8f4423c @jarun

2021-06-12 17:11 UTC, annagrram commented
> @annagrram CI fails. Please check.

@jarun, not because of this PR. Check your last couple of commits

2021-06-12 17:16 UTC, jarun commented
Got it! Resolved the issue now.

2021-06-12 17:24 UTC, jarun requested changes

2021-06-12 17:24 UTC, jarun commented on src/nnn.c
> +static int spawn(char *file, char *arg1, char *arg2, char *arg3, uint16_t flag);
Please use `ushort_t` instead of `uint16_t`.

Both `uint16_t` and `uint32_t` are [optional](https://en.cppreference.com/w/cpp/types/integer).

2021-06-12 17:26 UTC, jarun commented on src/nnn.c
> +		} else if (flag & F_FORCE_TTY) {
Hmm... I reduce lines, you keep adding.

Just kidding! This is fine!

2021-06-12 17:32 UTC, merged

2021-06-12 17:33 UTC, jarun commented
Thank you so much! :+1:

2021-06-12 17:49 UTC, craigbarnes commented on src/nnn.c
> +static int spawn(char *file, char *arg1, char *arg2, char *arg3, uint16_t flag);
FWIW, `uint16_t` is a required type on POSIX systems:

> The following types are required:
>
> int8_t
> int16_t
> int32_t
> uint8_t
> uint16_t
> uint32_t

-- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdint.h.html

2021-06-12 19:03 UTC, jarun commented on src/nnn.c
> +static int spawn(char *file, char *arg1, char *arg2, char *arg3, uint16_t flag);
Thanks for the reference! I think we can reduce a few typedefs now. ;)

2021-06-13 06:28 UTC, jarun commented on src/nnn.c
> +static int spawn(char *file, char *arg1, char *arg2, char *arg3, uint16_t flag);
And thanks to out patch framework. Making changes all around the code is not so simple anymore.
I'm leaving these as they are.