File-explorer functionality
jarun/nnn pull request #1073
Opened 2021-06-15 05:22 UTC by mizlan

Adds flag `-F` that prevents nnn from exiting on selection. This uses the path given to `-p` and will append to the output on each selection.

I'm not exactly aware of what `seltofile` does but it was getting in the way so I commented it out. I am not that great at C so please point out if I'm doing anything incorrectly here.

2021-06-15 05:26 UTC, mizlan commented
To try this yourself, if desired, run `nnn -F -p ~/testfile` and in another terminal window run `tail -F ~/testfile`.

2021-06-15 09:50 UTC, jarun commented
Ci fails. Please check.

@luukvbaal can you please help with the testing?

2021-06-15 16:28 UTC, mizlan commented on src/nnn.c
> +			if (!g_state.explorer && ((fd == -1) || (seltofile(fd, NULL) != (size_t)(selbufpos))))
Is it okay to not run this line?

2021-06-15 17:56 UTC, jarun commented on src/nnn.c
> +			if (!g_state.explorer && ((fd == -1) || (seltofile(fd, NULL) != (size_t)(selbufpos))))
Can you please explain what was the problem with this and what you are trying to achieve?

2021-06-15 18:20 UTC, jarun requested changes

2021-06-15 18:20 UTC, jarun commented on src/nnn.c
> +	FILE *fp = fopen(selpath, "a");
if you see the latest code, I have removed every instance of `FILE *`. Please rebase and extend writesel() to take one more bool param and append instead of overwrite if it's true.

2021-06-15 18:20 UTC, jarun commented on src/nnn.c
> +				if (g_state.explorer) {
Why is the explorer mode below picker mode? Do they have anything in common? If yes, case 'F' in line 7858 should also set picker mode.

2021-06-15 18:20 UTC, jarun commented on src/nnn.c
> +					// add a newline to the file to make it easier to parse `tail -F`
Please explain your design. What are you trying to achieve?

2021-06-15 18:20 UTC, jarun commented on src/nnn.c
> +					// is this necessary?
Not needed.

2021-06-15 18:20 UTC, jarun commented on src/nnn.c
> +					// add a newline to the file to make it easier to parse `tail -F`
So you are writing one file at a time to selection file newline separated.
When you read the selection file at the other end, how do you know which position you read last? Because user can keep pressing <kbd>Enter</kbd> on files one after another.

Why not read the FIFO like the previewer instead? We can have a different fifo for the same.

2021-06-15 19:24 UTC, mizlan commented on src/nnn.c
> +					// add a newline to the file to make it easier to parse `tail -F`
> When you read the selection file at the other end, how do you know which position you read last? Because user can keep pressing Enter on files one after another.

Using `tail -F` and a callback on stdout.

> Why not read the FIFO like the previewer instead? We can have a different fifo for the same.

Ah, I was approaching this from the wrong direction. I think this will significantly simplify it. And I think we can use the same fifo right? Just attaching a different listener.

2021-06-15 19:26 UTC, mizlan commented on src/nnn.c
> +				if (g_state.explorer) {
I think I can remove it now. I was originally repurposing the picker file as a file to append filepaths to, but I'm going to switch to using NNN_FIFO.

2021-06-15 19:32 UTC, jarun commented on src/nnn.c
> +				if (g_state.explorer) {
Re-using `NNN_FIFO` may be an issue as it sends out the file path on hover. You only need it when user presses Enter/^M on the file.

BTW, please rebase your code.

2021-06-15 19:34 UTC, mizlan commented on src/nnn.c
> +				if (g_state.explorer) {
I have rebased. I may open a new PR as I'm going to scratch most of the changes I've made here. Are you okay with that?

2021-06-15 19:52 UTC, mizlan commented on src/nnn.c
> +				if (g_state.explorer) {
Could you refactor the code to make it easier to work with multiple fifos? For example having `notify_fifo` take a file descriptor as an argument, or I'm not too sure what's the best way to do it.

2021-06-15 20:02 UTC, mizlan commented on src/nnn.c
> +	FILE *fp = fopen(selpath, "a");
Do I need to do this now that I plan on using a FIFO?

2021-06-15 21:04 UTC, jarun commented on src/nnn.c
> +	FILE *fp = fopen(selpath, "a");
No. See `notify_fifo()`.

2021-06-15 21:09 UTC, jarun commented on src/nnn.c
> +				if (g_state.explorer) {
Just add a `bool` to `notify_fifo()` and follow the current code.

2021-06-15 21:11 UTC, jarun commented on src/nnn.c
> +				if (g_state.explorer) {
Yes, please close the current PR.

2021-06-15 23:11 UTC, closed without merging

2021-06-16 07:35 UTC, luukvbaal commented
Sorry for the late response. 

This is supposed to provide a persistent picker mode mainly for `nnn.vim` right?
I agree that a separate FIFO makes sense.

2021-06-16 08:07 UTC, jarun commented
That's correct! @mizlan will be raising a new review with FIFO based implementation.