Refactor fifo code and add explorer
jarun/nnn pull request #1075
Opened 2021-06-16 17:10 UTC by mizlan

Work in progress, but let me know if anything doesn't look right.

2021-06-16 17:31 UTC, luukvbaal commented
Passing `<hover/,explorer>_<fifo,path>` directly to `notify_fifo()` instead of a boolean makes more sense I think. Unless more changes in `notify_fifo()` are required for either case.

Also is `picker` instead of `explorer` not a more appropriate name? You're making a persistent picker mode right, I would consider `nnn` in and of itself a file "explorer"  already.

2021-06-16 18:00 UTC, mizlan commented
> Passing `<hover,explorer>_<fifo,path>` directly to `notify_fifo()` instead of a boolean

I like this better. @jarun What do you think?

> Also is picker instead of explorer not a more appropriate name?

Good point. Although, picker already has a meaning within the source code but this is not really related to the picker implementation-wise.

2021-06-16 18:18 UTC, luukvbaal commented
> I like this better. @jarun What do you think?

`notify_fifo(bool force, const int fifofd, const char *fifopath)` is what I meant. 
If the function stays exactly the same except for those two arguments I would say it makes more sense to pass those arguments rather than passing an arbitrary boolean that determines those arguments inside the function no, even if only two different cases exist. Whatever works though I guess.


> Good point. Although, picker already has a meaning within the source code but this is not really related to the picker implementation-wise.

Yeah I would name it `prstpicker` or something for persistent picker(`prstssn` is used for persistent session) because I thought that's what you were implementing, if not never mind.

2021-06-16 18:19 UTC, mizlan commented
The concept of persistence is different in the case of persistent session though (persisting across different instances of nnn) while here it is just "not closing." I am sort of against the idea.

2021-06-16 18:26 UTC, luukvbaal commented
The same terminology to describe the issue was used here https://github.com/mcchrish/nnn.vim/issues/61#issuecomment-633784351.
I think its an apt description, you would be using the `nnn` picker mode persistently right:yum:?
I don't mind though, its just a name after all...

2021-06-16 18:28 UTC, mizlan commented
Alright, I'll consider it :)

I am running into an issue, however. This code currently works when the FIFO passed to `-F` is created ahead of time. However, it doesn't create the FIFO, even adding this:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 3e874926..a5f4533e 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -8095,6 +8095,15 @@ int main(int argc, char *argv[])
 
 		sigaction(SIGPIPE, &(struct sigaction){.sa_handler = SIG_IGN}, NULL);
 	}
+
+	if (g_state.explorer && explorer_fifopath) {
+		if (mkfifo(explorer_fifopath, 0600) != 0 && !(errno == EEXIST && access(explorer_fifopath, W_OK) == 0)) {
+			xerror();
+			return EXIT_FAILURE;
+		}
+
+		sigaction(SIGPIPE, &(struct sigaction){.sa_handler = SIG_IGN}, NULL);
+	}
 #endif
 
 #ifdef LINUX_INOTIFY
```

Is there anything I should do other than adding that?

2021-06-16 19:20 UTC, luukvbaal commented
Going by your current PR, I think your `explorer_fifopath()` will be `NULL` because `realpath()` returns NULL for non-existing files.
Not sure if we have a way to dereference file paths passed as an argument, can't look into it right now.

2021-06-16 20:07 UTC, mizlan commented
@luukvbaal How about this? Here I assume that the path passed to `-F` is valid (no call to `realpath`)

2021-06-16 20:10 UTC, mizlan commented
Hmm, should I make this a patch instead of putting these changes in master?

2021-06-16 23:01 UTC, luukvbaal commented
> @luukvbaal How about this? Here I assume that the path passed to `-F` is valid (no call to `realpath`)

Yeah I think requiring an absolute path by the caller (e.g. `nnn.vim` or other scripts) for `-F` is fine.

> Hmm, should I make this a patch instead of putting these changes in master?

I think this is a welcome addition to master given how it was requested a few times in `nnn.vim. Don't know how @jarun feels about it.

2021-06-16 23:31 UTC, luukvbaal commented on src/nnn.c
>  #endif
Don't forget
```suggestion
            if (g_state.explorer)
	        unlink(explorer_fifopath);
 #endif
```

2021-06-16 23:45 UTC, luukvbaal commented
Sorry, used spaces instead of tabs for that suggestion(idk how to insert tabs in this markdown window).
Please fix. Also off to bed now, gn.

2021-06-16 23:46 UTC, mizlan commented on src/nnn.c
>  #endif
Thanks! I don't know how I missed this bit. I'm going to unresolve this because formatting and also, shouldn't this also be inside the ifndef NOFIFO part as well?

2021-06-17 17:44 UTC, mizlan commented
Should I change all occurrences of "explorer" to "filetree" or "prstpicker" instead? Not sure what the right terminology here is.

2021-06-17 18:01 UTC, jarun commented
Can you please share an image how it looks like?

2021-06-17 18:02 UTC, mizlan commented
Of nnn.vim or nnn? Do you want a side-by-side of the FIFO output and nnn?

2021-06-17 18:03 UTC, jarun commented
When you use it as an explorer... I think that would be nnn.vim.

2021-06-17 18:04 UTC, mizlan commented
Sorry, I'm not done with that yet.

2021-06-17 18:05 UTC, jarun commented
Okk. Why are you using the term _tree_?

2021-06-17 18:08 UTC, mizlan commented
I'm not sure to be honest. Emacs has a thing called treemacs, which is probably what made me think of "tree," but the naming is up to you. @luukvbaal said "explorer" doesn't really make sense because nnn is an explorer in itself.

2021-06-17 18:09 UTC, jarun commented
We don't have a tree view. I would say _prstpicker_ is the right term.

2021-06-17 18:11 UTC, jarun commented
On second thoughts, it's ok to have explorer. Stay with it. Easy to refer to and understand.

2021-06-17 18:28 UTC, jarun requested changes

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +static int hover_fifofd = -1;
Shorten these with comments: `hfifofd` and `efifofd`.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +static char *hover_fifopath;
Shorten with comments - `hfifopath`, `efifopath`.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +static void notify_fifo(bool force, bool is_explorer); /* explorer has a separate fifo */
Just `explorer`. Drop the `is_`.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +	char **fifopath_ptr = is_explorer ? &explorer_fifopath : &hover_fifopath;
Use `ppath` and `pfd`.
We know we are dealing with fifos here.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +	char **fifopath_ptr = is_explorer ? &explorer_fifopath : &hover_fifopath;
Oh, why do we even need pointers here? fifofd and fifopath are both globals.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +		case 'F':
Use `-X` (capital) for `explorer` mode. We will document what we call `explorer mode`.

2021-06-17 18:28 UTC, jarun commented on src/nnn.c
> +	if (g_state.explorer && explorer_fifopath) {
Why do we need to check `explorer_fifopath`. The new option requires a value which comes through `optarg`.

2021-06-17 18:31 UTC, mizlan commented on src/nnn.c
> +	char **fifopath_ptr = is_explorer ? &explorer_fifopath : &hover_fifopath;
Yeah, I was a little bit confused at this part. I reassign the value of the path under some circumstances, so wouldn't it be necessary to use a pointer to update it?

2021-06-17 18:32 UTC, mizlan commented on src/nnn.c
> +	if (g_state.explorer && explorer_fifopath) {
Will fix

2021-06-17 18:35 UTC, jarun commented on src/nnn.c
> +static void notify_fifo(bool force, bool is_explorer); /* explorer has a separate fifo */
Also drop the comment.

2021-06-17 18:41 UTC, jarun commented on src/nnn.c
> +	char **fifopath_ptr = is_explorer ? &explorer_fifopath : &hover_fifopath;
OK, I see why. You will need pointers. But keep those short as I mentioned.

2021-06-17 23:00 UTC, luukvbaal commented
We need a man page entry as well.

2021-06-17 23:36 UTC, jarun commented
Yes, we are good to go! Please add `-X` to man page.

2021-06-17 23:44 UTC, mizlan commented
Do I need to add a section on explorer mode or is the mention of the flag enough?

2021-06-17 23:51 UTC, jarun commented
Mention of the flag is enough. :+1: Thank you!

2021-06-17 23:51 UTC, merged

2021-07-08 13:00 UTC, toddyamakawa commented
It looks like this patch adds an "explorer fifo"? What is the difference between an explorer FIFO and a hover FIFO?

2021-07-08 14:54 UTC, mizlan commented
When nnn is embedded inside another text editor, the explore FIFO allows nnn to act as a project drawer, where selecting files opens them up in the editor, by having the editor listen to the explorer FIFO. Think of it as the picker mode, but persistent.

2021-07-09 03:08 UTC, toddyamakawa commented
Thanks for the explanation.
How do you send files to the explorer FIFO?
Will this allow you to send a path from the text editor to change nnn's directory?

2021-07-09 17:21 UTC, mizlan commented
1. Check the source code for `notify_fifo()`.
2. No, since the communication is one way. Also that functionality seems
outside the scope of explorer mode.

On Thu, Jul 8, 2021 at 8:08 PM Todd Yamakawa ***@***.***>
wrote:

> Thanks for the explanation.
> How do you send files to the explorer FIFO?
> Will this allow you to send a path from the text editor to change nnn's
> directory?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jarun/nnn/pull/1075#issuecomment-876879082>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKSBU2J6SSAS3GX3ON2PEHLTWZR3ZANCNFSM46Z4CXHA>
> .
>