Imgview open hovered image
jarun/nnn pull request #1084
Opened 2021-06-27 23:42 UTC by luukvbaal

Should fix #1083

2021-06-28 02:17 UTC, tonijarjour commented on plugins/imgview
> +        view_files sxiv "$target" >/dev/null 2>&1 &
Please add the -a flags so sxiv plays gifs automatically

2021-06-28 02:21 UTC, tonijarjour commented
nvm its all good

2021-06-28 18:31 UTC, jarun requested changes

2021-06-28 18:31 UTC, jarun commented on plugins/imgview
>      make_thumbs 0
If I understand the logic correctly, do we really need to create a directory and show the image even when only a file is passed? I would like avoid that on e.g. read-only storage. In general, we should not issue writes if not absolutely necessary.

2021-06-28 20:16 UTC, tonijarjour commented on plugins/imgview
>      make_thumbs 0
For what its worth, if you could make this only happen if a video was passed, and if ffmpegthumbnailer is actually installed. It would make the program a lot faster.

2021-06-28 22:08 UTC, luukvbaal commented on plugins/imgview
>      make_thumbs 0
My reasoning was that there is no reason the behavior should be any different when a file or a directory is hovered after merging the thumbnail plugin.

When only a file is passed we still want to be able to view other images (or thumbnails) in the same directory (i.e. by pressing <kbd>n</kbd> in `sxiv`), thus thumbnails for media files in the directory are created in this case as well.

I do agree that it should continue gracefully for read only memory, would that be fine or do you still want it out altogether?

2021-06-28 22:22 UTC, luukvbaal commented on plugins/imgview
>      make_thumbs 0
Whether a video is passed or not is not sufficient to decide not to run `make_thumbs` with the current logic. We are creating thumbnails for all audio/video files in the same directory as the passed argument.

We are also using `ffmpeg` to generated audio thumbnails. I doubt much people would have  a system without `ffmpeg` so running `make_thumbs` when either `ffmpeg` or `ffmpegthumbnailer` is installed would likely result in it always being ran.

Is the slowdown really that noticeable? All thats being run is `file`.
You can also just comment it out if you don't need media thumbnails.

2021-06-28 22:47 UTC, tonijarjour commented on plugins/imgview
>      make_thumbs 0
The slowdown is noticeable but its not a big deal. Im working with over 300 files.
Since as you said only `file` is being run, there's nothing to do there. But in the case of sxiv, you passed `0` to `make_thumbs`, which means you aren't making audio thumbails (from what I understand from the code). In that case you can check if `ffmpegthumbnailer` is installed and if not, skip the iterator all together.

2021-06-28 22:59 UTC, luukvbaal commented on plugins/imgview
>      make_thumbs 0
You are correct, added the `ffmpegthumbnailer` check for `sxiv` case.
The reason for passing `0/1` to `make_thumbs` btw is that `sxiv` creates audio thumbnails by itself, but not video, whereas `ucollage` creates video thumbnails, but not audio🤣

2021-06-29 03:50 UTC, jarun commented on plugins/imgview
>      make_thumbs 0
Yes, we should detect read-only and work accordingly. Maybe try /tmp as fallback else jist show the image.

2021-06-29 15:02 UTC, jarun commented on plugins/imgview
>      make_thumbs 0
Please ping once this is done and we can have this in.

2021-06-30 09:43 UTC, luukvbaal reviewed
Reuse `NNN_PREVIEWDIR` from `preview-tui` to store the thumbnails instead of (trying to) create a `.nthumbs` in working directory.

2021-06-30 09:43 UTC, luukvbaal commented on plugins/imgview
> -nthumb_cleanup() {
Get rid of cleanup function since we are in `$TMDIR` or `$XDG_CACHE_HOME`

2021-06-30 09:43 UTC, luukvbaal commented on plugins/imgview
> +NNN_PREVIEWDIR="${NNN_PREVIEWDIR:-$TMPDIR/nnn/previews}"
Reuse `preview-tui` variable for preview directory

2021-06-30 09:43 UTC, luukvbaal commented on plugins/imgview
> +        if [ ! -f "$NNN_PREVIEWDIR$PWD/$file.jpg" ]; then
Don't regenerate previews

2021-06-30 09:43 UTC, luukvbaal commented on plugins/imgview
> +    for file in "$NNN_PREVIEWDIR$PWD"/*; do
Delete files not present in source directory from preview directory

2021-06-30 14:21 UTC, jarun commented
@tonijarjour can you please test and confirm the changes?

2021-06-30 17:09 UTC, tonijarjour commented
@jarun Tested with [this](https://github.com/jarun/nnn/blob/5e3c90751c6ff1e9c4395c8fe2b8250395ceacd4/plugins/imgview). Using imgview on a directory fails. Works correctly on a file.

2021-06-30 20:45 UTC, luukvbaal commented
> @jarun Tested with [this](https://github.com/jarun/nnn/blob/5e3c90751c6ff1e9c4395c8fe2b8250395ceacd4/plugins/imgview). Using imgview on a directory fails. Works correctly on a file.

Could you elaborate? Seems to work fine on my end.

2021-06-30 21:15 UTC, tonijarjour commented
The problem is that when `type ffmpegthumbnailer >/dev/null 2>&1 && make_thumbs 0` fails, the `previews` folder made by `make_thumbs` never comes into existence. So `find` in `listimages` fails as well and garbage gets passed to `sxiv`.

Thats about it.

2021-06-30 21:40 UTC, luukvbaal commented
Right, thanks.

2021-06-30 23:13 UTC, tonijarjour commented
Alright tested with and without ffmpegthumbnailer. Everything works perfectly and it is much faster now. :+1:

2021-06-30 23:17 UTC, luukvbaal commented
Yeah should be good now sorry.

2021-06-30 23:18 UTC, tonijarjour commented
Wait there is a problem. `mkdir` fails with a permission denied error. (trying to make `/nnn`)

2021-06-30 23:24 UTC, luukvbaal commented
Yeah `TMPDIR` variable was missing, try now.

2021-06-30 23:27 UTC, tonijarjour commented
It isn't generating thumbnails with `ffmpegthumbnailer`

2021-07-01 00:00 UTC, tonijarjour commented
`video/*) [ "$1" -ne 1 ] && ffmpegthumbnailer -i "$file" -o "$NNN_PREVIEWDIR$dir/$file.jpg" 2> /dev/null ;;`
to
`video/*) [ "$1" -ne 1 ] && ffmpegthumbnailer -i "$file" -o "$NNN_PREVIEWDIR$file.jpg" 2> /dev/null ;;`

2021-07-01 00:28 UTC, luukvbaal commented
Thanks for testing!
I think it's good now.

2021-07-01 09:06 UTC, merged

2021-07-01 09:06 UTC, jarun commented
Thank you!