MacOSX legacy
jarun/nnn pull request #1138
Opened 2021-08-21 20:35 UTC by elder-n00b

Hopefully it's now OK.

- Makefile now checks that `sw_vers` is present, also does version check a little better and uses (hopefully) better variable names.
- Added files are out of the way, in `misc/macosx-legacy`.

I thought I could run the CI workflow before PR but I haven't found how, even enabling workflows for the fork -- crossing fingers...

2021-08-21 21:26 UTC, jarun commented
@luukvbaal @KlzXS doesn't this belong to the patch framework? I don't want to add new files under `misc` for macOS.

2021-08-21 21:30 UTC, elder-n00b commented
I had the doubt too when I noticed the new patches framework, but the description didn't rhyme.
Also, it seems to me there's no way to patch the makefile from there -- I could be wrong.

2021-08-21 21:42 UTC, jarun commented
> Also, it seems to me there's no way to patch the makefile from there -- I could be wrong.

You should be able to patch any file in the repo. Would wait for others to help you out.

2021-08-21 21:43 UTC, luukvbaal commented
The current patch framework indeed does not allow patching the Makefile since we are applying the patches from inside the Makefile itself. At least the Makefile change will have to be merged.

The new files and `nnn.c` change could be adopted into a patch if you prefer although it doesn't really fit our current patch description.

2021-08-21 21:45 UTC, luukvbaal commented
In principle you can patch the Makefile but with the current framework that would just apply and revert the diff without affecting the already running ` make` process.

2021-08-21 21:47 UTC, jarun commented
@elder-n00b I think @luukvbaal intends to convey that this is related to OS support. I agree.

In that case I think we are good to go.

2021-08-21 21:58 UTC, jarun requested changes

2021-08-21 21:58 UTC, jarun commented on misc/macosx-legacy/mach_gettime.c
> +    if( clk_id == TIMER_ABSTIME) {
space after `if`

2021-08-21 21:58 UTC, jarun commented on misc/macosx-legacy/mach_gettime.c
> +    kern_return_t retval = KERN_SUCCESS;
We use tabs.

2021-08-21 21:58 UTC, jarun commented on misc/macosx-legacy/mach_gettime.c
> +    else { // other clk_ids are mapped to the coresponding mach clock_service
} else {

2021-08-21 21:58 UTC, jarun commented on misc/macosx-legacy/mach_gettime.c
> +int clock_gettime(clockid_t clk_id, struct timespec *tp)
static int

2021-08-21 21:58 UTC, jarun commented on Makefile
> +MACOSX_VERSION := $(strip $(shell command -v sw_vers >/dev/null && [ "`sw_vers -productName`" = "Mac OS X" ] && sw_vers -productVersion))
Please add a comment above to clarify what we are doing here.

2021-08-21 22:00 UTC, luukvbaal commented
> @elder-n00b I think @luukvbaal intends to convey that this is related to OS support. I agree.

No I was just conveying that IF we want to support legacy MacOS with this PR, the change to the Makefile is required in `master` due the the limitation of the patch framework.

I see no problem in placing this in `misc` but I was just saying that alternatively the required changes (outside of the Makefile change) could be placed in a patch if you really wanted.

2021-08-21 22:05 UTC, elder-n00b commented
Going to apply requested changes and commit.
Re patch, I guess it could also be done as a patch that interested users would apply manually before make.
Let me know.

2021-08-21 22:09 UTC, luukvbaal commented
That could work as well accompanied with a note on the Wiki/patches Readme yeah. Whatever @jarun prefers.

2021-08-21 22:34 UTC, elder-n00b commented on misc/macosx-legacy/mach_gettime.c
> +int clock_gettime(clockid_t clk_id, struct timespec *tp)
I get compile error with `static int` in `mach_gettime.c`.
```
misc/macosx-legacy/mach_gettime.c:11:12: error: static declaration of 'clock_gettime' follows non-static declaration
```
It becomes warnings if I also declare it `static int` in `mach_gettime.h`.
```
misc/macosx-legacy/mach_gettime.c:11:12: warning: unused function 'clock_gettime' [-Wunused-function]
In file included from src/nnn.c:112:
src/../misc/macosx-legacy/mach_gettime.h:24:12: warning: function 'clock_gettime' has internal linkage but is not defined [-Wundefined-internal]
```
```
static int clock_gettime(clockid_t clk_id, struct timespec *tp);
           ^
src/nnn.c:5701:2: note: used here
        clock_gettime(CLOCK_REALTIME, &ts1); /* Use CLOCK_MONOTONIC on FreeBSD */
        ^
```
One of those c subtleties I never really understood... I would have though that meant "return a static int" but apparently static applies to the function, not the return value. 
I read that "static means that the function can be called only in the .c file where it is defined" but I don't really know. 

Should I drop the static?

2021-08-21 22:53 UTC, elder-n00b commented
The patch would be simply `git diff origin/master > macosx-legacy.patch`, is that correct?

2021-08-21 22:53 UTC, jarun commented on misc/macosx-legacy/mach_gettime.c
> +int clock_gettime(clockid_t clk_id, struct timespec *tp)
Yes, please drop it then.

2021-08-21 22:54 UTC, jarun commented
No the misc thing is fine. It's a legacy OS support.

2021-08-22 01:09 UTC, 0xACE commented on misc/macosx-legacy/mach_gettime.h
> +
![cap](https://user-images.githubusercontent.com/1482942/130338616-45feec2c-244c-4755-bc44-d93564a481df.png)
It's probably not important in our limited usecase but incase someone else picks it up...

2021-08-22 01:39 UTC, elder-n00b commented on misc/macosx-legacy/mach_gettime.h
> +
Ops. Done. I'll be back ~6hrs.
Note: ideally I would have applied the fixup commits to the initial branch from v4.2 not HEAD but I'm not very git savvy and I wasn't sure not to wreck something with the open PR... happy swapping and squashing. Apologies. Or I'll do it tomorrow morning if it's a safe operation.

2021-08-22 06:39 UTC, merged

2021-08-22 06:39 UTC, jarun commented
Thank you!