[draft] signal CWD change to terminal via OSC-7
jarun/nnn pull request #1148
Opened 2021-08-29 16:40 UTC by dnkl

The path still needs to be URL encoded, but this shows the gist of it. Tested in foot only so far. Will hopefully be able to try a few more tomorrow.

Closes #1147

2021-08-29 16:48 UTC, jarun requested changes

2021-08-29 16:48 UTC, jarun commented on src/nnn.c
> +	/* Signal CWD change to terminal */
I think we should add it under the check in line 6510 below. 

Then users can enable it using option `-x`. The code is compiled by default.

Program options: https://github.com/jarun/nnn/wiki/Usage#program-options

The reason we did this is there were some cases where purist users complained about stray prints (like for xterm title print).

2021-08-29 17:38 UTC, dnkl commented on src/nnn.c
> +	/* Signal CWD change to terminal */
That's perfect! Fixed, thanks!

2021-08-29 17:44 UTC, jarun requested changes

2021-08-29 17:44 UTC, jarun commented on src/nnn.c
> +		gethostname(hostname, sizeof(hostname));
You can use `newpath` (which works like a scratchbuffer in each iteration) here to avoid additional memory usage for hostname. It's `PATH_MAX` long.

2021-08-29 19:41 UTC, jarun commented on src/nnn.c
> +		gethostname(hostname, sizeof(hostname));
I think there was a oversight on my part. Given the hostname doesn't change often (an it's non-fatal) if it does, we should have allocated the memory and set it only once in browse and then printed it here.

2021-08-30 02:01 UTC, jarun commented on src/nnn.c
> +		gethostname(hostname, sizeof(hostname));
Once you complete the tests, please update. I'll make the change to use a single call instead of each time. Thanks!

2021-08-30 14:21 UTC, merged

2021-08-30 14:45 UTC, jarun commented
Please confirm commit 0556ac14ecd6ae028dafe9645ac3bcefa8c0faf4 works fine in your tests.

2021-08-30 15:49 UTC, dnkl commented
That commit works fine in both foot, and in gnome-terminal.

Technically, the path needs to be URL encoded. In reality, not doing will work in probably 99% of all cases. I tested switching to a directory named `åöä&>`, and it worked in gnome-terminal as well as in foot.

I also tested a directory that included a literal `ESC`, and that did **not** work. That's expected, since an ESC will typically reset the VT state machine.

It would be fairly simple to implement a URL encoder that allows plain ASCII but `%NN` encodes all other characters. Such an encoder would be overly eager, compared to what's actually necessary, but would produce "safe" output.

On the other hand, if we want to keep things simple, then let's skip URL encoding. The worst thing that happens is the new terminal doesn't spawn in the correct directory.

2021-08-30 16:02 UTC, jarun commented
> I tested switching to a directory named åöä&>, and it worked in gnome-terminal as well as in foot.

That's because by default `nnn` is linked to ncursesw (with wide char support) so wide chars workas they should under the hood. Wide chars should work as expected.

2021-08-30 16:06 UTC, jarun commented
BTW, given the restrictions in `nnn`, no one would agree to have an encoder for a single-line printf. Practically speaking, there's no ROI.

2021-08-30 16:26 UTC, dnkl commented
Then it's all good from my side.

2021-08-30 16:34 UTC, jarun commented
:+1: