Resolve symlinks one level for .nmv when in list mode
jarun/nnn pull request #1218
Opened 2021-11-02 22:20 UTC by KlzXS

`NNN_LIST` is set automatically if we are in list mode and we are in the tmp directory.

Resolving is done using `readlink(1)`. This utility reads out what the symlink points to (the thing `ls -l` would display). We always use absolute paths so that's fine. The resolving is done while reading in the input, this way most of the script can stay untouched.

2021-11-02 22:38 UTC, jarun requested changes

2021-11-02 22:38 UTC, jarun commented on src/nnn.c
> +					setenv("NNN_LIST", "1", 1);
Do we need to clear `NNN_LIST` after the operation? What happens if the same operation is run once again?

2021-11-02 22:42 UTC, jarun commented on src/nnn.c
> +					setenv("NNN_LIST", "1", 1);
I mean multiple rename from a regular directory? As `NNN_LIST` remains set, the plugin will treat it as a case of listing.

2021-11-02 22:47 UTC, KlzXS commented on src/nnn.c
> +					setenv("NNN_LIST", "1", 1);
We do.

2021-11-02 22:49 UTC, KlzXS commented
CI fails on `browse()` complexity. Can't we do something to silence that for good? This is like the 10th time I've seen this that I can remember.

2021-11-02 22:58 UTC, KlzXS commented on src/nnn.c
> +					setenv("NNN_LIST", "1", 1);
I used the return value of `is_prefix()` for the value in the latest commit. Please check the indentation, I'm not on my usual system. That's why all the commits are unverified.

2021-11-03 02:51 UTC, merged

2021-11-03 02:51 UTC, jarun commented
Thank you!

> CI fails on browse() complexity.

I don't want the function to cross 900 lines. I will reduce somewhere.