[WIP] make the manpage more clear
jarun/nnn pull request #1270
Opened 2021-12-23 22:58 UTC by N-R-K

some of the terms used in the manpage aren't exactly obvious, especially
to a new user. this is an attempt at making the manual more clear and
remove any potential confusion.

here's a couple issues i've noticed where users were confused due to non
clear manpage description:

https://github.com/jarun/nnn/issues/1268
https://github.com/jarun/nnn/issues/1269
https://github.com/jarun/nnn/issues/1209

2021-12-23 23:13 UTC, N-R-K commented
I'm not entirely sure what `+` is supposed to do. It doesn't seem to do anything for me.

2021-12-24 05:41 UTC, PatrickF1 commented
> I'm not entirely sure what + is supposed to do. It doesn't seem to do anything for me.

😂 I just spent another 30 minutes experimenting and still couldn't figure out what it does. I'm tempted to learn C just to find out what it does.

2021-12-24 05:41 UTC, PatrickF1 commented on nnn.1
> +        show notis on selection cp, mv, rm completion (requires \fI.cbcp\fR plugin)
Notis = notification right? Why not just type out the whole thing?

2021-12-24 06:00 UTC, N-R-K commented
It's used here

https://github.com/jarun/nnn/blob/bd6e7e81479823fdf28cdc507027982011039c9f/src/nnn.c#L7036-L7038

Which suggests it's about advancing the cursor after opening something, but it doesn't seem to do anything for me.

2021-12-25 01:54 UTC, jarun requested changes

2021-12-25 01:54 UTC, jarun commented on nnn.1
> +        copy path to system clipboard on select (requires \fI.cbcp\fR plugin)
... to system clipboard on selection

2021-12-25 02:00 UTC, N-R-K commented on nnn.1
> +        copy path to system clipboard on select (requires \fI.cbcp\fR plugin)
How about
> copy all selection path to system clipboard

2021-12-25 02:03 UTC, jarun commented on nnn.1
> +        copy path to system clipboard on select (requires \fI.cbcp\fR plugin)
No it does each time when you select a single file also.

2021-12-25 02:12 UTC, jarun commented
Toggle auto-advance -> please make this Toggle auto-proceed on file open

2021-12-25 02:14 UTC, jarun requested changes

2021-12-25 02:14 UTC, jarun commented on nnn.1
>          disable auto-proceed on select
disable auto-proceed on select

> disable auto-proceed on selection

2021-12-25 02:17 UTC, jarun commented
`-A` documentation: please change auto-select to auto-enter

2021-12-25 02:18 UTC, jarun commented
Please ensure the word `advance` is gone from the manpage.

2021-12-25 02:36 UTC, jarun requested changes

2021-12-25 02:36 UTC, jarun commented on nnn.1
> +mode with auto enter, disk usage analyzer mode, bookmarks,
dir auto-enter


Use the hyphen

2021-12-25 02:36 UTC, jarun commented on nnn.1
> +        (eg. making a selection will no longer move cursor to the next entry)
(eg. making a selection

>

(e.g. selecting an entry...

2021-12-25 02:41 UTC, jarun commented
I think we are good. Please enable the merge option.

2021-12-25 02:47 UTC, N-R-K commented
Looks like we got conflict. I'll rebase on top of master.

2021-12-25 02:47 UTC, merged

2021-12-25 02:47 UTC, jarun commented
Thank you!

2021-12-25 03:46 UTC, PatrickF1 commented
Thank you @N-R-K! I appreciate you hoping on this so quickly after I opened up my issues in confusion. 
I still have some ideas. Is the ToDo issue a good place to discuss?

2021-12-25 03:52 UTC, N-R-K commented
> I still have some ideas. Is the ToDo issue a good place to discuss?

@PatrickF1 Yes, the ToDo issue is a good place for small discussions.