introduce new plugin for jumping git root
jarun/nnn pull request #1272
Opened 2021-12-24 01:45 UTC by PatrickF1

introduce new plugin for jumping to the root of current git repo
tested locally

2021-12-24 01:48 UTC, PatrickF1 commented on plugins/README.md
> +| [gpge](gpge) | Encrypt/decrypt files using GPG [✓] | sh | gpg |
this is a typo fix; if you click it currently on master it 404s

2021-12-24 02:22 UTC, N-R-K requested changes

2021-12-24 02:22 UTC, N-R-K commented on plugins/gitroot
> +# Shell: bash
What's the reason for requiring `Bash` ? I'm not seeing any bashism in here.

2021-12-24 02:24 UTC, PatrickF1 commented
Sure I will change it to sh honestly didn’t really know if there were any
bashisms

On Thu, Dec 23, 2021 at 6:22 PM N-R-K ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In plugins/gitroot
> <https://github.com/jarun/nnn/pull/1272#discussion_r774842459>:
>
> > @@ -0,0 +1,14 @@
> +#!/usr/bin/env bash
> +
> +# Description: cd to the top level of the current git repository in the current context
> +# Shell: bash
>
> What's the reason for requiring Bash ? I'm not seeing any bashism in here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jarun/nnn/pull/1272#pullrequestreview-839700614>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPAJEB22XWX7TY7VHYHVNDUSPKQFANCNFSM5KVZ4S5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-24 03:43 UTC, PatrickF1 commented
Done! Any other feedback?

2021-12-25 00:32 UTC, PatrickF1 commented
@N-R-K could I get a re-review please?

2021-12-25 01:03 UTC, N-R-K commented on plugins/gitroot
> +    printf "%s" "0c$root" > "$NNN_PIPE"
Could probably avoid calling `git` twice.

```suggestion
root="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -n "$root" ]; then
    printf "%s" "0c$root" > "$NNN_PIPE"
```

Untested, but I think it should work.

2021-12-25 01:03 UTC, N-R-K commented
> @N-R-K could I get a re-review please?

Looks fine to me. Wait for @jarun to take a look, he's usually responsible for merging things.

2021-12-25 01:15 UTC, PatrickF1 commented on plugins/gitroot
> +    printf "%s" "0c$root" > "$NNN_PIPE"
Great idea! Let's make it even faster. Let me test it out right now. And thanks for the review :)

2021-12-25 01:18 UTC, PatrickF1 commented on plugins/gitroot
> +    printf "%s" "0c$root" > "$NNN_PIPE"
tested and it works!

2021-12-25 02:40 UTC, jarun commented
Ultra cool! ;)
Thank you for your contribution!

2021-12-25 02:42 UTC, merged

2021-12-25 02:42 UTC, jarun commented
Thank you!

2021-12-25 03:47 UTC, PatrickF1 commented
Thank you for merging my changes @jarun ! And thank you so much for making this awesome tool with a well-thought-out plugin system. I commend your brilliance 💯