Emoji
jarun/nnn pull request #1356
Opened 2022-05-05 20:22 UTC by dkabus

I have implemented icons using emoji such that it works in my version of the suckless terminal st. This addresses the feature request #1346.

2022-05-05 20:32 UTC, N-R-K submitted a review, later dismissed
Glancing over the patch, here's a couple issues that stands out.

2022-05-05 20:32 UTC, N-R-K commented on Makefile
> +O_EMOJI := 1  # support emoji
Should probably be 0 by default.

2022-05-05 20:32 UTC, N-R-K commented on Makefile
> +	mv $(BIN) $(BIN)-icons-static
```suggestion
	mv $(BIN) $(BIN)-emoji-static
```

2022-05-05 20:32 UTC, N-R-K commented on src/icons.h
> +#endif
Why the conditional? Both branches seem to be doing the same thing.

2022-05-05 20:54 UTC, dkabus commented on src/icons.h
> +#endif
I am padding the emoji with two spaces vs one. This is kind of the ugly part of my implementation. Honestly, I do not understand how emoji are rendered well enough to know why this works, but it does.

2022-05-05 21:02 UTC, dkabus commented on Makefile
> +O_EMOJI := 1  # support emoji
I need to set O_EMOJI to 1 for it to properly compile. If I do it via `make O_EMOJI=1 clean all`, the emoji are not properly displayed.

2022-05-05 21:06 UTC, N-R-K commented on src/icons.h
> +#endif
Oh, my bad. I didn't notice that the emoji branch had different amount of spaces. But in that case the `*_LEN` should've been adjusted accordingly as well.

2022-05-05 21:10 UTC, N-R-K commented on Makefile
> +O_EMOJI := 1  # support emoji
That's weird, I don't see anything obvious to why that might be happening. Could you double check?

2022-05-05 21:16 UTC, dkabus commented on Makefile
> +O_EMOJI := 1  # support emoji
Nevermind. It does in fact compile properly that way 🤦

2022-05-05 21:25 UTC, dkabus commented on src/icons.h
> +#endif
Well its complicated. I think it works like this: Some of the glyphs are two characters wide, others are just one character. I made sure to add spaces where nessessary such that the strings stored in the compiler variables `EMOJI_*` all contain two characters. In the drawing process, to all of them one additional space is appended, namely `ICON_PADDING_RIGHT`. In total we now have three characters (`[emoji][maybe emoji][space]`). With the other icon sets, the icons are represented by only one character each (`[icon][space][space]`). So, this is why `ICON_PADDING_RIGHT` and `ICON_PADDING_RIGHT_LEN` do not match up here. This can probably done in a more elegant way, but this should probably be done by someone more familiar with the source code.

2022-05-06 08:15 UTC, N-R-K commented on src/icons.h
> +#endif
The following seems to be working fine for me.

```diff
diff --git a/src/icons.h b/src/icons.h
index 7bfa7c8..4f3f243 100644
--- a/src/icons.h
+++ b/src/icons.h
@@ -26,11 +26,12 @@ struct icon_pair {
 
 #define ICON_PADDING_LEFT  ""
 #define ICON_PADDING_LEFT_LEN  (0)
-#define ICON_PADDING_RIGHT_LEN (2)
 #if defined(EMOJI)
 #define ICON_PADDING_RIGHT " "
+#define ICON_PADDING_RIGHT_LEN (1)
 #else
 #define ICON_PADDING_RIGHT "  "
+#define ICON_PADDING_RIGHT_LEN (2)
 #endif
 
 #define COLOR_VIDEO        93  /* Purple */
```

This is in XTerm

![image](https://user-images.githubusercontent.com/79544946/167093807-a803f50c-e005-49aa-9577-657b30c37347.png)

Not sure if it's a good idea to mix different width emojies though.

2022-05-06 14:58 UTC, dkabus commented on src/icons.h
> +#endif
This (at least for me) does not work with long filenames that have to be truncated.

On the left: your proposed patch, on the right, my proposal:
![screenshot_20220506_165626](https://user-images.githubusercontent.com/11159390/167158910-c468bfe2-0bd9-4b7a-a1a7-3789b4387606.png)

2022-05-06 15:23 UTC, N-R-K commented on src/icons.h
> +#endif
Aright, I've digged into this a bit. The patch I sent earlier is correct, the `LEN` should indeed be 1.

The problem is elsewhere, I think it's because `nnn` expects all the icons to be one cell wide.

I think the nerd icons also suffers similar problem, which is why we rejected any double cell wide icons : https://github.com/jarun/nnn/pull/1135#issuecomment-901298575

2022-05-07 12:00 UTC, N-R-K commented on src/icons.h
> +#endif
https://github.com/jarun/nnn/pull/1356/commits/936d6fb0a825a0d05a9b096c8b9f3951a92b4174 Should fix the issue.

2022-05-07 12:05 UTC, N-R-K commented
The cell width issue should be fixed by https://github.com/jarun/nnn/pull/1356/commits/936d6fb0a825a0d05a9b096c8b9f3951a92b4174, but still not entirely sure if mixing single and double width emojies are a good idea or not.

Looks ugly IMO.

![image](https://user-images.githubusercontent.com/79544946/167253547-9e120f94-fab2-46ae-bb87-8a6224fb59c8.png)

2022-05-07 12:28 UTC, N-R-K requested changes

2022-05-07 12:28 UTC, N-R-K commented on src/icons.h
> +static const struct icon_pair exec_icon = {"", EMOJI_EXE,    0};
Let's respect the existing naming convention, so `EMOJI_FOLDER` -> `EMOJI_DIRECTORY` and `EMOJI_EXE` -> `EMOJI_EXEC`.

2022-05-07 12:28 UTC, N-R-K commented on src/icons.h
> +	{"Notes",        EMOJI_NOTES,      0},
The existing icons don't have these rules and some of these ("Uni", "Nextcloud" etc) seems better suited toward a personal build.

2022-05-07 12:28 UTC, N-R-K commented on src/icons-emoji.h
> +
Add a comment explaining that double width emojies need to be manually right padded with space.

2022-05-07 12:47 UTC, dkabus commented on src/icons.h
> +static const struct icon_pair exec_icon = {"", EMOJI_EXE,    0};
Sure, I've changed `EXE` -> `EXEC`. Nerd uses "directory" and icons uses "folder". I will just leave it.

2022-05-07 12:48 UTC, dkabus commented on src/icons.h
> +	{"Notes",        EMOJI_NOTES,      0},
Yes, indeed. I will keep "Games", "Cloud", "Literature", "Code", and "Notes" though, as these seem reasonably general.

2022-05-07 14:03 UTC, N-R-K approved these changes
Other than the mixing of single and double width emojies, looks good.

2022-05-10 14:43 UTC, merged

2022-05-10 14:44 UTC, jarun commented
Thank you so much!
Personally I like it very much.

2022-05-10 19:12 UTC, jarun commented
The game and code emoji are not showing correctly on xubuntu 22.04, xfce4-terminal. Can you please have a look?

![](https://imgur.com/fP2UwSr.png)

2022-05-10 19:30 UTC, jarun commented
@dkabus At commit af94c7704fcb3c9549fec2397b79c1c799346f51 I removed all the additional emojis you added. I think I made it very clear in the defect that I wanted something minimal, not with additional bells and whistles. This is a public project, we do not want non-standard stuff. If you need those for your custom distro, please patch downstream.

2022-07-26 15:15 UTC, N-R-K commented on Makefile
> +	tar -zcf $(BIN)-emoji-static-$(VERSION).x86_64.tar.gz $(BIN)-icons-static
@jarun Just noticed this while trying to test the released emoji static binary. It `tar`-ed the icons-in-terminal binary instead of the emoji binary.