Enter type-to-nav for plugin dir
jarun/nnn pull request #1374
Opened 2022-05-29 22:47 UTC by luukvbaal

RE https://github.com/jarun/nnn/pull/1373#issuecomment-1140461536: I think this covers everything, without too many extra checks. Please check if you agree :)

Also enables auto-enter for `g_state.selbm` and `g_state.runplugin`.

2022-05-29 23:38 UTC, N-R-K commented
Without looking at the code, I'm wondering what usecase does this serve? Having ttn mode on in bookmarks dir allows for quickly navigating the bookmarks. I haven't seen anyone ask for ttn mode on plugins dir.

2022-05-29 23:47 UTC, luukvbaal commented
It only enters ttn in plugin selection mode(i.e. pressing <kbd>;Enter</kbd>, not when navigating there menually).

I think it is a fair assumption to make that the user would like to easily filter/select the plugins and ttn provides a native way to do so.

Basically it is a builtin alternative to `fzplug` like I said. Do you think it is undesired behavior?

2022-05-29 23:57 UTC, N-R-K commented
> It only enters ttn in plugin selection mode(i.e. pressing ;Enter, not when navigating there menually).
> 
> I think it is a fair assumption to make that the user would like to easily filter/select the plugins and ttn provides a native way to do so.
> 
> Basically it is a builtin alternative to `fzplug` like I said. Do you think it is undesired behavior?

Ah, I misunderstood what this was doing then. And no, I think this is a fair improvement and makes sense.

2022-05-30 00:59 UTC, jarun requested changes

2022-05-30 00:59 UTC, jarun commented on src/nnn.c
> +	if (g_state.filtermode) {
A new check every time we jump to begin. This is what I was talking about. I have to think about it.

2022-05-30 00:59 UTC, jarun commented
This adds open condition checks in flows. That's what I was indicating. I'll think about it.

2022-05-30 01:11 UTC, luukvbaal commented on src/nnn.c
> +	if (g_state.filtermode) {
Sure, I understand why you would be apprehensive of adding a check there. I just hoped the convenience factor would outweigh the performance consideration :)

Let me know and I'll raise the PR for the `restorepreview` patch conflict(dependent on this PR) and patch conflict resolve instructions later.

2022-05-30 01:21 UTC, luukvbaal commented on src/nnn.c
> +	if (g_state.filtermode) {
Keep in mind that this block will almost never execute, the first check will only evaluate to true when the user presses <kbd>b/;Enter</kbd>.

2022-05-30 08:41 UTC, jarun commented on src/nnn.c
> +	if (g_state.filtermode) {
It's just a matter of pressing /.

2022-05-30 16:47 UTC, jarun commented
Guys I have decided not to go with this. I will also revert the bm hack. Can't litter the code with roundabout checks to save on a single keypress (`/`).

2022-05-30 16:47 UTC, closed without merging