make it easy to check for failing patches locally
jarun/nnn pull request #1413
Opened 2022-06-29 20:21 UTC by N-R-K

adds a script `check-patches.sh` to check for patch failures and also
adds a make target `checkpatches` which will invoke the check-patches
script.

2022-06-29 20:55 UTC, luukvbaal commented
LGTM. BTW it would look like this embedded in the Makefile:
```Make
SHELL := /bin/bash
checkpatches:
	export PATCH_OPTS="--merge"; \
	patches=("O_GITSTATUS" "O_NAMEFIRST" "O_RESTOREPREVIEW"); \
	z=$$(( 1 << $${#patches[@]} )); \
	pid=$$; \
	ret=0; \
	trap 'ret=1' SIGUSR1; \
	for ((n=1; n < z; ++n)); do \
	    for ((i=0; i < $${#patches[@]}; ++i)); do \
	        printf "%s=%d " "$${patches[$$i]}" "$$(( (n & (1 << i)) != 0 ))"; \
	    done | tee "/dev/stderr" | ( \
	        make clean -s; \
	        xargs make 2>&1; \
	        if [ "$$?" -ne 0 ]; then \
	            echo "[FAILED]" >&2; \
	            kill -SIGUSR1 "$$pid"; \
	        else \
	            echo "[SUCCESS]" >&2; \
	        fi; \
	        git restore src; \
	    ) >/dev/null; \
	done; \
	exit "$$ret" \
```

Involves a lot of escaping, idk if it's worth it. Up to jarun.

2022-06-30 16:16 UTC, jarun requested changes

2022-06-30 16:16 UTC, jarun commented on Makefile
> +	./misc/test/check-patches.sh
Why not add this under the `patches` directory?

2022-07-01 02:15 UTC, merged

2022-07-01 02:15 UTC, jarun commented
Thank you!