Add saucenao plugin
jarun/nnn pull request #1418
Opened 2022-07-03 20:26 UTC by GospodinHoroshiy

New plugin for searching hovered images with saucenao
Tested locally

2022-07-04 15:13 UTC, jarun requested changes

2022-07-04 15:13 UTC, jarun commented on plugins/README.md
> +| [saucenao](saucenao) | Upload file to saucenao and scrap links | sh | curl |
Can you mention that it is a reverse image search engine?

2022-07-04 15:28 UTC, jarun commented
Can you explain the benefit of this plugin for regular users?
Why should one use this plugin instead of opening the reverse image search engine in a web browser where she can visually see the images?

2022-07-04 17:00 UTC, jarun commented
Closing this as I am not seeing any real use case for regular users.
Also, the script is to scrape the results which is unrelated to day-to-day file management.

2022-07-04 17:00 UTC, closed without merging

2022-07-05 16:55 UTC, N-R-K commented
A more useful version might have been to download all the images to some `/tmp/` folder and take the user there on a new context. Then they can use `nnn` to delete the entries they don't like and move/copy the ones they do.

2022-07-06 01:22 UTC, jarun commented
@N-R-K we are not aware of the terms of usage and the copyrights of the images.