Escape call to `nnn` so `nnn` can be used as an alias to `n`
jarun/nnn pull request #1426
Opened 2022-07-17 00:33 UTC by Anomalocaridid

Currently, if you use quitcd and set `nnn` to be an alias of `n` in bash or zsh, you will get the following error if you try to run nnn: `maximum nested function level reached; increase FUNCNEST?`. Escaping the call to `nnn` in quitcd lets you use `nnn` as an alias to `n` without raising this error.

2022-07-17 03:43 UTC, jarun commented
For completeness, can you please check if that's achievable for the other shells with `quitcd` script as well?

2022-07-17 03:43 UTC, jarun requested changes

2022-07-17 03:43 UTC, jarun commented on misc/quitcd/quitcd.bash_zsh
> +    \nnn "$@"
Please add a comment on why this is done.

2022-07-18 00:54 UTC, Anomalocaridid commented
How's this? Also, as far as I was able to figure out, quitcd.elv already has the Elvish equivalent of this implemented, so I just put a comment in it.

2022-07-18 00:54 UTC, N-R-K commented on misc/quitcd/quitcd.bash_zsh
> +    # The backslash allows one to alias nnn to n if desired without making an
You can already alias `nnn` to `n`, think this should've been the other way around (?)

2022-07-18 01:07 UTC, Anomalocaridid commented
Sorry about that. Looks like I failed to notice a typo I made. How's this?

2022-07-18 03:06 UTC, N-R-K commented on misc/quitcd/quitcd.fish
> +    # The command function allowa one to alias n to nnn if desired without
```suggestion
    # The command function allows one to alias this function to `nnn` if desired without
```

2022-07-18 12:55 UTC, jarun commented on misc/quitcd/quitcd.fish
> +    # The command function allowa one to alias n to nnn if desired without
I'll take care of this. Merging.

2022-07-18 12:55 UTC, merged

2022-07-18 12:55 UTC, jarun commented
Thank you!