Erlang and Elixir icons with colors
jarun/nnn pull request #1437
Opened 2022-07-25 11:37 UTC by tlarevo

Hi, I added Erlang and Elixir icons with colors for different related file extensions. Let me know if I have done anything wrong or unacceptable.

2022-07-25 12:22 UTC, jarun commented
Please refer to PR #1419.

@N-R-K @luukvbaal please take a call.

2022-07-25 12:43 UTC, N-R-K requested changes

2022-07-25 12:43 UTC, N-R-K commented on src/icons.h
> +#define ICON_ERLANG        ICON_STR("", "\ue7b1", "📞")
Why is the ERLANG emoji-icon a phone ?

2022-07-25 12:43 UTC, N-R-K commented on src/icons.h
> +	{"lock",       ICON_LOCKFILE,       0},
What's the "lock" extension used for and how common is it? Quick internet search seems to suggest it's something related to minecraft?

2022-07-25 13:02 UTC, N-R-K requested changes
Elixir seems to be somewhat popular. Think we can take that.

I'm fine skipping Erlang and "lock".

2022-07-25 13:02 UTC, N-R-K commented on src/icons.h
> +#define ICON_ELIXIR        ICON_STR("", "\ue62d", "💧")
```suggestion
#define ICON_ELIXIR        ICON_STR(MFIZZ_ELIXIR, "\ue62d", "💧")
```

2022-07-25 13:02 UTC, N-R-K commented on src/icons.h
> +	COLOR_X(COLOR_ELIXIR_PHX,   104)  /* MediumPurple */ \
Please stick to a single color.

2022-07-25 14:08 UTC, N-R-K commented
@jarun Pushed the changes. Should be good to merge. (Probably should "squash-merge" it though).

2022-07-25 14:10 UTC, merged

2022-07-25 14:10 UTC, jarun commented
Thank you!

2022-07-25 17:17 UTC, tlarevo commented on src/icons.h
> +#define ICON_ERLANG        ICON_STR("", "\ue7b1", "📞")
Sorry about the late reply, Erlang is named after a Danish mathematician [Agner Erlang](https://en.wikipedia.org/wiki/Agner_Krarup_Erlang) and he created the field of [telephone networks](https://en.wikipedia.org/wiki/PSTN) analysis. Also Erlang(O.T.P - Open Telecom Platform) was initially designed for developing telecommunication related software. Hence, I thought of suggesting that icon. But if it causes ambiguity or confusion, I'm fine with dropping the emoji.

2022-07-25 17:25 UTC, tlarevo commented on src/icons.h
> +	{"lock",       ICON_LOCKFILE,       0},
No some package managers/build systems maintain a 'lock' file to freeze the dependencies to specific version so that when the app is built builder knows exact versions to pick. Elixir's `mix` is one such tool. In `elixir`, `mix.exs` stores the dependencies and `mix.lock` has exact versions and other details.

<img width="136" alt="Screenshot 2022-07-25 at 22 52 46" src="https://user-images.githubusercontent.com/3371313/180837867-ec583c60-f134-48f2-a299-1bd0537052bf.png">

2022-07-25 17:34 UTC, tlarevo commented on src/icons.h
> +#define ICON_ERLANG        ICON_STR("", "\ue7b1", "📞")
May I send a new PR for Erlang icons?

2022-07-26 04:16 UTC, tlarevo commented on src/icons.h
> +#define ICON_ERLANG        ICON_STR("", "\ue7b1", "📞")
Understood, however, Elixir runs on Erlang VM/OTP. Therefore, I hope you would consider adding Erlang as well. Cheers 🍺