Improved chunk allocation logic
jarun/nnn pull request #1451
Opened 2022-08-02 19:35 UTC by KlzXS

I'm much more satisfied with this check. No useless calculations. Also I saw that there was a way to `free(paths)` before we even allocated it so I patched that. Also it seems we were reading one chunk too few, not that anyone would notice without digging in too deep.

There is also the modified check for exhausting the input @N-R-K wanted to see.

2022-08-02 19:44 UTC, N-R-K commented on src/nnn.c
> +		free(paths);
`free(3)` is defined to be a no-op on NULL arg. So checks like these don't really have any effect.

2022-08-02 19:47 UTC, KlzXS commented on src/nnn.c
> +		free(paths);
Huh. I must have forgotten that. It's been a while since I've worked with dynamic allocation in C.

2022-08-02 19:47 UTC, N-R-K requested changes

2022-08-02 19:47 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
Would prefer using `sizeof` instead of hard coding.

```suggestion
		while (read(fd, buf, sizeof buf) != 0);
```

There's a lot of other places in our code that uses hard-coded sizes where sizeof would've sufficed (and would've been more robust against future changes).

2022-08-02 19:51 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
Now that I'm looking at it again, not sure if this is correct either.. This *might* end up going into an infinite loop where read fails for some reason and keeps returning `-1`.

2022-08-02 19:54 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
I suppose something like this would be more robust and deal with edge case of signal interrupt as well.

```c
ssize_t n;
do {
	if ((n = read(...)) < 0 && errno != EINTR)
		break;
} while (n);
```

2022-08-02 19:59 UTC, KlzXS commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
Is that what we are going with?

2022-08-02 20:04 UTC, KlzXS commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
I mean this is a dumb question, but what do we do if we are given an endless input? Like `/dev/zero` or something simply huge. That shouldn't ever happen even on accident, but do we really just try to read it endlessly until the user aborts?

2022-08-02 20:09 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
> Is that what we are going with?

Not sure. The upper `read` doesn't deal with `EINTR` either. So I guess we can leave it at `> 0`.

> I mean this is a dumb question, but what do we do if we are given an endless input?

Any specific reason we're draining the input to begin with? What happens if we don't drain it?

2022-08-02 20:15 UTC, KlzXS commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
Also couldn't we just close the fd? We reopen `stdin` after the call to `load_input()` either way. Closing the fd would offload the task of dealing with the excess data to the kernel. And it can surely handle it much more efficiently.

2022-08-02 20:19 UTC, N-R-K commented on src/nnn.c
>  			DPRINTF_S(strerror(errno));
I suppose we can take this as an opportunity to make this more robust against signals.

```suggestion
		if (input_read < 0) {
			if (errno == EINTR)
				continue;
			DPRINTF_S(strerror(errno));
```

2022-08-02 20:22 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
> Also couldn't we just close the fd? We reopen stdin after the call to load_input() either way

I'd go with that approach as well instead of trying to drain the input.

2022-08-02 20:37 UTC, KlzXS commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
We are doing that. Kind of a weird decision to leave closing of the fd to the caller of the function, but it's called from `readpipe()` as well, which seems to also delegate the responsibility to its caller who finally is the one that opens and closes it. I'm not sure about all that. The other path through main is much simpler.

Also this just looks off to me. How is this even valid syntax.
```c
do
	rfd = open(g_pipepath, O_RDONLY);
while (rfd == -1 && errno == EINTR);
```

2022-08-02 21:07 UTC, N-R-K commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
> Also this just looks wrong to me. How is this even valid syntax.

It's just omitting the  `{}` cus it's a single statement. I've seen (and done) worse stuff...

```c
	n[(char *)memcpy(d, s, n)] = '\0';
```

2022-08-02 21:18 UTC, N-R-K approved these changes
Mostly seems okay to me.

2022-08-02 21:18 UTC, N-R-K commented on src/nnn.c
> +			goto malloc_1;
I think `xrealloc` frees the old memory already, doesn't it?

I mean, given that `free(null)` is a no-op shouldn't be a problem, but just wanted to point it out.

2022-08-02 21:18 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  (1 << 28) /* Support reading in 256MiB */
Any specific reason for picking `256MiB` or just arbitrarily chosen limit?

2022-08-02 21:22 UTC, KlzXS commented on src/nnn.c
> +		while (read(fd, buf, 512) != 0);
> It's just omitting the {} cus it's a single statement.

Oh, I know why it is. But I don't really think it should.

I do like the `3[a]` way of indexing. And if it weren't hard to read that particular statement looks pretty nice. The worst I've done is something along the lines of
```c
ss = strstr(s, "...");
if (ss && ss != s && ss[-1] != '/') ...
```

2022-08-02 21:24 UTC, KlzXS commented on src/nnn.c
> +			goto malloc_1;
Again you are right. I'm sure I saw it a few days ago when I was first looking into it. I say we leave it like that. It might be easier to follow if all paths lead to the same exit.

2022-08-02 21:27 UTC, KlzXS commented on src/nnn.c
> +#define LIST_INPUT_MAX  (1 << 28) /* Support reading in 256MiB */
The original limit was 65536 paths each with `PATH_MAX == 4096` bytes, so 256 MiB in total. It seemed to me that @jarun wanted to keep it in case of invalid paths or something like that even though that's a bit overkill. I mean all of these numbers are arbitrary. Why did I originally pick 65k files? I don't know. It seemed like a nice number.

2022-08-02 21:43 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  (1 << 28) /* Support reading in 256MiB */
The manpage says the limit is 64MiB

https://github.com/jarun/nnn/blob/master/nnn.1#L315

So looks like this was just a mistake. I think we should change this to:

```suggestion
#define LIST_INPUT_MAX  (LIST_FILES_MAX * PATH_MAX)
```

Just like the manpage says.

2022-08-02 21:58 UTC, KlzXS commented on src/nnn.c
> +#define LIST_INPUT_MAX  (1 << 28) /* Support reading in 256MiB */
He might have changed it afterwards. That's fine.

2022-08-02 22:08 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  (LIST_FILES_MAX * PATH_MAX)
@KlzXS Cast this to `ssize_t` to make the CI happy, I guess.

```
 #define LIST_INPUT_MAX  ((ssize_t)LIST_FILES_MAX * PATH_MAX)
```

But now that I think about it, why do we even need this?? Cant we just do `chunk_count >= LIST_FILES_MAX` ? *Even if* we assume all of the paths are `== PATH_MAX` then this still should be enough.

2022-08-02 22:15 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  (LIST_FILES_MAX * PATH_MAX)
Maybe we can just have a check to ensure all paths are `< PATH_MAX`

2022-08-02 22:17 UTC, KlzXS commented on src/nnn.c
> +#define LIST_INPUT_MAX  (LIST_FILES_MAX * PATH_MAX)
It would be enough, in fact it's way more than. Each chunk is 512 KiB. At 16384 files that's 8 GiB. We wouldn't be true to the limit to put it mildly. I'd much rather not do that.

Also someone might change `PATH_MAX` on their system to either be way smaller or even larger. I think it's better to keep it like this.

2022-08-02 22:21 UTC, KlzXS commented on src/nnn.c
> +#define LIST_INPUT_MAX  (LIST_FILES_MAX * PATH_MAX)
I added some extra parentheses. Probably not necessary, but I don't want to have to make another commit just for the CI. It won't hurt.

2022-08-02 22:26 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
The ci was complaining about the multiplication taking place at `int`. And I suppose that'll overflow on systems where int is 32 bits.

The additional braces make it so the mul still takes place in `int` but the result is just casted to ssize_t. Removing the inner braces should make the multiplication happen at `ssize_t`, which should more appropriate in theory.

2022-08-02 22:27 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
But this is mostly pedantic, and I don't know weather we support 16bit int systems or not. So could just leave it be.

I have no strong opinion on this matter.

2022-08-02 22:32 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
Ah just saw this https://github.com/jarun/nnn/pull/1451#discussion_r936073349

Yeah, i think we can leave it be. 16 bit int systems are rarely seen nowadays outside of embedded systems.

2022-08-02 22:41 UTC, KlzXS commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
`ssize_t` is just too exotic of a type for me to reason through type coercion. As for the 16bit systems, I don't think we do. Don't worry too much about it. Lots of other stuff will probably break on 16bit systems. If you want you can spin up a VM and try it.

2022-08-03 01:09 UTC, jarun commented
Please squash the commits.

2022-08-03 09:50 UTC, 0xACE commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
On phone, but why `ssize_t` (`[-1, SSIZE_MAX]`)?

I'd say ˋ(size_t)LIST_FILES_MAX * PATH_MAXˋ is correct, though I haven't followed the entire context of the situation.

2022-08-03 10:22 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
> On phone, but why `ssize_t` (`[-1, SSIZE_MAX]`)?

That's simply because `chunk_count` is `size_t`. 

> I'd say `(size_t)LIST_FILES_MAX * PATH_MAX` is correct, though I haven't followed the entire context of the situation.

That'd work, but then we'd need to cast the comparison to avoid comparing singed vs unsigned type: `(size_t)chunk_count >= LIST_INPUT_MAX`.

2022-08-03 10:38 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
Now that I'm looking at it again, `chunk_count` has no reason to be `ssize_t`. I'll push a commit fixing it soon.

2022-08-03 10:45 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
Pushed https://github.com/jarun/nnn/pull/1451/commits/ddf869675f2c5878f8aa0070fc5186d91bdd15db , see if you guys agree with it or not. @KlzXS @0xACE

2022-08-03 13:11 UTC, 0xACE commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
Looks good (presuming there's no need for `ssize_t` in this case)

I would prefer a easier to read `for`-loop, but I'm okay either way 🙂

2022-08-03 13:16 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
> Looks good (presuming there's no need for `ssize_t` in this case)
> 
> I would prefer a easier to read `for`-loop, but I'm okay either way slightly_smiling_face

Hmm, I'm now also questioning why we are `free`-ing in reverse order instead of the good ol `for (i = 0; i < entries; ++i) free(paths[i]);`

2022-08-03 13:44 UTC, N-R-K commented on src/nnn.c
> +#define LIST_INPUT_MAX  ((ssize_t)(LIST_FILES_MAX * PATH_MAX))
Yeah, I'm not seeing why freeing in reverse would be needed. Just changed it to a regular loop at d208cffa

2022-08-03 14:03 UTC, jarun commented
Guys, please let me know if this is ready to merge. Also, I requested to squash all the changes.

2022-08-03 14:09 UTC, jarun commented
Sure! Thanks!

2022-08-03 15:57 UTC, merged

2022-08-03 15:57 UTC, jarun commented
Thank you!