Show selected items in rm msg
jarun/nnn pull request #1480
Opened 2022-09-07 23:18 UTC by luukvbaal

Close https://github.com/jarun/nnn/issues/1479

2022-09-07 23:28 UTC, N-R-K approved these changes
I remember a couple times I trashed something else in another directory by mistake because they were still selected. So I think showing the selection count makes sense.

2022-09-08 16:28 UTC, jarun requested changes

2022-09-08 16:28 UTC, jarun commented on src/nnn.c
> +		 (selection ? xitoa(nselected) : "hovered"),
Why not something like:

- hovered
- selected 5

2022-09-08 18:08 UTC, luukvbaal commented on src/nnn.c
> +		 (selection ? xitoa(nselected) : "hovered"),
Sure, done.

2022-09-08 19:10 UTC, merged

2022-09-08 19:10 UTC, jarun commented
Thank you!