Adding many new icons and colors
jarun/nnn pull request #1510
Opened 2022-10-24 06:15 UTC by Babkock

[![Screenshot](https://babkock.github.io/images/screenshot.png)](https://babkock.github.io)

Wow people still write programs in C?? Hello I love this program. It has replaced Ranger as a file manager for me, I find it very efficient and fast. I hope this pull request finds you well. Here is a summary of the changes I am proposing:

* Added many new icons, file extensions, and file names
* Added new color for Emacs, lisp, and Org documents (`Magenta2`)
* Added new color for Rust source files (`IndianRed1`)
* C and C++ header files now have their own icon
* C++ is now a slightly different color than C file icon (`DarkSeaGreen2`)
* Added color for various "key" file types (`.pub`, `.key`, `.kbx`) (`Khaki3`)
* Added color for various "lock" file types (`.lock`, `.asc`, `.ssh`)
* Assembly source files now have a color (`Gold1`)
* HTML files now have a color (`LightSteelBlue`)
* Made a separate file icon for archives, to distinguish them from software packages
* Partially-downloaded files now have a clock icon and a color
* The standard home-directory folders "Music", "Downloads", "Pictures", and "Videos" now have the default colors for audio files, downloads, image files, and videos respectively

Please let me know if there are any changes I can make, or any questions you have. If you think something should be a different color, please feel free to suggest it. I tried not to change too much, or change the currently established icons and colors.

2022-10-24 06:33 UTC, N-R-K requested changes

2022-10-24 06:33 UTC, N-R-K commented on src/icons.h
> +#define ICON_ARCHIVE       ICON_STR("", "\uf410"," 📦")
Why remove `FA_FILE_ARCHIVE_O` ?

2022-10-24 06:33 UTC, N-R-K commented on src/icons.h
> +	{"xmonad.hs",          ICON_CONFIGURE,     COLOR_CONFIGURE},
This part is probably not going to get added due to the reasons described [here](https://github.com/jarun/nnn/pull/1419#issuecomment-1179213035).

Could ofc turn this into a hash-table as well for faster lookups, but not sure if it's worth the effort.

2022-10-24 06:48 UTC, jarun commented
We are conservative in this area because adding every new icon increases memory usage and lookup time. And we want directories of the same color.

I understand you are from ranger. nnn follows different design principles.

2022-10-24 06:48 UTC, closed without merging

2022-10-24 06:50 UTC, jarun commented
Also the image leads to your personal website. Why?

2022-10-25 21:10 UTC, Babkock commented
Okay I understand the reasons why although it seems a bit arbitrary. What if I made a patch for extra icons that people could choose to compile in if they wanted, like gitstatus and namefirst? So if you don't want that many icons you don't have to have them. I can remove directory colors, and use hash table idea if you want.

Would you be more open to merging a pull request from me if I took the diff from this, and submitted it as a patch (with directory colors reverted), and adjusted the `Makefile`, `check-patches.sh`, etc.? Or would it be not worth the effort?

2022-10-26 01:28 UTC, jarun commented
I would leave that to @luukvbaal and @N-R-K to decide.

2022-10-26 08:16 UTC, N-R-K commented
I don't think patches like that would be a good idea because it's going collide alot and cause significant maintenance overhead.

The goal with icons isn't to provide every icon under the sun, it's to provide a decent *but small* set of defaults. Users can then add more if they want to.

@Babkock I'll take a look here and see if there were anything that might be worth adding.

2022-10-26 09:12 UTC, N-R-K commented
> @Babkock I'll take a look here and see if there were anything that might be worth adding.

Added ksh, ttf and otf icon in #1511.