fix plugins/wallpaper support for wayland
jarun/nnn pull request #1512
Opened 2022-11-01 15:57 UTC by Darukutsu

nitrogen & pywal don't set background on wayland. Therefore add swww.

2022-11-01 16:54 UTC, N-R-K requested changes

2022-11-01 16:54 UTC, N-R-K commented on plugins/wallpaper
> +	  if [ "$XDG_SESSION_TYPE" = "x11" ]; then
I don't think checking for this is necessary. If nitrogen and wal don't work on wayland then the user probably doesn't have it installed anyways.

2022-11-01 16:54 UTC, N-R-K commented on plugins/wallpaper
> +		printf "swww missing"
I'd drop the `XDG_SESSION_TYPE` check and make this error message more generic, something like: "couldn't find appropriate program to set the wallpaper"

2022-11-01 16:57 UTC, Darukutsu commented on plugins/wallpaper
> +	  if [ "$XDG_SESSION_TYPE" = "x11" ]; then
I think it good to have if you tend to switch between x11 and wayland. Bspwm to hyperland for example.

2022-11-01 16:58 UTC, N-R-K commented on plugins/wallpaper
> +	  if [ "$XDG_SESSION_TYPE" = "x11" ]; then
Ah, I see. Didn't consider people are using x11 and wayland both.

2022-11-01 17:05 UTC, N-R-K approved these changes

2022-11-02 13:04 UTC, merged

2022-11-02 13:04 UTC, jarun commented
Thank you!

2022-11-02 13:05 UTC, jarun commented
@Darukutsu if you can test Wayland, are there any other plugins which need changes to work on Wayland?

2022-11-03 15:15 UTC, Darukutsu commented
@jarun everything look ok, only plugin which behave incorectly is 'preview-tabbed'.
Universal solution for wayland would be using [wlrctl](https://git.sr.ht/~brocellous/wlrctl)
It only works with "urxvt" and need to add line in previewer_loop
```
...

2022-11-03 15:26 UTC, Darukutsu commented
@jarun everything looks ok. The only plugin which behave incorrectly is 'preview-tabbed'.
Universal solution for wayland would be using [wlrctl](https://git.sr.ht/~brocellous/wlrctl)
It only works with 'urxvt' and need to add line
```
previewer_loop() {
...
    wlrctl window focus title:nnn
    
    # Bruteforce focus stealing prevention method,
    # works well in floating window managers like ...
...
}
```
It's not suitable since user may have open multiple instances with nnn, but other than that there is only compositor-specific solutions. I don't think it's needed if using something like 'preview-tui' with kitty.

Also today discovered that alacritty supports XEmbed so maybe add to preview-tabbed
```
elif type alacritty >/dev/null 2>&1 ; then
    TERMINAL="alacritty --embed"
```