Support multiple selection in Kdeconnect plugin
jarun/nnn pull request #1543
Opened 2022-12-13 20:35 UTC by raffaem

2022-12-13 20:56 UTC, KlzXS requested changes
I added the complaints that shellcheck has. Please correct those before we go any further.

2022-12-13 20:56 UTC, KlzXS commented on plugins/kdeconnect
> +if [[ ! -s "$selection" ]];
SC2039: In POSIX sh, [[ ]] is undefined.

2022-12-13 20:56 UTC, KlzXS commented on plugins/kdeconnect
> +while read -d $'\0' file ; do
SC2162: read without -r will mangle backslashes.
SC2039: In POSIX sh, read -d is undefined.
SC2039: In POSIX sh, $'..' is undefined.

2022-12-13 20:56 UTC, KlzXS commented on plugins/kdeconnect
> +echo -en '\0' >> "$selection"
SC2039: In POSIX sh, echo flags are undefined.

2022-12-14 00:54 UTC, N-R-K commented
What is the problem with the current script? Does `kdeconnect-cli` not accept multiple files as cli arg?

2022-12-14 00:57 UTC, N-R-K commented
But in any case, I'd use `xargs -0` instead of a loop. Try to see the existing plugins on how that works.

```sh
    xargs -0 -I{} < "$selection" kdeconnect-cli -d "$id" --share {}
```

Untested by this should probably work.

2022-12-14 18:07 UTC, jarun requested changes

2022-12-14 18:07 UTC, jarun commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
Can you please explain what this change is about? You would also need to document the behaviour.

2022-12-14 23:02 UTC, raffaem commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
I'm not sure I understood your request.

You want me to write here in that part of the script what I did specifically?

2022-12-14 23:03 UTC, raffaem commented
> What is the problem with the current script? Does `kdeconnect-cli` not accept multiple files as cli arg?

It doesn't for me, or at least it doesn't with NULL-separated strings list.

It would be useful if someone can confirm that.

2022-12-14 23:30 UTC, KlzXS commented
> It doesn't for me, or at least it doesn't with NULL-separated strings list.

To avoid the need for appending a NULL you can use `xargs -0` as @N-R-K suggested.

If `kdeconnect-cli` really doesn't want to work with multiple files in one command (you can test that by hand) add a `-n 1` flag to `xargs` so it goes file by file.

Something like `xargs -0 -n 1 < "$selection" kdeconnect-cli -d "$id" --share `

2022-12-15 00:28 UTC, raffaem commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
The current documentation actually describes the new behavior, as it says "Send the selected file**s**"

2022-12-15 00:46 UTC, raffaem commented
> To avoid the need for appending a NULL you can use xargs -0 as @N-R-K suggested.

Yes, that works, thanks.

In fact the man page for `xargs` says, if I interpret it correctly:
>  As  of  GNU xargs version 4.2.9, the default behaviour of xargs is not to have a logical end-of-file marker.  POSIX
       (IEEE Std 1003.1, 2004 Edition) allows this.

> If kdeconnect-cli really doesn't want to work with multiple files in one command (you can test that by hand) add a -n 1 flag to xargs so it goes file by file.

My understanding is that @N-R-K suggested -I implies -L 1, which passes file one by one

2022-12-15 00:47 UTC, raffaem commented
> What is the problem with the current script? Does `kdeconnect-cli` not accept multiple files as cli arg?

The answer seems to be no.

The man page for `kdeconnect-cli` says:

> --share <path or URL>         Share **a** file/URL to a said device

2022-12-15 06:16 UTC, jarun commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
together or one by one? what difference does your change make?

2022-12-15 07:15 UTC, raffaem commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
> together or one by one? what difference does your change make?

Select multiple files with Space and activate the plugin.

Current version: only the first file is sent to the smartphone

This version: All files are sent to the smarphone

2022-12-15 07:30 UTC, KlzXS commented
> My understanding is that @N-R-K suggested -I implies -L 1, which passes file one by one

That's correct, but I prefer using `-n 1` when the argument should get tacked on the end.

I think that snippet from GNU xargs is referencing the `-E` option. Tbh today is the first time I read up on what that does. Apparently you can make `xargs` go until it hits a certain argument. By default either "_" or non-existant. GNU picked one.

2022-12-15 13:28 UTC, jarun commented on plugins/kdeconnect
> +# Author: juacq97, raffaem
OK. Then no further documentation is necessary.

2022-12-15 13:29 UTC, jarun commented
@KlzXS @N-R-K I think this is a good improvement. Please let me know when it's ready to merge.

2022-12-15 13:56 UTC, raffaem commented
I would like to implement also the following:

1. Send the hovered file if no selection is given
2. Support for multiple paired devices (ask the user which one to send to)

I don't know if that would overblow the addon.

Also, what are the requisites to have an addon under bash? Can we assume that, if the user has kdeconnect-cli, then it also has bash?

I'm asking because the shellcheck is remarking bash-like syntax which is not POSIX sh compatible.

2022-12-15 14:15 UTC, jarun commented
1. Send the hovered file if no selection is given

is OK. Other one we can skip.

2022-12-15 14:15 UTC, N-R-K requested changes

2022-12-15 14:15 UTC, N-R-K commented on plugins/kdeconnect
> +cmd="kdeconnect-cli -d '$id' --share '{}'"
Can you check if this works if the filename has `'` in it?

2022-12-15 14:15 UTC, N-R-K commented on plugins/kdeconnect
> +then
try to put the `then` on the same line as the `if`

2022-12-15 15:57 UTC, KlzXS commented
> Also, what are the requisites to have an addon under bash? Can we assume that, if the user has kdeconnect-cli, then it also has bash?

In general we try to keep it as POSIX compliant as possible. The main exception is if it would make the plugin absurdly complex or perform weakly.  One such example would be arrays. POSIX shell doesn't support arrays per se and getting around that is just not worth it.

I wouldn't make any assumptions on what shell someone uses. They might use classic sh for whatever reason or they may use something like fish, ksh, or whatever else. Not all of them are compatible with bash, but they all follow POSIX wherever possible, so it's a safe move.

Other than that we try to keep non-plugin-specific utilities conforming to POSIX. The notable exception being `-0` for `xargs` which is a GNU extension.

2022-12-16 13:41 UTC, raffaem commented
> 1. Send the hovered file if no selection is given
> 
> 
> is OK. Other one we can skip.

Errata corrige: The current plugin does not work in case multiple devices are paired and reachable. The IDs of all devices are sent to kdeconnect-cli, which consider it as the ID of one device only and don't fine it.

I've temporarily fixed it by sending to the first device in the list.

What should we do in case multiple devices are paired and reachable?

2022-12-16 13:45 UTC, raffaem commented on plugins/kdeconnect
> +cmd="kdeconnect-cli -d '$id' --share '{}'"
no it doesn't work. What do you propose?

2022-12-16 14:37 UTC, N-R-K commented on plugins/kdeconnect
> +cmd="kdeconnect-cli -d '$id' --share '{}'"
Just get rid of the notification. I'd rather have a script that works correctly than a flashy one that fails on certain input.

2022-12-16 14:40 UTC, N-R-K requested changes

2022-12-16 14:40 UTC, N-R-K commented on plugins/kdeconnect
> +		exit
Pretty sure this exit should be in the outer branch, no?

2022-12-16 14:40 UTC, N-R-K commented on plugins/kdeconnect
> +xargs -0 < "$selection" -I{} sh -c "$cmd"
Try this:

```suggestion
<"$selection" xargs -0 -I{} kdeconnect-cli -d "$id" --share {}
```

Should fix the quoting issue.

2022-12-16 15:15 UTC, raffaem commented on plugins/kdeconnect
> +		exit
I think it's in the right spot.
If there is no selection but there is an hovered fine, we use the hovered fine.
If there is no selection and there is no hovered file (is that possible?) we exit.
So we don't exit in all cases if there is no selection.

2022-12-17 16:44 UTC, N-R-K commented on plugins/kdeconnect
> +		exit
If there was no selection then we shouldn't be executing the `xargs` command below.

2022-12-17 17:17 UTC, 875d commented on plugins/kdeconnect
> +		exit
@N-R-K I don't understand. If there is no selection, **but** there IS a hovered file, then we execute the xargs below to send the hovered file to the Android device.

If there is no selection, and there is no hovered file, then we don't execute the xargs below: we print an error message and we exit.

That's why the exit at line 40 it's in the "no selection" AND "no hovered file" branch.

Maybe I'm missing something.

You would like the exit on the outer branch, so you would like this:
```
# In case of no selection, use hovered file
if [ ! -s "$selection" ]; then
	if [ -n "$1" ]; then
		printf "$1" > "$selection"
	else
		if [ $notify = 1 ]; then
			notify-send -a "Kdeconnect" "No selected files, and no hovered file"
		else
			echo "[Kdeconnect] No selected files, and no hovered file"
		fi
	fi
	exit
fi
```

But this means that we exit if there is no selection, regardless on whether there is a hovered file to send or not.

Maybe if you could write the code you would like I can understand better :)

2022-12-17 17:20 UTC, raffaem commented on plugins/kdeconnect
> +		exit
@N-R-K I don't understand. 

If there is no selection and there is a hovered file, then we execute the xargs below to send the hovered file to the Android device.

If there is no selection and there is no hovered file, then we don't execute the xargs below: we print an error message and we exit.

That's why the exit at line 40 it's in the "no selection" AND "no hovered file" branch.

Maybe I'm missing something.

If I understand you correctly, you would like the exit on the outer branch, so you would like this:

```
# In case of no selection, use hovered file
if [ ! -s "$selection" ]; then
	if [ -n "$1" ]; then
		printf "$1" > "$selection"
	else
		if [ $notify = 1 ]; then
			notify-send -a "Kdeconnect" "No selected files, and no hovered file"
		else
			echo "[Kdeconnect] No selected files, and no hovered file"
		fi
	fi
	exit
fi
```

But this means that we exit if there is no selection, regardless on whether there is a hovered file to send or not.

Then why the `printf "$1" > "$selection"` at all?

Maybe if you could write the code you would like I can understand better :)

2022-12-17 17:31 UTC, N-R-K commented on plugins/kdeconnect
> +		exit
> Then why the `printf "$1" > "$selection"` at all?

AH, I didn't even notice that. It's not a good idea to mess with the selection file like that. Just run the kdeconnect command there directly instead.

2022-12-17 17:32 UTC, N-R-K commented on plugins/kdeconnect
> +		printf "$1" > "$selection"
```suggestion
		kdeconnect-cli -d "$id" --share "$1"
```

2022-12-17 21:28 UTC, raffaem commented on plugins/kdeconnect
> +		exit
I'm asking for a temporary file. I would like to mantain the connection code at the end since I would like notifications too

2022-12-17 21:29 UTC, raffaem commented
@N-R-K can you check the new implementation?

I also have bash code to manage multiple devices. I don't know if (1) it can be rewritten in POSIX sh (2) you would like to split it into another extension (3) you would like to maintain it like that, commented out

2022-12-17 22:26 UTC, KlzXS commented on plugins/kdeconnect
> +		exit
If you're using `mktemp` add it as a dependency in `README.md`. Though you could also just make two commands for sending and resume on a common path to get your notifications. I'm inclined to leave it up to you.

2022-12-17 22:54 UTC, KlzXS commented
> I don't know if (1) it can be rewritten in POSIX sh

You just opened a deranged can of worms my friend. It _can_ be done, but it's not pretty.
What you are looking for is something like this

```
getname() {
    j=0
    for name in "$@"; do
        printf "%d. %s\n" "$j" "$(eval printf "\${$j})"
        j=$((j+1))
    done

    read -r -p "Choice: " choice
    devname="$(eval printf "\${$choice})"
    printf "%s" "$devname"
}

devname=$(getname $(kdeconnect-cli --list-available --name-only 2>/dev/null))
```

might need slight corrections and I have no idea what the output of `kdeconnect` actually looks like so you might even need to transform that a bit. But there you go, that's how you do arrays POSIX style, by manipulating the arguments "_array_".

2022-12-18 03:39 UTC, N-R-K commented
@raffaem 

1. Commented out code is almost always a bad sign, so I like the new `note` function.
2. We can add multi-device support - but let's do that on another PR. For now just focus on selection support.
3. I don't think there's any need for abusing the selection file and don't think there was any need for a tempfile either.

I've pushed some changes. Untested, please let me know if it works fine or not.

If it works, then I think we can merge this (and then figure out multi-device support; which I think can be done without bash).

Also in the future - please use a separate git branch when opening pull requests.

2022-12-18 08:42 UTC, raffaem commented
Yes it works.

```
send < "$selection"
```

I don't understand why this line works

```
[ -p "$NNN_PIPE" ] && printf "-" > "$NNN_PIPE" # clear selection
```
Does this work because the interpreter, when it meets the and operator, evaluates the second term only if the first term is true?

Is this guaranteed by POSIX? The evaluation of the second term if and only if the first is true?

So it's a bit of a hack to write it in one line?

```
printf "$1" | send
```

This works because `xargs` read from stdin?

I didn't know you could pipe into a function.

> Also in the future - please use a separate git branch when opening pull requests.

I didn't know the PR would give you write permission on my repo.

Does it give you write permission only on the branch on which the PR is based?

2022-12-18 10:37 UTC, N-R-K commented
> I don't understand why this line works
> 
> ```
> [ -p "$NNN_PIPE" ] && printf "-" > "$NNN_PIPE" # clear selection
> ```

It's because of how "logical-operators" work. Look up "short-circuiting", I bet someone one the internet has probably done a better job at explaining it more than I could.

> ```
> printf "$1" | send
> ```
> 
> This works because `xargs` read from stdin?
> 
> I didn't know you could pipe into a function.
Yes. And the `<` operator redirects a processes' stdin.

> Does it give you write permission only on the branch on which the PR is based?

Only the branch that you PR-ed from. (And I'll lose it when this PR is closed).

2022-12-18 10:39 UTC, merged

2022-12-18 10:47 UTC, N-R-K commented
Thanks, merged the PR. Let's discuss multi-device support on another PR.

I think you should be able to do with without bash, here's some (completely untested) snippet to get to started @raffaem:

```
names=$(kdeconnect-cli --list-available --name-only 2>/dev/null)
printf "$names" | while IFS=$(printf "\n") read -r name; do
	i=0
	printf "%d. %s\n" "$i" "$name"
	i=$(( i + 1 ))
done
printf "pick a device: "
read -r pick
if [ -n "$pick" ] && [ "$pick" -eq "$pick" ]; then
	# use sed/awk to grab the nth 
fi
```

2022-12-18 12:32 UTC, jarun commented
Thank guys!

2022-12-26 17:54 UTC, raffaem commented
> Thanks, merged the PR. Let's discuss multi-device support on another PR.
> 
> I think you should be able to do with without bash, here's some (completely untested) snippet to get to started @raffaem:
> 
> ```shell
> names=$(kdeconnect-cli --list-available --name-only 2>/dev/null)
> printf "$names" | while IFS=$(printf "\n") read -r name; do
> 	i=0
> 	printf "%d. %s\n" "$i" "$name"
> 	i=$(( i + 1 ))
> done
> printf "pick a device: "
> read -r pick
> if [ -n "$pick" ] && [ "$pick" -eq "$pick" ]; then
> 	# use sed/awk to grab the nth line from $names
> fi
> ```

isn't `"$pick" -eq "$pick"` always TRUE?

2022-12-26 18:34 UTC, N-R-K commented
> isn't `"$pick" -eq "$pick"` always TRUE?

No, because `$pick` might not be an integer. `-eq` tests for numeric equality, so if `$pick` happened to be a non numeric string, then it'll error.

```sh
[~]~> test 5 -eq five
test: integer expression expected: five
```

It's basically an idiomatic way to check weather a variable is an integer or not.