[kdeconnect] Multidevice support
jarun/nnn pull request #1551
Opened 2022-12-27 15:21 UTC by raffaem

2022-12-27 17:14 UTC, N-R-K requested changes

2022-12-27 17:14 UTC, N-R-K commented on plugins/kdeconnect
> +	devname=$(printf "%s" "$names" | awk 'NR==1')
If there's just one name, why call awk on it?

2022-12-27 17:14 UTC, N-R-K commented on plugins/kdeconnect
> +	printf "%s" "$names" | while IFS=$(printf "\n") read -r name; do
This loop can probably be replaced by something like this ` printf "%s" "$names" | awk '{ print NR ". " $0 }'`.

2022-12-27 17:14 UTC, N-R-K commented on plugins/kdeconnect
> +		printf "You have selected: %s\n" "$devname"
Don't think this is necessary. The user can figure out what he selected by looking at the list.

2022-12-28 11:27 UTC, N-R-K commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
What's this about?

2022-12-28 11:44 UTC, raffaem commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
if you pass a directory, kndeconnect creates an empty file on the device with the name of the directory. Basically it doesn't support directory transfers.

2022-12-28 12:10 UTC, N-R-K commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
As far as I see, this simply filters out directories, right? It doesn't recursively send all the files inside the dir?

If that's the case, then just leave it out. The user can simply not select a directory. And if he does select one, it's better to see the empty file than to silently discard his selection.

2022-12-28 13:04 UTC, raffaem commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
Yes it just filters out directory.

1. But I think we will need some kind of checks. What happens if you send over a block device?
2. In general, how can I have xargs call a user-defined function? On SO [I found I can export the function](https://stackoverflow.com/a/11003457/1719931), but `shellcheck` complains that is not POSIX sh-compatible.

2022-12-28 13:31 UTC, raffaem commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
it hangs

2022-12-28 14:49 UTC, N-R-K commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
In that case, filtering out only the files seems like a good idea. Does this work?

```diff
diff --git a/plugins/kdeconnect b/plugins/kdeconnect
index 0d3ef8b7..209bf137 100755
--- a/plugins/kdeconnect
+++ b/plugins/kdeconnect
@@ -21,8 +21,18 @@ note() {
 	fi
 }
 
+# kdeconnect doesn't cope with non-files
+filter_files() {
+	xargs -0 -I{} sh -c \
+		'if [ -f "{}" ]; then'\
+		'	printf "%s\0" "{}";'\
+		'else'\
+		'	printf "Error: not a file: %s\n" "{}" >&2;'\
+		'fi;'
+}
+
 send() {
-	xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
+	filter_files | xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
 	note "Files sent"
 }
 
```

2022-12-28 16:13 UTC, raffaem commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
No it says:
```
Pick a device: 1
	printf "%s\0" "src";: -c: line 2: syntax error: unexpected end of file
	printf "%s\0" "CHANGELOG";: -c: line 2: syntax error: unexpected end of file
	printf "%s\0" "LICENSE";: -c: line 2: syntax error: unexpected end of file
```

but I made it to work by removing the `\` characters :)

2022-12-28 16:13 UTC, raffaem commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
How can we call:

```
note "Error: not a file:
```

instead of:

```
printf "Error: not a file:
```
?

2022-12-29 09:39 UTC, N-R-K commented on plugins/kdeconnect
> +	xargs -0 -I{} sh -c 'if [ ! -d "{}" ]; then printf "%s\0" "{}"; fi;' |  xargs -0 -I{} kdeconnect-cli --name "$devname" --share {}
Don't think that's possible without doing something dirty. So I'd leave it be.

2022-12-29 09:41 UTC, N-R-K approved these changes
@jarun This should be good to merge.

2023-01-02 16:53 UTC, merged

2023-01-02 16:53 UTC, jarun commented
Thanks guys!