General simplification
jarun/nnn pull request #1566
Opened 2023-01-14 21:32 UTC by KlzXS

`get_output()`:
- The function now uses `UTIL_SH_EXEC` to execute the command.
- The command writes directly to a tmp file where applicable.
- Got rid of parameter `multi` as it's no longer needed.
- A bad use case is now blocked.
- Got rid of `cmd` and `fd` as they are no longer needed. Correct me if I'm wrong, but `fd` wasn't ever used and there is a path to call `free(cmd)` while it's `NULL` (`multi == FALSE` and `pipe()` failing).
- The comment above wasn't accurate, now it is.
- `g_buf` is now clobbered only in some cases. Not that it would matter much, I imagine.

@jarun I still need to look into using `UTIL_SH_EXEC` for running GUI apps as plugins as you suggested, but I thought I should share this regardless.

I only tried the simple case of setting `NNN_HELP` and opening the help screen. I might do more extensive testing later, or if someone wants to give it a shot as well that would be great.

2023-01-15 02:53 UTC, jarun commented
I see the following issue with `nnn -i` (to show file info):

Constant message in the info bar: `Usage: file [-bcCdEhikLlNnprsSvzZ0] [--apple] [--extension] [--mime-encoding]`

2023-01-15 03:34 UTC, jarun commented
I think all internal commands are failing e.g. listing a zip file results in:

```
atool: no command specified
Try `atool --help' for more information.
```

2023-01-15 04:41 UTC, jarun requested changes

2023-01-15 04:41 UTC, jarun commented on src/nnn.c
> +		spawn(utils[UTIL_SH_EXEC], file, arg1, arg2, F_MULTI);
Maybe we are seeing the missing argument issue because `sh` expects a single argument string... like:

    sh "file arg1 arg2"
But concatenating would require an internal temporary buffer.

2023-01-15 05:45 UTC, jarun approved these changes

2023-01-15 05:46 UTC, merged

2023-01-15 05:46 UTC, jarun commented
Thanks @KlzXS!

2023-01-15 18:51 UTC, jarun commented
@KlzXS I reverted this change and the changes I made on top of it. It appears concatenating the arguments don't work when the filename has spaces in it due to the usual shell quirks.

2023-01-15 18:51 UTC, jarun commented
Please re-raise if you find a way around it.

2023-01-15 19:57 UTC, KlzXS commented
I guess it's best to forego using `UTIL_SH_EXEC` and go the good old way it was while using the rest of the simplification.

I also had thoughts of implementing a new variant of `spawn()` that would allow us to pass in file descriptors to be mapped to stdin, stdout and stderr. I think a few places in the code might benefit from that. Say we pipe the output directly into `nnn` instead of writing to a file and reading from it. What do you think?

2023-01-15 20:50 UTC, jarun commented
> I guess it's best to forego using UTIL_SH_EXEC and go the good old way it was while using the rest of the simplification.

I agree!

> I also had thoughts of implementing a new variant of spawn() that would...

We had problems and breaks with such experiments earlier. I think spawn() is good for now.

2023-01-15 20:56 UTC, KlzXS commented
> I think spawn() is good for now.

Sure. I'll do it the old way. I might submit my experiment at a later date. Might.

2023-01-16 02:48 UTC, jarun commented
👍

2023-01-16 03:39 UTC, N-R-K commented
> I also had thoughts of implementing a new variant of `spawn()` that would allow us to pass in file descriptors to be mapped to stdin, stdout and stderr. I think a few places in the code might benefit from that. Say we pipe the output directly into `nnn` instead of writing to a file and reading from it. What do you think?

@KlzXS You may want to take a look at [`posix_spawn`](https://linux.die.net/man/3/posix_spawn) - it's much faster than `fork + dup + exec` and I think it should be capable of doing what you want. You can take a look at nsxiv for some reference (the error handling is quite ugly, but otherwise it works quite well): [util.c#L251-L294](https://codeberg.org/nsxiv/nsxiv/src/commit/75849adb88187ab93ab2224706693676a3ea0fb3/util.c#L251-L294)