Simplify the command as plugin codepath
jarun/nnn pull request #1571
Opened 2023-01-25 16:50 UTC by KlzXS

Invoking commands as plugins now uses `UTIL_SH_EXEC` which should allow for lifting the restrictions about the placement of `$nnn` it some commands. The new behavior also requires the user to quote `$nnn` so that the shell can properly expand it, since we no longer pass it as a separate argument to `exec()`. An exception is made is ` $nnn` is detected to be a suffix. In that case the old behavior is preserved as to not break users' configs. We can slate this for removal at some point if you wish, but for now I think it's best to keep it.

As always, my testing is rather light, so you should probably try it out for yourself before merging. Have you considered developing an environment for automatic testing of regressions or is that just not worth it at this point?

2023-01-25 17:54 UTC, KlzXS commented
The CI failing is the result of my poor git branch management in this case. If the other PR is merged it should go away on its own. I made the PR under the assumption that the other changes were already merged.

2023-01-27 15:35 UTC, jarun requested changes

2023-01-27 15:35 UTC, jarun commented on plugins/README.md
> +| `c:!convert "$nnn" png:- \| xclip -sel clipboard -t image/png*` | Copy image to clipboard |
Please update the man page as well.

2023-01-28 02:53 UTC, merged

2023-01-28 02:53 UTC, jarun commented
Thank you!

2023-01-28 02:57 UTC, jarun commented on plugins/README.md
> +| `c:!convert "$nnn" png:- \| xclip -sel clipboard -t image/png*` | Copy image to clipboard |
I'll take care of this.