feat(preview-tui): add `wezterm` support
jarun/nnn pull request #1578
Opened 2023-02-02 08:19 UTC by kuntau

This PR add support for [wezterm](https://wezfurlong.org/wezterm/) in `preview-tui` plugin.

Wezterm supports all three image protocols: `iTerm2`, `sixel` and `kitty` protocol.

2023-02-02 10:55 UTC, jarun commented
@luukvbaal @N-R-K please have a look.

2023-02-02 13:57 UTC, N-R-K commented
The patch looks OK to me. But I'm not interested in compiling wezterm (and it's dependency tree) to test it out. Let's wait for @luukvbaal to take a look.

2023-02-02 14:07 UTC, kuntau commented
> The patch looks OK to me. But I'm not interested in compiling wezterm (and it's dependency tree) to test it out. Let's wait for @luukvbaal to take a look.

There's [pre-compiled binary](https://github.com/wez/wezterm/releases) for most system. Unless you _use arch btw_

2023-02-03 15:00 UTC, luukvbaal requested changes
No complaints otherwise.

2023-02-03 17:42 UTC, kuntau commented on plugins/preview-tui
> +#   Wezterm should work out of the box. If `NNN_PREVIEW_IMGPROG` is not specified it will use
Hmm.. I tried running wezterm with no config and still work fine. What OS are you on?

2023-02-03 17:44 UTC, luukvbaal commented on plugins/preview-tui
> +#   Wezterm should work out of the box. If `NNN_PREVIEW_IMGPROG` is not specified it will use
Linux

2023-02-03 19:37 UTC, kuntau commented on plugins/preview-tui
> +            if [ "$SPLIT" = "v" ]; then split="--horizontal"; else split="--bottom"; fi
What do you suggest? Since every terminal have different flags

2023-02-03 19:39 UTC, kuntau commented on plugins/preview-tui
> +#   Wezterm should work out of the box. If `NNN_PREVIEW_IMGPROG` is not specified it will use
Did you manage to get it working? Can you check if `$WEZTERM_PANE` is set too? Any of them should be ok

2023-02-03 19:57 UTC, N-R-K commented on plugins/preview-tui
> +            if [ "$SPLIT" = "v" ]; then split="--horizontal"; else split="--bottom"; fi
> Copying this list of variables for each supported option is getting annoying.

I was about to make this exact comment. Can't we just export the variables and let the child inherit them?

2023-02-03 20:16 UTC, luukvbaal commented on plugins/preview-tui
> +            if [ "$SPLIT" = "v" ]; then split="--horizontal"; else split="--bottom"; fi
No I think we do have to pass them, the terminal splits don't inherit the environment AFAIK.

> What do you suggest? Since every terminal have different flags

I was thinking to make single list of env vars and manipulate them into the proper flags in a case statement, not sure if it's feasible.

2023-02-03 20:22 UTC, N-R-K commented on plugins/preview-tui
> +            if [ "$SPLIT" = "v" ]; then split="--horizontal"; else split="--bottom"; fi
> the terminal splits don't inherit the environment AFAIK

Maybe `env` can work? Something like `env VAR=VALUE $app`. Otherwise, I'm out of ideas.

2023-02-03 22:53 UTC, luukvbaal commented on plugins/preview-tui
> +    elif [ -n "$WEZTERM_UNIX_SOCKET" ]; then
Yes, `$WEZTERM_PANE` is set, and works.
```suggestion
    elif [ -n "$WEZTERM_PANE" ]; then
```

2023-02-03 22:57 UTC, luukvbaal commented on plugins/preview-tui
> +            if [ "$SPLIT" = "v" ]; then split="--horizontal"; else split="--bottom"; fi
I don't think so, the problem is that the terminal split commands are just instructions for the terminal to split itself. The terminal is then doing the actual forking and it doesn't inherit any environment, which is the exact reason why those terminals/tmux have an env flag to set the environment when splitting. I'll try the list manipulation idea sometime, not blocking for this PR.

2023-02-03 23:39 UTC, kuntau commented on plugins/preview-tui
> +    elif [ -n "$WEZTERM_UNIX_SOCKET" ]; then
Which distro you're running on @luukvbaal?

2023-02-03 23:42 UTC, luukvbaal approved these changes

2023-02-04 01:34 UTC, merged

2023-02-04 01:34 UTC, jarun commented
Thank you!

2023-02-04 01:41 UTC, luukvbaal commented on plugins/preview-tui
> +    elif [ -n "$WEZTERM_UNIX_SOCKET" ]; then
Arch linux, I might start using this on my windows machine though so thanks(if it works there?)!