Preview-tui!: refactor environment variables
jarun/nnn pull request #1580
Opened 2023-02-08 13:00 UTC by luukvbaal

Problem:    List of environment variables is copied for each previewer.
            Environment variable names are too general.
Solution:   Parameterize environment variable flags with static list of
            variables. Prepend user-facing variables with `NNN_`.

2023-02-08 16:07 UTC, jarun requested changes

2023-02-08 16:07 UTC, jarun commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
What is the problem with using the default pager?

2023-02-08 16:09 UTC, jarun requested changes

2023-02-08 16:09 UTC, jarun commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
The problem is - it's difficult for users to decide which one to setup which one not to.

Maybe we can list and document all of them in one place.

2023-02-08 16:37 UTC, luukvbaal commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
I think there is merit to not using the default shell `$PAGER` to avoid issue like this: https://github.com/jarun/nnn/issues/1069.
This way we enforce a value that works by default.

2023-02-09 12:49 UTC, jarun commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
I think we have the PAGER thing documented somewhere in the wiki. Even if that's not the case, users have to know that it should be `less -Ri`. Changing the variable name does not help.

2023-02-09 13:00 UTC, luukvbaal commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
It helps in the sense that new users that have defined `$PAGER` in their shell profile will no longer run into problems...

2023-02-12 00:19 UTC, luukvbaal commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
To reiterate: I think it's bad practice to blindly import default shell variables that we know can cause issues with `preview-tui`.

Why not set default values that we know works but still allow modifying them through shell variables, prefixed with `_NNN`. That why I made that change but if you disagree I can omit that. The main point of this PR was refactoring/de-duplicating the list of shell variables to be passed to the previewer.

2023-02-12 02:00 UTC, jarun commented on plugins/preview-tui
> +#   - less or $NNN_PAGER
Makes sense.

2023-02-12 02:00 UTC, jarun commented
LGTM. @N-R-K please have a look.

2023-02-12 02:26 UTC, N-R-K commented
Seems to work OK, tested with xterm.

2023-02-12 02:28 UTC, merged

2023-02-12 02:29 UTC, jarun commented
Thanks guys!