Added patch for colemak keyboard layout. Existing renamed to colemak-dh
jarun/nnn pull request #1587
Opened 2023-02-17 05:03 UTC by jacmoe

A PR as discussed in #1584

2023-02-17 13:11 UTC, luukvbaal requested changes

2023-02-17 13:11 UTC, luukvbaal commented on Makefile
> +	patch --forward $(PATCH_OPTS) --strip=1 --input=$(COLEMAK-DH)/mainline.diff
Please also add the reverse patch in the Makefile below. We do this to keep the repository in a clean state:
```diff
+++ b/Makefile
@@ -361,6 +361,9 @@ endif
 ifeq ($(strip $(O_COLEMAK)),1)
        patch --reverse $(PATCH_OPTS) --strip=1 --input=$(COLEMAK)/mainline.diff
 endif
+ifeq ($(strip $(O_COLEMAK-DH)),1)
+       patch --reverse $(PATCH_OPTS) --strip=1 --input=$(COLEMAK-DH)/mainline.diff
+endif

 skip: ;
```

We normally also add a new patch to the array in the `patches/checkpatches.sh` script but in this case I think we are good with just a single colemak patch in there.

2023-02-17 13:16 UTC, jarun commented
@luukvbaal please merge when this is ready.

2023-02-17 14:09 UTC, jacmoe commented on Makefile
> +	patch --forward $(PATCH_OPTS) --strip=1 --input=$(COLEMAK-DH)/mainline.diff
Will do!

2023-02-18 01:36 UTC, jacmoe commented on Makefile
> +	patch --forward $(PATCH_OPTS) --strip=1 --input=$(COLEMAK-DH)/mainline.diff
Done!
But, there is a slight issue: O_COLEMAK and O_COLEMAK-DH are mutually exclusive. Every test in the check_patches script fails when it tries to apply both of those.
Since I am not familiar with the patch system, I can't do much about that.

2023-02-18 01:40 UTC, jacmoe commented
Updated the PR with suggested changes, but `check_patches` fails whenever it tries to apply both `O_COLEMAK` and `O_COLEMAK-DH`. Those two are mutually exclusive.

2023-02-18 04:47 UTC, N-R-K commented
> Updated the PR with suggested changes, but `check_patches` fails whenever it tries to apply both `O_COLEMAK` and `O_COLEMAK-DH`. Those two are mutually exclusive.

Prefer `O_COLEMAK` over `O_COLEMAK-DH` when both are set. You can do something like this:

https://github.com/jarun/nnn/blob/b49cc28d80bc2236c33954b625245d9fbb180279/Makefile#L69-L79

- - -

But honestly, I feel like the current patching system is not very scalable. It used to work fine when there was only 2~3 patches, but every new patch will end up increasing the number of possible combination by an exponential factor (2<sup>n</sup>).

Though I don't exactly have a better solution either.

2023-02-18 04:55 UTC, N-R-K commented
Also the difference between colemak and colemak-dh seems to be really low (looks like just 3~4 changes).

So I'd rather just rm `colemak-dh` if @jarun agrees.

2023-02-18 05:46 UTC, jacmoe commented
I tried to remedy the Makefile, but it errors out. Individually, both O_COLEMAK and O_COLEMAK-DH applies succesfully, but not together.
Would be better if both could coexist because I suspect there's quite a few colemak-dh users among the potential audience of `nnn`. I am fine with ordinary colemak because I don't have an ortholinear / split keyboard.

2023-02-19 00:37 UTC, luukvbaal commented
> Also the difference between colemak and colemak-dh seems to be really low (looks like just 3~4 changes).

> So I'd rather just rm colemak-dh if @jarun agrees.

I'm not familiar with these keyboard layouts to judge whether they both warrant their own keyboard layouts for nnn. If they differ enough where it matters, I would be fine with providing a patch for both, given that we allow keymap patches...

> Updated the PR with suggested changes, but check_patches fails whenever it tries to apply both O_COLEMAK and O_COLEMAK-DH. Those two are mutually exclusive.

I suggested to omit adding an additional entry to the checkpatches array.

> But honestly, I feel like the current patching system is not very scalable. It used to work fine when there was only 2~3 patches, but every new patch will end up increasing the number of possible combination by an exponential factor (2n).

The patch system itself is scalable enough I think, but indeed the checkpatches script isn't really. However it it just to catch merge conflicts. So like I said I don't think we need multiple entries for keymap patches that edit the same lines.

2023-02-19 01:17 UTC, jacmoe commented
That makes sense!
If the `COLEMAK-DH` is removed from the check script, all is fine. Yes, it will fail at compile time if both are set, but at least it's a logical thing to do.

The difference between dh and standard colemak is significant enough to warrant a patch for each.

2023-02-19 15:18 UTC, N-R-K approved these changes
Looks OK, I think. Though, I would've preferred to just rm the `dh` variant.

2023-02-19 16:22 UTC, merged