add shell_escape() to properly escape filenames fed to shell
jarun/nnn pull request #1616
Opened 2023-03-22 04:10 UTC by N-R-K

Fixes: https://github.com/jarun/nnn/issues/1615

2023-03-24 19:40 UTC, KlzXS approved these changes
The changes here look good. Did you want to replace all potentially problematic paths in shell commands we invoke in this PR or did you want to leave that for another one when all such places are identified.

In either case commands in `patterns` could use this treatment, though `shell_escape()` won't suffice as is. In some of them paths are passed inside bigger string in `''`, see `P_CPMVRNM`.

Escaping with `''` should work for all potentially problematic paths except maybe those that contain certain non-printable characters. I think those need some different type of escaping, but I'm sure we don't need to worry about that<sup>TM</sup>.

2023-03-24 21:21 UTC, jarun requested changes

2023-03-24 21:21 UTC, jarun commented on src/nnn.c
> +static bool shell_escape(char *output, size_t outlen, const char *s)
Would this handle unicode characters as well?

2023-03-24 21:51 UTC, KlzXS commented on src/nnn.c
> +static bool shell_escape(char *output, size_t outlen, const char *s)
I had no problem both with and without escaping `t̶̩͇̜̔͒́̈́̃ē̸̪̽s̶̨͛t̴͍̙̳̳͙̅f̷͎̐͒ỉ̴̧̦͙̯̞̇̿l̵̡̯̝̞̑͌̄͊e̶͉̟̙̫͑͂̉` while working with it in the shell. If it can handle Zalgo it can handle sane everyday Unicode, I'd say.

PS. Sorry if this breaks your emails.

2023-03-24 21:53 UTC, jarun commented on src/nnn.c
> +static bool shell_escape(char *output, size_t outlen, const char *s)
Cool!

2023-03-25 04:15 UTC, N-R-K commented
> Did you want to replace all potentially problematic paths in shell commands we invoke in this PR or did you want to leave that for another one when all such places are identified.

Ideally, yes. But doesn't necessarily need to be done now. We can fix the other cases up in a later PR.

2023-03-27 22:58 UTC, merged

2023-03-27 22:58 UTC, jarun commented
Thank you!