Update nerd-font icons to v3
jarun/nnn pull request #1638
Opened 2023-05-04 23:10 UTC by luukvbaal

* Replace all nerd-font code points with their unicode icon in `icons.h`. (`for i in "$(cat icons.h)"; do echo "$i"; done`)
* Update all deprecated nerd-font code points in `icons.h` and `.iconlookup` with their v3 variants. (`nerdfix check icons.h`)
* Add some "recent" `icons.h` additions to `.iconlookup` (should make it completely in sync again with the new top level icons from `icons.h`...

2023-05-04 23:17 UTC, jarun requested changes

2023-05-04 23:17 UTC, jarun commented on plugins/.iconlookup
> +    icons["ex"][1] = icons["elixir"][1]; icons["ex"][2] = icons["elixir"][2]
Have you added new icons? If yes, why should that be part of this PR?

2023-05-04 23:27 UTC, N-R-K commented on plugins/.iconlookup
> +    icons["ex"][1] = icons["elixir"][1]; icons["ex"][2] = icons["elixir"][2]
I think it's just syncing iconlookup with existing icons header.

2023-05-04 23:29 UTC, luukvbaal commented on plugins/.iconlookup
> +    icons["ex"][1] = icons["elixir"][1]; icons["ex"][2] = icons["elixir"][2]
> > Add some "recent" icons.h additions to .iconlookup (should make it completely in sync again with the new top level icons from icons.h...)

Yes I added some recent additions to `icons.h` that were missing from `.iconlookup`...

2023-05-04 23:30 UTC, jarun commented on plugins/.iconlookup
> +    icons["ex"][1] = icons["elixir"][1]; icons["ex"][2] = icons["elixir"][2]
OK.

2023-05-04 23:30 UTC, N-R-K commented on src/icons.h
> +#define ICON_ARROW_UP      ICON_STR(MD_ARROW_UPWARD, "󰁝", "⬆")
Any specific reason for switching to "raw icons" from the escaped version?

(TBH I prefer it this way, so that the icon is visible in my editor compared to having to lookup the code point. But curious if there's any other reason.)

2023-05-04 23:32 UTC, luukvbaal commented on src/icons.h
> +#define ICON_ARROW_UP      ICON_STR(MD_ARROW_UPWARD, "󰁝", "⬆")
I needed to convert it to raw icons to be able to run the `nerdfix` program on it. Saw no reason to convert it back as indeed it seems more convenient than having the code points in `icons.h`.

2023-05-04 23:32 UTC, N-R-K commented
> @N-R-K can you please test and confirm this one?

Will do in a bit.

2023-05-04 23:33 UTC, jarun approved these changes

2023-05-04 23:33 UTC, jarun commented on plugins/.iconlookup
> +    color_elixir=104  #color_elixir=109    #color_elixir="143;188;187"
We need to document the change in support model for Nerd Fonts somewhere. The best place is:

https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

2023-05-05 00:02 UTC, N-R-K approved these changes
Just tried it out with a v3 nerd font and everything seems to be working OK.

2023-05-05 00:06 UTC, merged

2023-05-05 00:06 UTC, jarun commented
Thanks guys! Please update the wiki!