Add djvu icon
jarun/nnn pull request #1673
Opened 2023-06-15 14:46 UTC by JingMatrix

Use paperclip as icon since it is used by DjVuLibre.

2023-06-15 14:53 UTC, N-R-K requested changes

2023-06-15 14:53 UTC, N-R-K commented on src/icons.h
> +	{"djvu",       ICON_DJVU,           0},
Should use the same color as pdf, epub etc.

```suggestion
	{"djvu",       ICON_DJVU,           COLOR_DOCS},
```

2023-06-15 14:53 UTC, N-R-K commented on src/icons.h
> +#define ICON_DJVU          ICON_STR("FA_PAPERCLIP", "", "📎")
The `FA_*` stuff are macros, you're not supposed to surround them in quotes.

```suggestion
#define ICON_DJVU          ICON_STR(FA_PAPERCLIP, "", "📎")
```

2023-06-15 14:58 UTC, JingMatrix commented
Thanks for your review, now they are working as expected.

2023-06-15 18:01 UTC, jarun commented
@N-R-K is this ready to merge?

2023-06-16 03:49 UTC, N-R-K approved these changes
looks good to me.

2023-06-16 06:42 UTC, merged

2023-06-16 06:42 UTC, jarun commented
Thanks guys!