fix some macro issues
jarun/nnn pull request #1679
Opened 2023-07-01 03:29 UTC by N-R-K

### do not define internal libc macros

macros like `__USE_XOPEN` are internal to libc and shouldn't be defined
by the user. the proper macro to define is `_XOPEN_SOURCE`.

defining `_XOPEN_SOURCE_EXTENDED` shouldn't be needed anymore since
according to the manpage (`man feature_test_macros`):

> defining _XOPEN_SOURCE with a value of 500 or greater produces the same
> effects as defining _XOPEN_SOURCE_EXTENDED.

but define it anyways, just in case.

### define _FILE_OFFSET_BITS 64 unconditionally

according to the manpage, it won't have any effect on 64bit system
anyways. and musl always uses 64bit so this macro doesn't have any
effect there either.

### define _GNU_SOURCE unconditionally

2023-07-01 04:00 UTC, N-R-K commented
Okay, I give up. No clue why macos is failing, it is completely evil.

2023-07-04 14:33 UTC, jarun requested changes

2023-07-04 14:33 UTC, jarun commented on src/nnn.c
> +#define _GNU_SOURCE
We treat warnings as errors in compilation options. Is there are chance of this failing on any platform due to double definition?

2023-07-04 14:45 UTC, N-R-K commented on src/nnn.c
> +#define _GNU_SOURCE
The CI seems to be happy, but I've dropped the _GNU_SOURCE commit, just in case.

My main goal was to remove using internal libc macros but macos kinda ruined that.

As for `_FILE_OFFSET_BITS`, glibc recommends defining it to 64 unconditionally AFAIK. So it should be okay.

2023-07-04 14:51 UTC, merged

2023-07-04 14:51 UTC, jarun commented
Thank you!