fix O_NERD and O_EMOJI on macOS
jarun/nnn pull request #1694
Opened 2023-07-18 18:58 UTC by FelixKratz

This fixes the problem discussed in #1692 

I had to remove the "fast redraw" path, I don't know if this is a problem.

2023-07-19 14:35 UTC, N-R-K requested changes
Thanks for your effort, but frankly I'm not very happy with this patch because `ifdef` mess like this gets out of hand really quickly (and `nnn` has too much ifdef already IMO).

> The important thing seems to be the clear() call.

If I change `erase()` to `clear()` and then hold down `j`, I see severe flickering whenever it scrolls close to the bottom of the screen. Do you not see it on your end?

2023-07-19 15:10 UTC, FelixKratz commented
I understand that this is not a very elegant patch but it was the only patch that seemed to work for me.

My personal patch for this problem will be to revert the nerdfont update.

2023-07-19 15:10 UTC, closed without merging

2023-07-22 16:36 UTC, N-R-K commented
> I have also tried to keep the "fast redraw" path by utilizing `clrtoeol` but that did not work.

Btw, what exactly did you try? Does the following make any difference?

```diff
@@ -4192,6 +4192,8 @@ static void printent(const struct entry *ent, uint_t namecols, bool sel)
        char ind = '\0';
        int attrs;
 
+       clrtoeol();
+
        if (cfg.showdetail) {
                int type = ent->mode & S_IFMT;
```

2023-07-23 18:16 UTC, FelixKratz commented
I have tried adding the `clrtoeol` call just after https://github.com/jarun/nnn/blob/b835cfcc2abf0503966dec1b9226b3a7c34d371a/src/nnn.c#L6507

and
https://github.com/jarun/nnn/blob/b835cfcc2abf0503966dec1b9226b3a7c34d371a/src/nnn.c#L6520

Didnt help at all with the problem.