preview-tui SSH compatibility
jarun/nnn pull request #1695
Opened 2023-07-20 10:19 UTC by amalgame21

When accessing the remote machine through SSH, skip ueberzug preview method which does not support preview in SSH, even though ueberzug in installed on the remote machine.

2023-07-20 17:51 UTC, jarun commented
@luukvbaal @N-R-K please review and approve if looks good.

2023-07-20 17:54 UTC, N-R-K requested changes

2023-07-20 17:54 UTC, N-R-K commented on plugins/preview-tui
> +    elif exists ueberzug && { [ -z "$NNN_PREVIEWIMGPROG" ] || [ "$NNN_PREVIEWIMGPROG" = "ueberzug" ] ;} && [ -z "$SSH_CONNECTION" ] ; then⏎
What's this?

![image](https://github.com/jarun/nnn/assets/79544946/f497afcf-0bb8-4733-b2cc-dec9e41bc0ed)

2023-07-21 03:58 UTC, amalgame21 commented on plugins/preview-tui
> +    elif exists ueberzug && { [ -z "$NNN_PREVIEWIMGPROG" ] || [ "$NNN_PREVIEWIMGPROG" = "ueberzug" ] ;} && [ -z "$SSH_CONNECTION" ] ; then⏎
vim eol character also copied in tmux... sorry about that.

2023-07-21 11:01 UTC, amalgame21 commented
Sorry, seems it is still not working properly in my test. 
The preview can be generated by catimg/viu while ssh, but it cannot generate preview of next items after pressing up/down. Have to toggle preview-tui on and off manually for another preview.

2023-07-21 11:01 UTC, closed without merging