Jump to the next young file
jarun/nnn pull request #1698
Opened 2023-07-22 18:58 UTC by ANtlord

Forward jumping to the next young file is implemented.  The starting position from which the next young file is searched is the current cursor position or the next position if the current position of the cursor points to a young file.  If there no young file has been found, the search starts from the beginning.  It stops at the initial position where the search has started.

2023-07-22 19:21 UTC, N-R-K requested changes

2023-07-22 19:21 UTC, N-R-K commented on src/nnn.c
> +	       "cy  Next young file\n"
Try to keep this aligned with the rest:

```diff
                 "b^G  QuitCD%18Q  Pick/err, quit\n"
-              "cy  Next young file\n"
+                 "cy  Next young file\n"
```

2023-07-22 19:21 UTC, N-R-K commented on src/nnn.c
> +		if (!is_found) {
No need for 2 loops doing the same thing.

```c
	case SEL_YOUNG:
	{
		for (int r = cur;;) {
			if (++r == ndents)
				r = 0;
			if (r == cur)
				break;
			if (pdents[r].flags & FILE_YOUNG) {
				move_cursor(r, 0);
				break;
			}
		}
		break;
	}
```

2023-07-22 19:21 UTC, N-R-K commented on src/nnn.h
> +	{ 'y',            SEL_YOUNG },
`y` seems like a bad key for this. Usually `y` means yank/copy in programs that have vim-like bindings.

2023-07-23 08:37 UTC, ANtlord commented on src/nnn.h
> +	{ 'y',            SEL_YOUNG },
I agree.  Any suggestions?

2023-07-23 14:13 UTC, jarun requested changes

2023-07-23 14:13 UTC, jarun commented on src/nnn.c
> +	      "cy  Next young file\n"
The alignment is still wrong. Please check on github diff view.

2023-07-23 14:13 UTC, jarun commented on src/nnn.h
> +	{ 'y',            SEL_YOUNG },
<kbd>^y</kbd>

Would be handy for users in nav-to-type mode also.

2023-07-24 00:14 UTC, N-R-K reviewed
Looks okay. But please remove this line from the commit message:

> The starting position from which the next young file is searched is the current cursor position or the next position if the current position of the cursor points to a young file.

This is not the case anymore with the new loop. And even in the old loop, this was dead code:

* If initial file was young, it'd get skipped (before the loop).
* If initial file wasn't young, it'd get skipped as well (but this time inside the loop).

So the initial file was always being skipped anyways.

2023-07-24 10:49 UTC, ANtlord commented
Looks like I should correct the patches also.  Is that correct?

2023-07-25 02:29 UTC, N-R-K commented
Weird, looks like the `--merge` option in `check-patches.sh` is what's causing the patches to fail... It works fine otherwise. I'll look into it later.

2023-07-28 15:09 UTC, merged