Clear the entire line and refresh the screen before calling `printent`
jarun/nnn pull request #1711
Opened 2023-08-09 05:39 UTC by quantonganh

Fix #1692

2023-08-09 06:40 UTC, quantonganh commented
Why this failed?

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Cloning git repository
Enumerating objects: 17975, done.
Counting objects: 100% (164/164), done.
Compressing objects: 100% (80/80), done.
Total 17975 (delta 88), reused 135 (delta 81), pack-reused 17811

error fetching: couldn't find remote ref "refs/pull/1711/head"
```

2023-08-09 12:29 UTC, jarun commented
Can you please make the change macOS-specific?

2023-08-09 16:09 UTC, N-R-K commented on src/nnn.c
> +	refresh();
Is the `refresh()` also needed? What happens without it?

2023-08-09 23:20 UTC, quantonganh commented on src/nnn.c
> +	refresh();
The issue still persists if we do not refresh the screen:

<img width="144" alt="Screen Shot 2023-08-10 at 06 15 45" src="https://github.com/jarun/nnn/assets/1568504/f826c8c9-3f45-4cbd-b2b5-768e0665e770">

2023-08-10 21:29 UTC, N-R-K commented on src/nnn.c
> +	refresh();
I was thinking we can avoid unnecessary flushes. But the performance impact here doesn't seem too noticeable (unlike https://github.com/jarun/nnn/pull/1694). So we can probably merge this in as a hack until someone comes up with something better.

Could you please add a comment under the `#ifdef` referencing the original issue url? And also leave a comment stating that there might be a better way to fix it without a flush (so that it's easily visible to anyone else interested in this) @quantonganh

2023-08-10 21:39 UTC, N-R-K commented on src/nnn.c
> +#if defined(ICONS_ENABLED) && defined(__APPLE__)
Instead of duplicating this, you can put this in a single place on top of the file:

```c
#if defined(ICONS_ENABLED) && defined(__APPLE__)
#define macos_icon_hack() do { clrtoeol(); refresh(); } while(0)
#else
#define macos_icon_hack()
#endif
```

Then just use `macos_icon_fix()` in those places.

2023-08-10 23:57 UTC, quantonganh commented on src/nnn.c
> +#if defined(ICONS_ENABLED) && defined(__APPLE__)
I have made the updates as you suggested. Kindly review them.

2023-08-11 00:03 UTC, N-R-K approved these changes

2023-08-15 18:33 UTC, jarun requested changes

2023-08-15 18:33 UTC, jarun commented on src/nnn.c
> +#define macos_icons_hack() do { clrtoeol(); refresh(); } while(0)
Why do we need a do while loop for this?

2023-08-15 19:58 UTC, N-R-K commented on src/nnn.c
> +#define macos_icons_hack() do { clrtoeol(); refresh(); } while(0)
It's a common idiom to avoid surprises when used inside if statements. E.g

```c
if (c)
    MACRO();
```

Will not work without the `do {} while(0)` trick because it'll expand to this:

```c
if (c)
    statement_1;
statement_2;
```

2023-08-16 23:43 UTC, jarun commented on src/nnn.c
> +#define macos_icons_hack() do { clrtoeol(); refresh(); } while(0)
Can't we just have the braces:

#define macos_icons_hack() { clrtoeol(); refresh(); }

2023-08-16 23:59 UTC, N-R-K commented on src/nnn.c
> +#define macos_icons_hack() do { clrtoeol(); refresh(); } while(0)
Then you won't be able to put the semi-colon when invoking the macro. From [c-faq 10.4](https://c-faq.com/cpp/multistmt.html):

> If the macro expanded to a simple compound statement, the final, caller-supplied semicolon would be a syntax error:

```c
if (cond)
	{ stmt1; stmt2; };
else	/* some other code */
```

2023-08-20 12:29 UTC, merged

2023-08-20 12:29 UTC, jarun commented
Thank you!