fzhist plugin: add support for zsh history #1721
jarun/nnn pull request #1722
Opened 2023-09-04 22:48 UTC by umaranis

resolves #1721

2023-09-04 22:53 UTC, N-R-K requested changes

2023-09-04 22:53 UTC, N-R-K commented on plugins/fzhist
> +    hist_file="$HOME/.zsh_history"
`$HISTFILE` should be checked for both zsh and bash: https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html.

(For zsh there's also `$ZDOTDIR` which *might* need to be checked as well for the `-z $HISTFILE && -n $ZDOTDIR` case)

2023-09-05 13:00 UTC, umaranis commented on plugins/fzhist
> +    hist_file="$HOME/.zsh_history"
Pushed a new commit. I am checking if $HISTFILE available, otherwise going to the default location.

2023-09-05 19:32 UTC, jarun requested changes

2023-09-05 19:32 UTC, jarun commented on plugins/fzhist
> +elif [ "$shellname" = "zsh" ]; then
Please fix alignment.

2023-09-06 00:44 UTC, umaranis commented on plugins/fzhist
> +elif [ "$shellname" = "zsh" ]; then
Not sure what's wrong with alignment... looks good to me.

![image](https://github.com/jarun/nnn/assets/2135071/6c2130d0-eb12-4d49-8172-73b55494f345)

2023-09-06 00:57 UTC, N-R-K commented on plugins/fzhist
> +elif [ "$shellname" = "zsh" ]; then
I see that there's some trailing spaces after the `fi`. 

![image](https://github.com/jarun/nnn/assets/79544946/f17ba335-7808-4370-a8f9-6b6ef94236c0)

Though I don't know if that's what jarun is actually talking about or not.

2023-09-07 12:32 UTC, jarun commented
Thank you!
Can you please squash all changes into one?

2023-09-07 12:33 UTC, merged

2023-09-07 12:33 UTC, jarun commented
I took care of it. Thanks!