fix nu quitcd: switched quotes
jarun/nnn pull request #1737
Opened 2023-09-26 11:25 UTC by J-Kappes

- quitcd target directory has been in single quotes since 57882ff
- I updated the nushell snippet to correctly parse it, closing #1736

2023-09-26 11:31 UTC, N-R-K commented
Are you sure this will work on path which contain `'` ?

2023-09-27 12:40 UTC, J-Kappes commented
It doesn't work and I haven't found a fix yet.

2023-09-27 20:41 UTC, N-R-K commented
> It doesn't work and I haven't found a fix yet.

If you can't figure out a way to fix it then leave a FIXME comment explaining the edge case.

2023-09-28 07:44 UTC, J-Kappes commented
This is pretty hacky, so leaving the FIXME might be preferable.

2023-09-28 11:58 UTC, N-R-K requested changes
Small reword.

2023-09-28 11:58 UTC, N-R-K commented on misc/quitcd/quitcd.nu
> +      #FIXME fails on dir names containing single-quotes
```suggestion
      # FIXME: fails if path contains single-quote
```

2023-09-29 09:49 UTC, N-R-K commented on misc/quitcd/quitcd.nu
> +      let newpath = ($rawpath | $"echo ($in)" | /bin/bash -s)
Adding bash dependency on another shell's config doesn't seem like a good idea.

2023-09-30 16:19 UTC, merged

2023-09-30 16:20 UTC, N-R-K commented
Feel free to open another PR if you manage to fix it without requiring `bash` or other non-posix dependency.