+ tmux sixel support for img, gif & vid preview
jarun/nnn pull request #1749
Opened 2023-10-15 06:37 UTC by abhinav3398

adds sixel image, video and gif preview support when tmux is buit with `./configure --enable-sixel`
requirements for preview apart from sixel supported tmux:
- mpv
- img2preview
![2023-10-15T00:31:13,007901883-06:00](https://github.com/jarun/nnn/assets/34549766/b496854a-8fdf-4635-a8fd-f89f889d9e50)
![2023-10-15T00:31:44,573211029-06:00](https://github.com/jarun/nnn/assets/34549766/e15ac3be-bc1d-4c96-b2a1-2f8847239021)

2023-10-15 13:18 UTC, luukvbaal commented
Please check `shellcheck` errors and style/documentation format. Also, which terminals does this target?

2023-10-15 23:01 UTC, abhinav3398 commented
yes you are right. This is targeted towards foot, putty, wezterm, alacritty and other terminals wherein which the user wants to use tmux as multiplexer for nnn window split.

2023-10-18 16:26 UTC, jarun commented
@luukvbaal or @N-R-K please merge when this is ready.

2023-10-18 16:31 UTC, luukvbaal commented
Sure, I haven't had the chance to test this yet but it looks better now.

2023-10-18 16:36 UTC, N-R-K requested changes

2023-10-18 16:36 UTC, N-R-K commented on plugins/preview-tui
> +    vid_start=$(( RANDOM % vid_end ))
What happens if both of these are beyond the file duration? `--start` in mpv accepts a percent, see `man mpv`. I'd use it instead of random stuff. E.g `--start=50% --length=4` to play 4 seconds from the middle.

2023-10-18 16:36 UTC, N-R-K commented on plugins/preview-tui
> +        mpv --no-config --msg-level=all=warn,ao/alsa=error --vo=sixel --profile=sw-fast --loop-file --mute=yes --start="$vid_start"% --end="$vid_end"% "$3" &
I don't get the msg-level flag. Shouldn't we just disable terminal logging entirely? See the `--no-terminal` flag in mpv.

2023-10-18 18:46 UTC, luukvbaal commented on plugins/preview-tui
> +        mpv --no-config --msg-level=all=warn,ao/alsa=error --vo=sixel --profile=sw-fast --loop-file --mute=yes --start="$vid_start"% --end="$vid_end"% "$3" &
mpv recommends the `--really-quiet` flag in the sixel section of their man page.

2023-10-19 18:51 UTC, N-R-K commented on plugins/preview-tui
> +    vid_start=$(( RANDOM % vid_end ))
> Why cant it just start at the beginning?

I presume this is because a lot of videos might have some common opening part. E.g some opening of some series etc.

But thinking about movies and series, starting at 50% might not be a great idea then, since it might end up spoiling the story. Playing 4 seconds starting at 10% probably is a good default.

2023-10-31 01:41 UTC, jarun commented
@N-R-K please merge when ready.

2023-10-31 13:22 UTC, N-R-K reviewed
The code looks okay, but I don't have my mpv built with sixel support so I didn't test.

2023-10-31 13:22 UTC, N-R-K commented on plugins/preview-tui
> +#       - tmux sixel support (should be compiled with `./configure --enable-sixel`)
It should be obvious, but the terminal emulator needs to support sixel too. Should probably be mentioned.

2023-10-31 13:22 UTC, N-R-K commented on plugins/preview-tui
> +            mpv --no-config --really-quiet --vo=sixel --profile=sw-fast --loop-file --mute=yes --start="$vid_start"% --length=4 "$3" &
No point in making `vid_start` a variable when it's used only once. I'd hardcode `--start="10%"`

2023-11-11 16:10 UTC, luukvbaal commented
Sorry for the delay, finally got around to looking into this. Looks alright but I think some more work is needed to implement this properly. 

We need to make sure we don't try to use the sixel backend on terminals that do not support it. I actually havent gotten the sixel backend to mpv work yet on my machine. It prints the raw sixel data when running tmux with sixel support, in a terminal that doesn't support sixel.
In terminals that supposedly do support sixel, I'm getting `[vo] Video output sixel not found!` when using the mpv sixel backend, even though `img2sixel` works fine. Anything else needed to make the mpv sixel backend work @abhinav3398?

#1590 also mentions the kitty backend, I tried adding support for that and that seems to work fine. I'll try to add a commit and merge this PR this weekend if I can get sixel to work...

2023-11-11 16:44 UTC, luukvbaal commented
OK mpv in the arch repo is not built with the sixel backend, installing mpv-full did the trick. What terminal are you using this on @abhinav3398?

I'm currently testing on WezTerm which supports both the sixel and kitty backends. Kitty backend works all right but the sixel backend is horribly slow. Is performance alright for you?

2023-11-11 17:28 UTC, luukvbaal commented
Added a commit to also support the mpv kitty backend. Also try to detect sixel support and better honor the `NNN_PREVIEWIMGPROG` and newly added `NNN_PREVIEWVIDEO` veriables.

2023-11-11 18:05 UTC, abhinav3398 commented
> installing mpv-full did the trick. 

 That's exactly what I used.

> What terminal are you using this on @abhinav3398 

> I'm currently testing on WezTerm which supports both the sixel and kitty backends. Kitty backend works all right but the sixel backend is horribly slow. Is performance alright for you?

I'm using foot. works perfectly fine for me. Mpv used to display videos fine about 2 weeks ago. It just recently started lagging for me. But the lag is fine for prewing purposes. Haven't tried on other terminals yet but I'll try it out on other terminals and try to add a check for sixel support for the terminal after the weekend. 

Thanks for the help @luukvbaal as I'm busy during the weekend.

2023-11-11 18:33 UTC, luukvbaal commented
> It just recently started lagging for me. But the lag is fine for prewing purposes.

Yeah I suppose so. I doubt there is much we can do about performance anyways besides hoping it gets improved upstream ^^ Thanks for kicking off the mpv support, it's cool :) Maybe it's time to consider switching from st again, although I never end up doing so.

2023-11-12 03:32 UTC, N-R-K commented on plugins/preview-tui
> +        mpv --no-config --really-quiet --vo="$NNN_PREVIEWVIDEO" --profile=sw-fast --loop-file --mute=yes "$4" "$3" &
You can use `--ao=null` instead of `--mute=yes`. A null output should skip some unnecessary work compared to using an audio output and muting it.

2023-11-12 03:33 UTC, N-R-K commented
> I doubt there is much we can do about performance anyways besides hoping it gets improved upstream

Doesn't seem like there's any performance issues on sixel output being reported upstream (that's probably because no one uses it). Pinging @mia-0.

2023-11-12 21:45 UTC, mia-0 commented on plugins/preview-tui
> +        mpv --no-config --really-quiet --vo="$NNN_PREVIEWVIDEO" --profile=sw-fast --loop-file --mute=yes "$4" "$3" &
Or just `--no-audio` to also stop mpv from using any audio tracks in the first place.

2023-11-12 22:09 UTC, mia-0 commented
Performance is mostly bottlenecked by libsixel (the quantization step in particular; dithering options may affect it) and the terminal emulator. So there’s not much we can do about it on mpv’s side without replacing libsixel I’m afraid.

2023-11-15 18:13 UTC, N-R-K commented
> I'm fine to merge this now, but I'll test a bit more and wait for reviews one more time.

Assuming this is good to go then?

2023-11-16 14:50 UTC, merged

2023-11-17 12:59 UTC, jarun commented
Thanks guys!