restore sort function pointers when restoring cfg
jarun/nnn pull request #1762
Opened 2023-11-17 22:42 UTC by azuline

closes #1757 

This PR fixes a sorting synchronization issue.

The root cause of the bug in #1757 is that the sorting function `entrycmpfn` is not restored when changing contexts, causing `reverse` (and `version`) to be "global" in that setting them on one context caused them to be set on all contexts.

This PR fixes the bug by setting `entrycmpfn` and `namecmpfn` to the correct pointers whenever `cfg` is set.

---

simulation of state variables in the bugged scenario:

1. starting state
   - `cfgsort[0] = '0'`, `cfg0.reverse = 0`, `entrycmpfn = &entrycmp`
2. set context 1 to `r`
   - `cfgsort[0] = 'r'`, `cfg0.reverse = 1`, `entrycmpfn = &reventrycmp`
3. create context 2. context 2 should also be `r`.
   - `cfgsort[0] = 'r'`, `cfgsort[1] = 'r'`, `cfg0.reverse = 1`, `cfg1.reverse = 1`, `entrycmpfn = &reventrycmp`
4. unset `r` in context 2.
   - `cfgsort[0] = 'r'`, `cfgsort[1] = 'c'`, `cfg0.reverse = 1`, `cfg1.reverse = 0`, `entrycmpfn = &entrycmp`
5. switch back to context 1. context 1 should not be `r`.
   - we hit the "skip ordering on open context carry logic". so we do not change anything
   - `cfgsort[0] = 'r'`, `cfgsort[1] = 'c'`, `cfg0.reverse = 1`, `cfg1.reverse = 0`, `entrycmpfn = &entrycmp`
6. try to set `r` again. no-ops when it should op.
   - `cfgsort[0] = 'r'`, `cfgsort[1] = 'c'`, `cfg0.reverse = 0`, `cfg1.reverse = 0`, `entrycmpfn = &entrycmp`

the "double unset" behavior is because the statusbar uses a function pointer comparison to print `R` and `V`. it does not use `cfg.reverse` or `cfg.version`.

2023-11-17 22:44 UTC, azuline commented on src/nnn.c
> +		namecmpfn = cfg.version ? &xstrverscasecmp : &xstricmp;
i'm not sure if this is necessary, since a new session is spawned with the last session's active directory and sorts (?).

2023-11-18 14:44 UTC, jarun commented on src/nnn.c
> +		namecmpfn = cfg.version ? &xstrverscasecmp : &xstricmp;
It would be great if you can test and confirm whether it works without this change or not.

2023-11-18 14:45 UTC, jarun requested changes

2023-11-18 14:45 UTC, jarun commented on src/nnn.c
> +					entrycmpfn = cfg.reverse ? &reventrycmp : &entrycmp;
Since we are doing it in multiple places, can we have a function?

2023-11-18 15:15 UTC, azuline commented on src/nnn.c
> +		namecmpfn = cfg.version ? &xstrverscasecmp : &xstricmp;
the behavior i observed should be fixed without this change, but i am not sure if there is a scenario where a new session results in an inconsistent state between cfg and the function pointers. i didnt fully model the session mechanics when debugging this.

it shouldn't cause any problems, since this logic is a NoOp if everything is in sync, but we can remove this change and wait to see if any bugged behavior is observed.

2023-11-18 15:55 UTC, jarun commented on src/nnn.c
> +		namecmpfn = cfg.version ? &xstrverscasecmp : &xstricmp;
OK. In that case please have have the code (call tot he funciton) commented and add sufficient documentation.

2023-11-18 21:32 UTC, azuline commented on src/nnn.c
> +		namecmpfn = cfg.version ? &xstrverscasecmp : &xstricmp;
the function i factored out does more than set the function pointers, it encapsulates the switching of the `cfg` global, as whenever `cfg` is switched, the function pointers should be synchronized to match the new `cfg`. i left a comment above these two lines expressing intent.

2023-11-18 21:32 UTC, azuline commented on src/nnn.c
> +					entrycmpfn = cfg.reverse ? &reventrycmp : &entrycmp;
added a function to encapsulate setting `cfg =`, since we should synchronize global function pointers whenever we set `cfg =`

2023-11-19 08:09 UTC, merged

2023-11-19 08:09 UTC, jarun commented
Thank you!