When handling bookmark, use readlink, not realpath
jarun/nnn pull request #1773
Opened 2023-11-22 06:04 UTC by 7ocb

This is to cd to path as it pointed by symlink, not to it's real path. Bookmarked directory may itself contain symlinks in path, which should be respected.

For example: if directory is physically in `/mnt/storage/some` and it's symlinked to `~/some` and directory `~/some/dir` added to bookmarks, it's reasonable to expect that when following bookmark directory will be changed to `~/some/dir` (as in bookmark's link) not to `/mnt/storage/some/dir` (as dir real path).

It's reasonable to expect this behavior because this follows the `cd` behavior (both shell `cd` and `nnn` changing directory) when changing directory into symlink.

Also, with behavior as in this PR user can have both bookmarks to "short" path (i.e. `~/some/dir` in example above) and long path (i.e. `/mnt/storage/some/dir`) - which path is actually bookmarked, that path will be followed. Original behavior disallows using bookmarks to go to "short" path.

2023-11-22 16:54 UTC, N-R-K requested changes

2023-11-22 16:54 UTC, N-R-K commented on src/nnn.c
> +static char *bmtarget(const char *filepath, char *cwd, char *buf) {
`{` goes to the next line.

2023-11-22 16:54 UTC, N-R-K commented on src/nnn.c
> +   char target[PATH_MAX + 1];
nnn uses TABs for indent.

2023-11-22 16:54 UTC, N-R-K commented on src/nnn.c
> +   const int n = readlink(filepath, target, PATH_MAX);
Drop the `const`, it's useless noise.

2023-11-22 16:54 UTC, N-R-K commented on src/nnn.c
> +   target[n] = 0;
Use `'\0'`.

And `readlink` isn't guaranteed to succeed and can return -1. That needs to be checked properly.

2023-11-22 16:54 UTC, N-R-K commented on src/nnn.c
> +			                        bmtarget(pent->name, path, newpath) &&
The function name says `bmtarget` but this will affect all navigation logic. Not just bookmarks.

2023-11-22 16:57 UTC, 7ocb commented on src/nnn.c
> +			                        bmtarget(pent->name, path, newpath) &&
@N-R-K in this case only bookmarks as far as I can see (as per `g_state.selbm` check). Am I missing something?

2023-11-22 17:02 UTC, 7ocb commented on src/nnn.c
> +static char *bmtarget(const char *filepath, char *cwd, char *buf) {
Done.

2023-11-22 17:02 UTC, 7ocb commented on src/nnn.c
> +   char target[PATH_MAX + 1];
Done.

2023-11-22 17:02 UTC, 7ocb commented on src/nnn.c
> +   const int n = readlink(filepath, target, PATH_MAX);
Done.

2023-11-22 17:03 UTC, 7ocb commented on src/nnn.c
> +   target[n] = 0;
Done.

2023-11-22 17:10 UTC, KlzXS requested changes

2023-11-22 17:10 UTC, KlzXS commented on src/nnn.c
> +	} else {
Don't use else after return as per CI.

2023-11-22 17:17 UTC, N-R-K commented on src/nnn.c
> +			                        bmtarget(pent->name, path, newpath) &&
You're right. I didn't notice the `selbm` check.

2023-11-22 17:20 UTC, 7ocb commented on src/nnn.c
> +	} else {
Done.

2023-11-22 17:23 UTC, N-R-K reviewed
Seems to work fine. A couple style nits.

2023-11-22 17:23 UTC, N-R-K commented on src/nnn.c
> +
This is a really small function. There's no real need for all these blank lines. I'd drop them all.

2023-11-22 17:23 UTC, N-R-K commented on src/nnn.c
> +	int n = readlink(filepath, target, PATH_MAX);
Forgot to mention this earlier, but it's better to use `ssize_t` since that's what `readlink` actually returns (even though it doesn't really matter here).

2023-11-22 17:25 UTC, N-R-K commented on src/nnn.c
> +	} else {
TBH, I was never a fan of that warning. To me it seems perfectly fine to have `else` after `return` if all the branches end up returning.

(To be clear, the above is just a small rant, not a suggestion to change it back. Keep the PR as it currently is to keep the CI happy).

2023-11-22 17:42 UTC, 7ocb commented on src/nnn.c
> +
Done.

2023-11-22 17:42 UTC, 7ocb commented on src/nnn.c
> +	int n = readlink(filepath, target, PATH_MAX);
Done.

2023-11-22 17:42 UTC, N-R-K approved these changes

2023-11-25 13:04 UTC, merged

2023-11-25 13:04 UTC, jarun commented
Thank guys!