show linenumber when in SEL_JUMP
jarun/nnn pull request #1804
Opened 2024-01-27 10:37 UTC by Darukutsu

Related [discussion](https://github.com/jarun/nnn/discussions/1708).
I reworked my previous answer a bit. I think this should be part of nnn, since it's (IMO) hard to manually count down. Or at least include as native patch.

We could also show relative/absolute linenumber always(with minor tweaks), but that doesn't seem to be useful in any way yet.

![linenumber](https://github.com/jarun/nnn/assets/54768193/91173f6f-efa3-404e-891d-985f28d199bd)

2024-02-02 15:44 UTC, jarun commented
Can you test this will very long filenames?

Also, what is the keybind to show the relative numbers?

2024-02-02 15:47 UTC, jarun requested changes

2024-02-02 15:47 UTC, jarun commented on src/nnn.c
> +        int ncount;
This increases memory usage per file. Why do we need to store this and not calculate on the fly?

2024-02-03 09:34 UTC, N-R-K commented on src/nnn.c
> +        int ncount;
Simpler approach in https://github.com/jarun/nnn/pull/1808 which doesn't require storing counts.

2024-02-03 14:31 UTC, closed without merging

2024-02-03 15:07 UTC, jarun commented on src/nnn.c
> +        int ncount;
Already merged.