add zip plugin
jarun/nnn pull request #1805
Opened 2024-01-27 10:43 UTC by Darukutsu

I don't like that built-in zip includes absolute paths by default. I also miss zstd as option. This could do probably any 
compression. You can also password protect archive.

Related issues [#1105](https://github.com/jarun/nnn/issues/1105).

2024-02-02 15:49 UTC, jarun requested changes

2024-02-02 15:49 UTC, jarun commented on plugins/zip
> +#!/usr/bin/env sh
Please add the details in the plugin readme table.

2024-02-02 15:49 UTC, jarun commented on plugins/zip
> +    "7"|"zstd") alg=zstd
What happens when the user chooses a compression which is not available in the system?

2024-02-02 16:30 UTC, N-R-K requested changes

2024-02-02 16:30 UTC, N-R-K commented on plugins/zip
> +        compress_tar "$abspath"
You can generally just pipe the output of `tar` over to the compressor program without needing to create any intermediate file.

2024-02-02 16:30 UTC, N-R-K commented on plugins/zip
> +working_dir=$(pwd)
Use either `$PWD` or `$2` (see https://github.com/jarun/nnn/tree/master/plugins#access-level-of-plugins)

2024-02-02 16:30 UTC, N-R-K commented on plugins/zip
> +    find . -maxdepth 1 -type f \( -name "$1.zip" -o -name "$1.tar*" \) \! -name "*.gpg" -exec gpg -c "{}" \; -exec rm "{}" \;
Why not just pass the full filename instead of doing this. Also `gpg` might accept `stdin` as well. So you might be able to just pipe it in and avoid the intermediate file once again.

2024-02-02 16:30 UTC, N-R-K commented on plugins/zip
> +      ppath=$(echo "$abspath" | sed 's#\(/.*/\).*#\1#')
It's not generally safe to echo a filepath since it might contain special chars. Use `printf` instead.

Also what exactly is this sed doing?

2024-02-02 17:21 UTC, KlzXS requested changes
I only marked a single occurrence of each issue. Please change all of them.

2024-02-02 17:21 UTC, KlzXS commented on plugins/zip
> +    for abspath in $(sed 's#\x0# #g' < "$selection"); do
All other plugins use `tr '\0' '\n'` to get rid of '\0'. Let's keep it consistent.

2024-02-02 17:21 UTC, KlzXS commented on plugins/zip
> +      ppath=$(echo "$abspath" | sed 's#\(/.*/\).*#\1#')
Use `dirname` to get the containing directory of a file. Keep in mind that it doesn't include a trailing `/` if that matters to you.

2024-02-02 17:21 UTC, KlzXS commented on plugins/zip
> +      file=$(echo "$abspath" | sed 's#/.*/\(.*\)#\1#')
Use `basename` to get the filename.

2024-02-02 17:21 UTC, KlzXS commented on plugins/zip
> +  if test "$individual"; then
`[` is an alias for `test`. Keep it consistent and use `if [ "$individual" ]; then`.

2024-02-02 17:23 UTC, KlzXS commented on plugins/zip
> +      ppath=$(echo "$abspath" | sed 's#\(/.*/\).*#\1#')
My comments below address this in entirety.

2024-02-02 18:06 UTC, Darukutsu commented on plugins/zip
> +      ppath=$(echo "$abspath" | sed 's#\(/.*/\).*#\1#')
You can also zip files individualy with absolute path or not. Let's say for some reason you have 2 different directories which you want compress separately or maybe 2 big files and you want to have A.zip B.zip. **I needed to pass this in loop instead of `xargs` for comment mentioned above and when you don't want absolute path you have to be in that path... `zip -j` is not very good, breaks structure, when you want compress dirs within dirs.** Because we want selection separated `sed` removes `\0` character since `read -0` is not POSIX. Anyway changed it for `tr`. I didn't want to repeat although I have. Because of highlighted text I didn't used `tar -I` and piping gpg. Don't know any better

2024-02-02 18:09 UTC, Darukutsu commented on plugins/zip
> +  if test "$individual"; then
Yeah I know. For some reason shellcheck recommended this but not now... weird :D.

2024-02-02 18:12 UTC, KlzXS requested changes

2024-02-02 18:12 UTC, KlzXS commented on plugins/zip
> +      rm "$1.tar"
CI is flagging this. Use `"$alg"`.

2024-02-02 18:16 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
There are more variables should I put `""` for all of them?
Also is it ok to amend commit? Don't know what's proper way when fixing issues like that.

2024-02-02 18:35 UTC, KlzXS commented on plugins/zip
> +      rm "$1.tar"
Please do, I missed those. It'll keep complaining until all of them are quoted. In general, if it has `$` it goes between `""`.

You can add more commits, amend, force push, whatever you like. PRs usually just get squashed anyway.

2024-02-02 18:42 UTC, KlzXS commented on plugins/zip
> +      rm "$1.tar"
You know how every rule has an exception? This is it for the quoting rule: `$(tr '\0' '\n' < "$selection")` shouldn't be quoted. We want that to split at whitespace.

2024-02-02 18:45 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
what if filename has white space?

2024-02-02 18:46 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
anyway `selection` should only contain selected file nothing else right?

2024-02-02 18:47 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
Ah ok... for loop will break

2024-02-02 18:49 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
Ah, for loop isn't great for this since it will break if filename contains `\n` or white space.

2024-02-02 18:53 UTC, Darukutsu commented on plugins/zip
> +      rm "$1.tar"
well I will have to come with other solution or maybe I'm not right and already talking bullshits :D.

2024-02-02 19:31 UTC, N-R-K commented on plugins/zip
> +  which "$alg" >/dev/null 2>&1 || (printf "'%s' not installed, cancelling..." "$alg" && exit 1)
0. Use `command -v` instead of `which`. It should be more portable.
0. Switch from `(..)` to `{..}` to group commands.
0. It should exit regardless of whether `printf` failed or not. So change `&&` to `;`
0. printf doesn't add newline unlike echo. Use `printf "...\n" ...` instead. Also I think this should go to standard error instead. So add a `>&2` redirect.

2024-02-02 19:39 UTC, N-R-K commented on plugins/zip
> +      rm "$1.tar"
Just do it with `xargs -0` and add a `alg_to_extension()` function or something to add the extension.

2024-02-02 20:30 UTC, KlzXS commented on plugins/zip
> +      rm "$1.tar"
Yeah, it would be best if you can get it to work with `xargs -0`. Just keep in mind that you can't run functions inside `xargs`. That's a bash extension.

2024-02-04 10:51 UTC, Darukutsu commented
Well boys, will this work in other shells? I tried to preserve original behavior, but it's kinda weird. I mean it works for me :D. Maybe I should include some tests.

I could possibly rewrite it in way in which I specify file extensions in `choose_alg()` and then use native `tar --use-compress-program=COMMAND`.
Or let user manually everytime specify extension in input like `myarchive.tar.gz`.

It works now in a way that users need to specify only name without extensions.

2024-02-04 20:35 UTC, N-R-K requested changes

2024-02-04 20:35 UTC, N-R-K commented on plugins/zip
> +      find . -maxdepth 1 -type f \( -name "$filename.zip" -o -name "$filename.tar*" \) \! -name "*.gpg" -exec gpg -c "{}" \; -exec rm "{}" \;
Won't this just end up encrypting unrelated files if it happened to start with the same `$filename`?

2024-02-04 20:51 UTC, Darukutsu commented on plugins/zip
> +      find . -maxdepth 1 -type f \( -name "$filename.zip" -o -name "$filename.tar*" \) \! -name "*.gpg" -exec gpg -c "{}" \; -exec rm "{}" \;
oh yeah it will. I forgot to add encryption to individual selection so it wasn't encrypting at all. My bad.

2024-02-09 17:47 UTC, jarun commented
@N-R-K and @KlzXS is this ready to merge?

2024-02-09 18:18 UTC, KlzXS commented
@jarun There are still some outstanding comments from me that should be addressed. CI is currently failing; I'd say we probably just silence it in this case. I myself haven't tried the plugin out; will probably do that at some point.

When those issues are address and if we confirm that it does work, we'll be ready to merge. Personally, I'd like to see the script simplified a bit, there's a lot of commands nested inside of `xargs ... sh -c '' ` constructs, but I haven't had time to look into it and see if something can be done about that.

2024-02-09 21:20 UTC, Darukutsu commented
There are some issues. I finally made somewhat testing script, so now it will be easier to fix them. I will provide script with fix tomorrow.

2024-02-10 14:13 UTC, Darukutsu commented
When testing using script comment line `229`. You still need to make sure output is ok. I tested using this.
```
  # Clear selection
  printf "-" > "$NNN_PIPE"
```
<details>
  <summary>test script</summary>
  
  ```
  #!/usr/bin/env sh

g=$(tput setaf 2)
n=$(tput sgr0)

command=~/.config/nnn/plugins/zip

#tar
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rY\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 1${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rY\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 2${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rY\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 3${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rY\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 4${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rN\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 5${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rN\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 6${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rN\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 7${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "tar\rN\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}tar passed 8${n}"

#tar.gz
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rY\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 1${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rY\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 2${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rY\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 3${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rY\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 4${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rN\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 5${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rN\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 6${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rN\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 7${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "gzip\r\rN\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}gzip passed 8${n}"

#zip
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rY\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 1${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rY\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 2${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rY\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 3${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rY\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 4${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rN\rY\rN\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 5${n}" ; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rN\rY\rY\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 6${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rN\rN\rY\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 7${n}" ; read; read
(sleep 1 ; xdotool type --delay 100 $(printf "zip\r\rN\rN\rN\r\r"))& $command && printf "\n%s\n\n" "${g}zip passed 8${n}"
```
<\details>

2024-02-14 15:10 UTC, Darukutsu commented
Should I fix anything else?

2024-02-14 23:42 UTC, N-R-K commented
Did some basic tests (didn't test encryption). Couple remarks:

0. Why does compressing a single file produce a tar? I'd expect it to be compressed directly without the tar archive.
0. Should we really hardcode 5 as default compression level? Each tool comes with it's own default and IMO we should let the tool decide for itself what the default should be instead of hardcoding 5.

2024-02-15 00:02 UTC, N-R-K commented
Also, I'm really not a fan of this type of thing that's going on: `-o -name "$filename.tar*"`. All this would go away if we just used stdin/out instead of making intermediate files. Here's an example of how to do stdin/out pipe to do `tar.gz` on selection:

```console
$ xargs -0 tar -cvf - < "$selection" | gzip -c -9 > archive.tar.gz
```

Or if you want to remove the $pwd from the paths:

```console
sed -z "s|^$PWD/||g" < "$selection" | xargs -0 tar -cvf - | zstd -c -19 > archive.tar.zst
```

2024-02-15 14:09 UTC, Darukutsu commented
> ```
> sed -z "s|^$PWD/||g" < "$selection" | xargs -0 tar -cvf - | zstd -c -19 > archive.tar.zst
> ```

does this work because after trying it i got something like this which is not what we want.

```
# run under .config/nnn
" tar.vim version v32
" Browsing tarfile /home/daru/.config/nnn/archive.tar.zst
" Select a file with cursor and press ENTER

plugins/x2sel
plugins/xdgdefault
plugins/zfs-snapdir
sessions/
sessions/@                              # my implementation does this
home/daru/.config/pgcli/                #pgcli/
home/daru/.config/pgcli/config          #pgcli/config
home/daru/.config/pgcli/log             #pgcli/log
```
also doing this piping to gpg and thus creating another `elseif` entry isn't very something... or maybe gpg should be separate script then, or don't include it at all.

> Should we really hardcode 5 as default compression level? Each tool comes with it's own default and IMO we should let the tool decide for itself what the default should be instead of hardcoding 5.

As a workaround to prevent including more if-statements we could do `"default_compression=-verbose` since expanding it will make `--verbose` and it's unharmful behavior and should be same across all compression algorithms.

2024-03-24 21:28 UTC, jarun commented
@Darukutsu CI is failing, can you check?

Also, this is open for a while, if this doesn't move, I'll close it.

2024-03-24 22:00 UTC, Darukutsu commented
```
 ^-- SC2016 (info): Expressions don't expand in single quotes, use double quotes for that.
 ```
  just like @KlzXS said
 >CI is currently failing; I'd say we probably just silence it in this case.
 
 I couldn't come up with better solution. It's pretty much working for me(haven't spotted any issue, when using/[testing](https://github.com/jarun/nnn/pull/1805#issuecomment-1937017504)), but that's not what means "production ready". Feel free to close. In either case thank you guys for perfectioning this script.

2024-03-24 22:27 UTC, KlzXS commented
The main issue I have with the script is that it's a nightmare to maintain with all those nested substitutions, extracting and constructing names and a lot of `if`s that run in parallel across multiple functions.  Unfortunately, I don't have a solution to those issues.

If you're fine with such code merge it in.

@Darukutsu Thank you for giving it a shot. Personally, I'd have written this in something like Python as bash isn't really great at dealing with complex logic. You get ugly things like that `find` for removing files after encrypting them. Ideally you should know the name of the temporary file you just wrote to, but alas, you don't.

We don't really have examples of non-shell scripts, but a plugin can be any old executable file, we just happen to mostly do it in `sh` as that's available everywhere.

2024-03-29 20:54 UTC, KlzXS commented
I think it's best that we close this for now. I've added it as a task in the Tracker. Someone can give it a shot in the future.

My suggestions for those attempting this task:
- Don't use POSIX `sh`. This is a complicated task and it's very limited in its functionality. At the very least use `bash` so that you can execute a function inside `xargs`. That should simplify the script significantly and make it easier to modify and maintain. Functions are your friends.
- You can try another scripting language but try to use something widespread and popular. I've mentioned Python above.
- If you try to support encryption, see if you can support both symmetric and asymmetric `gpg`. See `gpge` and `gpgd` for an example.
- If using `gpg`, see if you can remove the intermediate files directly, without having to resort to `find`ing them after `gpg`'s done its job.
- In general, try to make the script as performant as possible. It should spend most of its runtime doing useful work and as little as possible executing helper functions.
- `nnn`'s core archiving solution has support for `atool`. See if you can use that to simplify the task.
- Consider if you want to support actions for extracting (Extract Here, Extract to..., Extract to `archive_name/`) available in many archiving solutions. Splitting that off into a separate plugin would be a good choice.

Now that I've written this it sounds more like a whole separate tool instead of a "simple" plugin. Make of that what you will.

All in all, this is functionality that would be nice to have in `nnn` in some form. Thanks to @Darukutsu for bringing it up.

2024-03-29 20:54 UTC, closed without merging