Add option to `rm -rf` irrespective of trash
jarun/nnn pull request #1811
Opened 2024-02-03 21:58 UTC by 62832

Heya. I was slightly annoyed by the fact that using `NNN_TRASH` completely disabled the ability to `rm -rf` within nnn, so I wanted to add a separate option for `^X` that would just use `rm -rf` regardless of the trash backend being used.

Hope this is alright.

2024-02-04 19:00 UTC, KlzXS requested changes
I think this is a fine addition. It always seemed redundant to me that there were two keybinds for the exact same thing bound to the exact same key.

Though it is a bit dangerous for the people who've grown accustomed to using `^X` for deleting files with trash enabled. The last *change* (there have been additions since, but those wouldn't affect existing workflows) in keybinds was in April 2022 and that was much less impactful than this would be.

2024-02-04 19:06 UTC, jarun commented on src/nnn.h
> +	{ CONTROL('X'),   SEL_RMONLY },
I don't understand what is "only". Not here, not in the help.

2024-02-04 19:24 UTC, 62832 commented on src/nnn.c
> -	                   + xstrlen(selpath)) * sizeof(char));
I believe I *am* using tabs there, it's just that those were previously spaces. I use an alias to tab-indent anything in this case since I typically use 4 spaces to indent in my own projects.

2024-02-04 19:25 UTC, 62832 commented on src/nnn.h
> +	{ CONTROL('X'),   SEL_RMONLY },
In this case "only" is supposed to mean "only use `rm -rf`, ignoring `NNN_TRASH`". I can see why it would be confusing, however.

2024-02-04 19:30 UTC, 62832 commented on src/nnn.c
> +static char confirm_force(bool selection, enum action rmopt)
By that point, `sel` can only be either `SEL_RM` or `SEL_RMONLY`, so I assumed this would be okay.

2024-02-04 19:42 UTC, KlzXS commented on src/nnn.c
> -	                   + xstrlen(selpath)) * sizeof(char));
Oh, you're right. I swapped the colors around. In any case, revert it back to what it was. That's how it's done everywhere else.

2024-02-04 19:47 UTC, KlzXS commented on src/nnn.c
> +static char confirm_force(bool selection, enum action rmopt)
I was expecting something along the lines of `bool use_trash`. It's kind of weird passing down the action to this mundane function this deep in the call stack, after we've pretty much used it up for its intended purpose.

It's just personal preference, we can keep it like this. It's just that I don't remember something like this ever coming up, so it got my attention.

2024-02-04 19:52 UTC, 62832 commented on src/nnn.c
> +static char confirm_force(bool selection, enum action rmopt)
Yeah, that makes more sense, actually. I'll go ahead and change it as such.

2024-02-04 20:01 UTC, KlzXS commented on src/nnn.h
> +	{ CONTROL('X'),   SEL_RMONLY },
Maybe `SEL_RMNOTRASH`, implying that `SEL_RM` does or can use trash like it was up until now? I've been trying to come up with something, but everything is either somewhat vague or too verbose.

2024-02-04 20:02 UTC, N-R-K commented
You can accomplish the same thing with a simple plugin. Bind it to `x` and then call it with <kbd>alt+x</kbd>. Don't think we need to have this builtin, and I *especially* don't think we should bind it to `^x` and change existing bind.

2024-02-04 20:18 UTC, KlzXS commented
On the other hand, I think this is a useful bultin. It's a bit odd that you can't specify to permanently delete a file if you configure trash. Maybe even going as far as to say that most file managers have such a feature. So, delegating it to a one-liner plugin seems a bit off.

I do agree about the keybind tough. I don't expect it to affect anybody realistically, but who knows. This would have been perfect back before keybinds were stabilized, but apparently no one thought of that at the time.

2024-02-04 20:23 UTC, KlzXS commented
...unless we do something like with batch rename where we call a plugin if it's found and otherwise do the builtin thing.

It's a bit convoluted, but would at the same time keep the existing behavior for most users while allowing something extra for those willing to opt in. Also, there was some talk recently about supporting more trash managers. I didn't follow that through, but I imagine giving them a script they can edit would allow them better compatibility than just building all those options directly in.

What do you think?

2024-02-04 20:31 UTC, N-R-K commented
> do something like with batch rename where we call a plugin if it's found and otherwise do the builtin thing.

That might be a good idea. Would allow people to use other trash utilities or add special logic to skip trash and rm directly and what not.

2024-02-04 20:52 UTC, KlzXS commented
@62832 the plugin in question is `.nmv` and the corresponding symbol in code is `UTIL_NMV`. In case you want to take a look at that.

2024-02-07 01:11 UTC, jarun requested changes

2024-02-07 01:11 UTC, jarun commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
Does ^X result in `rm` or `rm -rf`?

2024-02-07 01:16 UTC, jarun commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
Also, when the user presses `^X` does the next prompt explicitly state that `rm` is going to be invoked?

2024-02-07 10:26 UTC, 62832 commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
Yes to both of those.

2024-02-07 11:30 UTC, 62832 commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
`^X` results in `rm -rf` as it would if there was no trash backend being used. The prompt does also explicitly state that `rm -rf` will be invoked.

2024-02-07 11:30 UTC, 62832 commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
The `(rm-only)` clause could probably be amended to just say `Delete (rm -rf)`.

2024-02-07 13:24 UTC, jarun commented on src/nnn.c
> +		 "b^X  Delete (rm-only)%06Esc  Send to FIFO\n"
Yes, that should be the correct help documentation.

2024-02-07 13:30 UTC, jarun commented
@KlzXS there is one problem. For users who use the `type-to-nav` mode, `^X` is the natural way to trash. In my case, I still use `rm -rf` but someone used to trash files would inadvertently remove the files.

So I am inclined to agree with @N-R-K on this aspect.

However, I think we can have a best of both the worlds. We can add a program option `-X` (capital-X) which would force `rm -rf` with `^X` when a different trash is configured.

What do you think?

@62832 hold on till we conclude this discussion.

2024-02-07 17:39 UTC, N-R-K requested changes

2024-02-07 17:39 UTC, N-R-K commented on src/nnn.c
> +	return (g_state.trash && use_trash ? '\0' : 'i'); /* interactive for rm */
I don't like how you need to check the same thing everywhere in multiple places. Just make the caller check for `g_state.trash` and make these functions only use the `use_trash` argument.

2024-02-07 17:39 UTC, N-R-K commented on src/nnn.h
> +	{ CONTROL('X'),   SEL_RMNOTRASH },
Capital x is free. You can use that instead of changing `ctrl+x`.

2024-02-07 17:56 UTC, jarun commented on src/nnn.h
> +	{ CONTROL('X'),   SEL_RMNOTRASH },
@N-R-K yes, that is also a good idea. That way we don't need to change the behaviour of the current keybinds.

2024-02-07 18:02 UTC, jarun commented
@62832 I am fine with a new keybind `X` for `rm -rf` always.

Also, please squash all the commits into one for easy maintenance.

2024-02-08 14:12 UTC, 62832 commented
Should be done now, having addressed @N-R-K's concerns and switched to using SHIFT+X as the bind for `rm -rf`. Ready when you are.

2024-02-08 16:30 UTC, jarun requested changes

2024-02-08 16:30 UTC, jarun commented on src/nnn.h
> +	{ 'X',            SEL_RMNOTRASH },
Can you please rename the above 2 to SEL_TRASH and this one to SEL_RM_FIXED?

2024-02-08 17:25 UTC, N-R-K commented on src/nnn.h
> +	{ 'X',            SEL_RMNOTRASH },
`SEL_RM_ONLY` sounds better to me. And for the existing one, I think `SEL_RM` is fine. But `SEL_TRASH` also works if you prefer that.

2024-02-09 02:22 UTC, N-R-K approved these changes
Small documentation nit. Code seems ok to me.

2024-02-09 02:22 UTC, N-R-K commented on src/nnn.c
>  	       "9x ^X  Delete%18S  Listed sel size\n"
Maybe this should be changed to "Delete or trash"? A bit weird seeing both the bindings with "Delete" description.

2024-02-09 06:37 UTC, KlzXS approved these changes
If we are happy with the new names of the actions and the description in the help this should be good to go.

Also a reminder that we should update the wiki after this is merged.

2024-02-09 15:20 UTC, jarun commented
We are good! I'll take care of the Wiki update. Thanks guys!

2024-02-09 15:23 UTC, 62832 commented
Is that failing `ubuntu-patches` test going to be a problem?

2024-02-09 15:23 UTC, jarun commented
./patches/check-patches.sh fails in CI. @62832 please have a look.

```
./patches/check-patches.sh
7
O_COLEMAK=1 O_GITSTATUS=0 O_NAMEFIRST=0 O_RESTOREPREVIEW=0 [FAILED]
8
O_COLEMAK=0 O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=0 [SUCCESS]
9
O_COLEMAK=1 O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=0 [FAILED]
10
O_COLEMAK=0 O_GITSTATUS=0 O_NAMEFIRST=1 O_RESTOREPREVIEW=0 [SUCCESS]
11
O_COLEMAK=1 O_GITSTATUS=0 O_NAMEFIRST=1 O_RESTOREPREVIEW=0 [FAILED]
12
O_COLEMAK=0 O_GITSTATUS=1 O_NAMEFIRST=1 O_RESTOREPREVIEW=0 [SUCCESS]
13
O_COLEMAK=1 O_GITSTATUS=1 O_NAMEFIRST=1 O_RESTOREPREVIEW=0 [FAILED]
14
O_COLEMAK=0 O_GITSTATUS=0 O_NAMEFIRST=0 O_RESTOREPREVIEW=1 [SUCCESS]
15
O_COLEMAK=1 O_GITSTATUS=0 O_NAMEFIRST=0 O_RESTOREPREVIEW=1 [FAILED]
16
O_COLEMAK=0 O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=1 [SUCCESS]
17
O_COLEMAK=1 O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=1 [FAILED]
18
O_COLEMAK=0 O_GITSTATUS=0 O_NAMEFIRST=1 O_RESTOREPREVIEW=1 [SUCCESS]
19
O_COLEMAK=1 O_GITSTATUS=0 O_NAMEFIRST=1 O_RESTOREPREVIEW=1 [FAILED]
20
O_COLEMAK=0 O_GITSTATUS=1 O_NAMEFIRST=1 O_RESTOREPREVIEW=1 [SUCCESS]
21
O_COLEMAK=1 O_GITSTATUS=1 O_NAMEFIRST=1 O_RESTOREPREVIEW=1 [FAILED]
22
make: *** [Makefile:326: checkpatches] Error 1
23
Error: Process completed with exit code 2.
```

2024-02-09 15:37 UTC, 62832 commented
@jarun Should be sorted now, conflicts have been resolved with the Colemak patch.

2024-02-09 15:45 UTC, jarun commented
Re-ran CI.

2024-02-09 15:45 UTC, jarun approved these changes

2024-02-09 15:48 UTC, merged

2024-02-09 15:48 UTC, jarun commented
Thank you!