quitcd: fix range limits for new nushell version
jarun/nnn pull request #1890
Opened 2024-05-27 02:07 UTC by BeyondMagic

[Last version of nushell](https://www.nushell.sh/blog/2024-04-30-nushell_0_93_0.html) changed the way ranges work, so the command `str substring 4..-1` isn't behaving the way it was anymore.

2024-05-27 02:15 UTC, N-R-K commented
Won't this break for people who have older nushell versions or is the new patch backwards compatible? If it's not backwards compatible, then please document the minimum required version in the comment at the top of the file.

2024-05-27 02:19 UTC, N-R-K requested changes

2024-05-27 02:19 UTC, N-R-K commented on misc/quitcd/quitcd.nu
> +			| str trim --char "'"
What happens if a path ends in `'`? Won't strim end up removing the `'` as well? https://www.nushell.sh/commands/docs/str_trim.html

I think you should only remove the last char, not "trim" every `'`.

2024-05-27 14:05 UTC, BeyondMagic commented on misc/quitcd/quitcd.nu
> +			| str trim --char "'"
True, I hoped NNN'd send a trailing slash at the end of the path before the single quotes; but that's no the case.

2024-05-27 14:07 UTC, BeyondMagic commented
> Won't this break for people who have older nushell versions or is the new patch backwards compatible?

No; not in the way it is coded right now.

2024-05-27 14:17 UTC, BeyondMagic commented
Resolved with backwards compatibility and fixed trimming issue.

2024-06-03 21:25 UTC, merged

2024-06-03 21:26 UTC, jarun commented
Thank you!