Disable large file support on old glibc
jarun/nnn pull request #1910
Opened 2024-07-15 22:02 UTC by sjmulder

On glibc <2.23 fts.h doesn't support the feature:

https://sourceware.org/bugzilla/show_bug.cgi?id=11460

```
In file included from src/nnn.c:78:0:
/usr/include/fts.h:41:3: error: #error "<fts.h> cannot be used with -D_FILE_OFFSET_BITS==64"
 # error "<fts.h> cannot be used with -D_FILE_OFFSET_BITS==64"
```

2024-07-16 12:02 UTC, N-R-K requested changes
This was discussed here: https://github.com/jarun/nnn/issues/1678#issuecomment-1615220416

I don't think we want to keep adding workarounds for buggy libc behavior which have been fixed for almost a decade now.

2024-07-16 12:02 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
I don't think this is a public header for us to be including.

2024-07-16 13:20 UTC, sjmulder commented
It's your call to make - the advantage is that nnn can still run older targets such as CentOS 7, at the cost of a bit of preprocessor crud. Functionally there's no degradation on platforms where nnn already works.

2024-07-16 13:22 UTC, sjmulder commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
I wasn't aware of this but indeed feature_test_macros(7) documents this. I can shuffle includes around a bit to avoid this if you're not against this PR a priori.

2024-07-16 13:50 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
It's upto @jarun to make the call. I personally don't think trying to work around a decade old glibc bug is worth it, especially since glibc maintainers now recommend defining it unconditionally.

2024-07-16 14:26 UTC, sjmulder commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
I understand the perspective but the one extra ifdef keeps nnn working on legacy platforms where system utilities like this remain useful. Note that RHEL 7 is still under extended lifecycle support. I'll keep it working in pkgsrc while I can but it would be nice if vanilla nnn kept working too.

2024-07-16 16:17 UTC, jarun requested changes

2024-07-16 16:17 UTC, jarun commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
I am fine with this. We should try to keep `nnn` working on older systems.

2024-07-16 16:34 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
> I am fine with this. We should try to keep nnn working on older systems.

In that case, @sjmulder please try to see if you can do this without including private/non-posix libc headers.

2024-07-16 16:41 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
> then unconditionally include one of the base headers like stddef.h to get the effects of features.h

This sounds okay.

> That would assume it's okay to delay _FILE_OFFSET_BITS until after stddef.h

Unfortunately, I don't think this will work. From the `feature_test_macros` manpage:

"NOTE: In order to be effective, a feature test macro must be  defined  before  including  any header files"

2024-07-16 16:49 UTC, sjmulder commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
`_FILE_OFFSET_BITS` is indeed checked by features.h, so a bit of a chicken and egg problem here. Bit of a chicken and egg problem.

2024-07-16 18:04 UTC, sjmulder commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
I can't think of a way to do this correctly without a configure script. Unless you do I propose we close this PR and I think of something better (or leave it as is).

2024-07-17 09:25 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
We have a bit of pseudo configure script going on in the Makefile over here

https://github.com/jarun/nnn/blob/86d883eee4986c7125bd77415e1a9b6b94e6bb83/Makefile#L189-L190

If you can do something like this without too much baggage (we don't want to slow down the build step noticeably) then that seems acceptable to me.

2024-07-31 14:02 UTC, N-R-K commented on src/nnn.c
> +#include <features.h>		/* __GLIBC__ etc */
Here's a command that you can use to test glibc version in the makefile if you're still interested in pursuing this:

```sh
printf "#include <stdlib.h>\n#if __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 23)\nYES\n#else\nNO\n#endif\n" | cc -E - | tail -n1
```

2024-08-11 02:44 UTC, jarun commented
Closing this since this is working for a very long time.

2024-08-11 02:44 UTC, closed without merging