Replace use of dprintf() with fprintf() or write()
jarun/nnn pull request #1912
Opened 2024-07-16 18:01 UTC by sjmulder

This improves compatibility with legacy platforms that don't provide the function, in particular, Illumos.

(Alternative to https://github.com/jarun/nnn/pull/1911)

2024-07-17 17:21 UTC, jarun requested changes

2024-07-17 17:21 UTC, jarun commented on src/nnn.c
> +		write(fd, g_buf, strlen(g_buf));
Please check the warning.

2024-07-17 20:14 UTC, sjmulder commented on src/nnn.c
> +		write(fd, g_buf, strlen(g_buf));
The warning indicates that XDG_HOME can end up in `curpath` and hence the file. I suppose this is correct but also entirely intentional, we want to write out the current path.

It's also unchanged from the current situation but it appears that CodeQL didn't catch it with dprintf().

2024-07-19 13:14 UTC, jarun requested changes

2024-07-19 13:14 UTC, jarun commented on src/nnn.c
> +		write(fd, "cd ", 3);
Please check the return value of write. CI fails with the following:

```
########## gcc-9 ##########
gcc-9  -Werror -std=c11 -Wall -Wextra -Wshadow -O3 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -o nnn  src/nnn.c -lreadline -lncursesw -ltinfo -lpthread
src/nnn.c: In function 'write_lastdir':
src/nnn.c:2846:3: error: ignoring return value of 'write', declared with attribute warn_unused_result [-Werror=unused-result]
 2846 |   write(fd, "cd ", 3);
      |   ^~~~~~~~~~~~~~~~~~~
src/nnn.c:2847:3: error: ignoring return value of 'write', declared with attribute warn_unused_result [-Werror=unused-result]
 2847 |   write(fd, g_buf, strlen(g_buf));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:224: nnn] Error 1

Exited with code exit status 2
```

2024-07-19 13:16 UTC, jarun requested changes

2024-08-11 02:24 UTC, jarun commented
Any update here?

2024-08-11 02:35 UTC, jarun commented
Merging. I'll take care of the rest.

2024-08-11 02:35 UTC, merged