Indicate type-to-nav mode with symbol N
jarun/nnn pull request #1937
Opened 2024-09-22 19:27 UTC by amalgame21

Notify the user the current context menu is in type-to-nav mode with symbol N after pressing `ESC` in type-to-nav mode.
After pressing `CTRL+n`, the symbol N disappear, indicate it is no longer in type-to-nav mode.

2024-09-23 22:08 UTC, jarun requested changes

2024-09-23 22:08 UTC, jarun commented on src/nnn.c
> +	if (cfg.filtermode)
Why do we need this? The prompt should show `/` when the mode is enabled.

2024-09-23 22:24 UTC, jarun requested changes

2024-09-23 22:24 UTC, jarun commented on src/nnn.c
> +		sort[i++] = 'N';
In case you really want it (appears to be useful in some cases), please use `F`.

2024-09-24 11:19 UTC, jarun commented on src/nnn.c
> +	if (cfg.filtermode)
Got it.

2024-09-24 11:19 UTC, merged

2024-09-24 11:19 UTC, jarun commented
Thank you!

2024-09-24 13:50 UTC, N-R-K commented on src/nnn.c
> +		sort[i++] = 'F';
Is this the right place to add this though? This string is related to sorting, but type to nav mode isn't really related to sorting order.

2024-09-24 14:38 UTC, jarun commented on src/nnn.c
> +		sort[i++] = 'F';
True but it's the smallest patch. :)

2024-09-24 17:19 UTC, amalgame21 commented on src/nnn.c
> +		sort[i++] = 'F';
Sorry I don't understand the code design very much and I just hacked it with my very very limited knowledge in C. If it is not the proper place to add this code and mess thing up please reverse it. Local patch is easy anyway.

2024-09-25 14:41 UTC, jarun commented on src/nnn.c
> +		sort[i++] = 'F';
I have taken care of it. The code is better paled now.

2024-09-25 18:56 UTC, amalgame21 commented on src/nnn.c
> +		sort[i++] = 'F';
Thanks! Really appreciated!!!