O_EMOJI: Use a bigger variety of emoji
jarun/nnn pull request #1950
Opened 2024-11-06 20:52 UTC by dkabus

This commit changes the following icon definitions to use more specific emoji as icons. All of the new definitions are padded with spaces to ensure they use two cells each.

```
ICON_CHESS "" -> "♟ " (chess notation)
ICON_FSHARP "" -> "🔷" (blue diamond looks like F Sharp logo)
ICON_FONT "" -> "🔤" (letters abc)
ICON_HTML "" -> "🌍" (globe)
ICON_JAVASCRIPT "" -> ICON_SCRIPT (use a less generic emoji)
ICON_MS_EXCEL ICON_WORDDOC -> "📗" (green book for Excel)
ICON_MUSIC "🎧" (headphones and notes for music folder)
ICON_MUSICFILE ICON_MUSIC -> "🎵" (one musical note for a song)
ICON_PLAYLIST "" -> "🎶" (multiple notes for a playlist)
ICON_PHOTOSHOP ICON_PICTUREFILE -> "🖌 " (paintbrush symbolising photo editing)
ICON_PICTUREFILE ICON_PICTURES -> "🖼 " (a framed picture)
ICON_RUST "" -> "🦀" (crab emoji looks like Rust mascot)
ICON_SASS "" -> ICON_EXT_CSS (CSS preprocessor)
ICON_VIDEOFILE ICON_VIDEOS -> "🎞 " (a film strip to symbolise a video)
ICON_VIDEOS "🎞 " -> "🎬" (a clapper board for videos folder)
ICON_VIM "" -> "🪛" (the power tool for everyone)
ICON_EXT_COFFEE "" -> ICON_JAVASCRIPT (JS preprocessor)
ICON_EXT_DEB ICON_LINUX -> "🍥" (Debian swirl)
ICON_EXT_GO "" -> "💨" (Go logo dashing away)
ICON_EXT_MAT "" -> ICON_EXT_M (MATLAB)
ICON_EXT_NIX "" -> "❄ " (Nix language logo like snowflake)
ICON_EXT_PHP "🌐" -> ICON_HTML (use same Emoji for PHP and HTML)
ICON_EXT_ROM "" -> "🔒" (a padlock)
ICON_EXT_TS "" -> ICON_JAVASCRIPT (JS with static typing)
```

2024-11-06 22:13 UTC, N-R-K requested changes
Looks mostly okay. A couple minor stuff:

2024-11-06 22:13 UTC, N-R-K commented on src/icons.h
> +#define ICON_FSHARP        ICON_STR(DEV_FSHARP, "", "🔷")
I think it's better to have a generic source code icon instead of using emojies which are vaguely similar.

2024-11-06 22:13 UTC, N-R-K commented on src/icons.h
> +#define ICON_VIM           ICON_STR(DEV_VIM, "", "🪛")
I don't get the vim and 🪛 association.

2024-11-06 22:13 UTC, N-R-K commented on src/icons.h
> +#define ICON_EXT_GO        ICON_STR(MFIZZ_GO, "󰟓", "💨")
I don't get how 💨 connects to go. Also, the previous comment about generic source code icon applies here.

2024-11-06 22:13 UTC, N-R-K commented on src/icons.h
> +#define ICON_CHESS         ICON_STR("", "󰄺", "♟️ ")
Maybe use chess knight emoji? It will match with nnn's logo.

2024-11-06 23:03 UTC, dkabus commented on src/icons.h
> +#define ICON_VIM           ICON_STR(DEV_VIM, "", "🪛")
Vim is called "The power tool for everyone!" on their official website. https://www.vim.org/

2024-11-06 23:05 UTC, dkabus commented on src/icons.h
> +#define ICON_FSHARP        ICON_STR(DEV_FSHARP, "", "🔷")
I see your point. I've adressed this in commit https://github.com/jarun/nnn/pull/1950/commits/e4ea1fd92615459793e562cd3bdfcbcaf9113aec

2024-11-06 23:05 UTC, dkabus commented on src/icons.h
> +#define ICON_EXT_GO        ICON_STR(MFIZZ_GO, "󰟓", "💨")
Adressed in https://github.com/jarun/nnn/pull/1950/commits/c299fe8bfab59285b4045702d8606b1cbf24df8a

2024-11-06 23:11 UTC, dkabus commented on src/icons.h
> +#define ICON_CHESS         ICON_STR("", "󰄺", "♟️ ")
That would be nice indeed, but won't work. The knight ♞ is in the unicode block "Miscellaneous Symbols", only some of which are emoji. The only chess related glyph that is an emoji is the black pawn. ♟️ https://en.wikipedia.org/wiki/List_of_emojis

2024-11-08 13:54 UTC, jarun commented
@N-R-K please merge when ready.

2024-11-08 15:44 UTC, merged

2024-11-08 15:44 UTC, N-R-K commented
Thanks. Merged.