xreadline by word movement
jarun/nnn pull request #1971
Opened 2024-12-15 06:31 UTC by doremiyeon

is this useful? added by-word navigation and deletion bindings for xreadline()
- **extend xreadline() with some by-word movement**
- **xreadline ctrl-w memmove less**

2024-12-15 10:57 UTC, jarun commented
Can you explain each of the behavioural changes for me to take a call?

2024-12-16 00:23 UTC, N-R-K requested changes
Untested, but some cursory review.

2024-12-16 00:23 UTC, N-R-K commented on src/nnn.c
> +					if (pos <= 0)
`pos` can't be less than 0 since it's unsigned.

2024-12-16 00:23 UTC, N-R-K commented on src/nnn.c
> +				}
I think the previous code was fine. `prompt` should never get large enough for multiple memmoves to become noticeable.

Also, I don't like the `len > lpos` special casing. `len` can't be bigger than `lpos`, only equal. And if `len == lpos` then the memmove with 0 length argument would've gracefully handled that as a no-op anyways.

2024-12-16 00:23 UTC, N-R-K commented on src/nnn.c
> +						printmsg(prompt);
Is this supposed to be here?

2024-12-16 00:30 UTC, N-R-K commented on src/nnn.c
> +						printmsg(prompt);
Okay, nevermind. I see what's going on. I thought it was some debug print message mistakenly left behind.

2024-12-16 01:26 UTC, N-R-K commented
I've pushed some changes:

1. Removed the superfluous checks. Just make the code gracefully work with 0.
2. `isalnum` (and all the other `ctype.h` functions) only accept argument in the rage `[0, 255]`, we can't feed it `wchar_t` arguments. Added custom macro for it instead.
3. We might be dealing with unicode chars, so instead of `isalnum` I changed the checks to `isspace` which would work on unicode chars instead of just ascii.
4. I notice a bug in the current `Ctrl+W` handling, we only delete a single space if there's multiple before the cursor while readline will remove all. I've fixed it, but it also no longer treats `/` as a boundary (neither does readline).

@jarun do you want `xreadline` to follow readline's behavior or do you want to keep the custom `/` as word boundary behavior? If you want the custom behavior, do you want it just for `Ctrl+w` or the rest as well?

2024-12-16 04:36 UTC, doremiyeon commented on src/nnn.c
> +					if (pos <= 0)
sure, it's just a habit. i prefer specifying stricter conditions to safeguard against type changes or the like.

2024-12-16 04:43 UTC, doremiyeon commented on src/nnn.c
> +				}
len is always bigger than lpos unless cursor is at final position. it's true that memmove is called with 0 at len == lpos. semantics don't change, just saves the call.

2024-12-16 04:47 UTC, doremiyeon commented
> Can you explain each of the behavioural changes for me to take a call?

I added Meta-b, Meta-f conforming to https://www.gnu.org/software/bash/manual/bash.html#index-forward_002dword-_0028M_002df_0029 as well as the corresponding deletion commands, M-d and M-bspc.

They move cursor by word boundary, where a word is defined to be composed of letters and digits.

2024-12-16 04:54 UTC, doremiyeon commented
@N-R-K 

> I've pushed some changes:
>     3. We might be dealing with unicode chars, so instead of `isalnum` I changed the checks to `isspace` which would work on unicode chars instead of just ascii.

I hadn't considered unicode, but could isspace be turned into something to include all the other non-word (non alphanum) characters within ascii range as well?

2024-12-16 06:26 UTC, N-R-K commented
> but could isspace be turned into something to include all the other non-word (non alphanum) characters within ascii range as well?

What meaningful difference does it make?

2024-12-16 08:33 UTC, doremiyeon commented
> > but could isspace be turned into something to include all the other non-word (non alphanum) characters within ascii range as well?
> 
> What meaningful difference does it make?

the word boundaries differ, do they not? many filenames have underscores in  them, or dashes. navigating between those is the whole point of these movements. paths contain slashes, same thing.

also: strictly speaking, Ctrl-w explicitly differs from Meta-bspc by what it considers a word boundary. whitespace vs non-alphanumerical (including unicode, not sure if it distinguishes between unicode "special characters" and the rest off the top of my head).

2024-12-16 08:56 UTC, N-R-K commented
> the word boundaries differ, do they not? many filenames have underscores in them, or dashes. navigating between those is the whole point of these movements.

Ok, I see. I've switched to `iswalnum`. Hopefully it doesn't contain any weird pitfalls like the `ctype.h` counterparts do.

> strictly speaking, Ctrl-w explicitly differs from Meta-bspc by what it considers a word boundary.

I've left out `ctrl-w` change for now, I'll look into it later. But first I'm going to wait for @jarun to reply on whether he wants to keep the custom `/` behavior.

> edit: there's also iswalnum() that "should just work."

Yes, I thought about it just now as well.

2024-12-16 12:37 UTC, jarun commented
> do you want xreadline to follow readline's behavior or do you want to keep the custom / as word boundary behavior? If you want the custom behavior, do you want it just for Ctrl+w or the rest as well?

We can keep it the same as readline.

2024-12-16 15:25 UTC, N-R-K commented
> We can keep it the same as readline.

Okay, done.

---

@doremiyeon can you test it out and make sure everything still works as intended?

2025-01-05 16:45 UTC, jarun commented
I am merging this. Can you please list the new keybinds and the intended behaviour so I can try them out?

2025-01-05 16:45 UTC, merged

2025-01-05 17:06 UTC, N-R-K commented
New bindings are `M-f`, `M-b`, `M-d` and `M-Backspace/Del`.
Intended behavior can be found here: https://www.gnu.org/software/bash/manual/bash.html#index-forward_002dword-_0028M_002df_0029.

(Remember to compile with `O_NORL=1` if you're going to test it out).

`C-w` was also changed to match readline's behavior. Details in the commit message: https://github.com/jarun/nnn/pull/1971/commits/942afdf4454743be6065e022fc31271c75c0f01c

2025-01-05 17:17 UTC, jarun commented
Basic operations work fine for me.