Add support for Alexey Tourbin's QSORT code
jarun/nnn pull request #708
Opened 2020-08-19 15:41 UTC by leovilok

See https://github.com/svpv/qsort

No benchmark yet.

2020-08-19 16:40 UTC, jarun requested changes

2020-08-19 16:40 UTC, jarun commented on Makefile
> +	CPPFLAGS += -DNO_TOURBIN_QSORT
Can we have something smaller? Also this should go in:

- initialize at line 22
- Haiku Makefile

2020-08-19 16:40 UTC, jarun commented
Travis complains _mostly_ about macro parenthesis. Please fix those.

2020-08-19 16:42 UTC, jarun commented on Makefile
> +	CPPFLAGS += -DNO_TOURBIN_QSORT
Also, this increases the binary size as @KlzXS suggested. Let's have it as compile-in.

2020-08-19 17:02 UTC, jarun commented
Benchmark details from @leovilok for the record. It's faster than stdlib at the cost of increasing the binary size by 4KB.

It turns out that `populate()` was already instrumented in DEBUG mode, including both `dentfill()` and `qsort()` calls. So as an early result, we can already tell that Tourbin's qsort **is** faster:
(here I'm manually starting nnn in a test dir filled whith 100000 empty files with random names)
~~~
#### TOURBIN QSORT ####
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=3656519433
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=354925821
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=3652997582
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=3657911883
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=347739563
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=347168855
#### STDLIB QSORT ####
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=400908271
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=3676649821
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=378532354
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=382453839
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=397564860
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=379860967
[leo@franky tmp]$ grep nsec nnndbg 
ln 5141: ts2.tv_nsec - ts1.tv_nsec=3697438251
~~~

2020-08-19 17:47 UTC, leovilok commented
I've been trying to get more in-depth benchmarks, so I ran everything in valgrind (callgrind mode).
Here is basically what I got:

## Tourbin's qsort version

Total callgrind "cost": 685 487 119
Calls to `entrycmp`: 1 859 344
Screenshot (excuse the french UI):
![tourbin-qsort](https://user-images.githubusercontent.com/1430862/90669097-5f75b780-e251-11ea-98a6-eff78ea3b25f.png)

## stdlib's qsort

Total callgrind "cost": 582 280 595
Calls to `entrycmp`: 1 536 571
Screenshot:
![std-qsort](https://user-images.githubusercontent.com/1430862/90669105-63a1d500-e251-11ea-9793-ed41e5bf5934.png)

## Discussion

So in this directory with 100000 empty files generated by `misc/test/genfiles.sh`, when quitting immediately, sorting the input file entries is really the big performance bottleneck in a `nnn` execution (more than 90% of the "cost" in both cases).
Of course valgrind is a slow VM, and doesn't allways reflect the real performmances, especially when sys calls are in the mix, but we can still count loops and function calls, and compare both qsort implementations.

Tourbin's QSORT, being implemented in macros, is not visible in the call graph. But we can count calls to `entrycmp`, much higher than in stdlib's qsort implementation, as expected considering that's what happens in Tourbin's benchmarks too.

Now this makes the overall callgrind "cost" of the Tourbin version higher, but the bare metal benchmarks are more important than what happens in Valgrind VM.

2020-08-19 17:50 UTC, leovilok commented
I forgot the callgrind traces, if you want to explore them by yourself with kcachegrind.
[callgrind-traces.zip](https://github.com/jarun/nnn/files/5098321/callgrind-traces.zip)

2020-08-19 17:50 UTC, jarun commented
Thanks a lot for the in-depth details!

2020-08-19 19:31 UTC, jarun commented on Makefile
> +	CPPFLAGS += -DNO_TOURBIN_QSORT
Maybe just use `O_QSORT` in Makefile and `TOURBIN_QSORT` in code.

2020-08-19 22:30 UTC, leovilok commented
So here is a more "real world" benchmark, with the unix sh builtin `time` (and with `nextsel()` always returning `SEL_QUIT`, so it's the "time to first user input"):
![qsort-bench](https://user-images.githubusercontent.com/1430862/90695485-d07d9500-e27a-11ea-82dd-53cec9562fbf.png)

 So there is no clear winner for `/`, or even `/usr/lib/` (which I think is one of the most crowded real directory on my system), but the new `QSORT` wins on (unrealistically?) entry heavy directory.

But the difference is barely noticeable on my system, it might be worth benchmarking on lower end hardware, where it could make a real difference. I might publish the benchmark code for that.

So do you think this QSORT is worth including?

2020-08-19 22:38 UTC, jarun commented
> it might be worth benchmarking on lower end hardware

I concur. Please run the benchmarks on a Pi or mid-range Android.

> So do you think this QSORT is worth including?

Of course! Please update the PR.

2020-08-19 22:46 UTC, jarun commented
> I might publish the benchmark code for that.

Please do so and I can run on the Pi 4 4GB version I have.

2020-08-19 23:01 UTC, 0xACE commented
@leovilok that's a sexy diagram, how did you make it?

2020-08-20 03:43 UTC, leovilok commented
I just pushed some benchmark scripts & compilation mode, I'll really update the PR tomorrow.

@0xACE I wanted to learn some matplotlib, but in the end I only used it to plot the violin graph and the vertical axis, and I did colors, spacing, and adding labels in Inkscape :stuck_out_tongue:

2020-08-20 03:55 UTC, jarun commented
No problem! Please take your time.

2020-08-20 18:39 UTC, jarun commented on Makefile
> +ifeq ($(O_BENCHMARK),1)
`O_BENCH`?

2020-08-21 01:48 UTC, leovilok commented on Makefile
> +ifeq ($(O_BENCHMARK),1)
OK

2020-08-21 01:49 UTC, leovilok commented on Makefile
> +	CPPFLAGS += -DNO_TOURBIN_QSORT
All done.

2020-08-21 01:53 UTC, leovilok commented
I don't own a Pi or a similar small computer, and I don't have a very old box running currently, so I can't really benchmark on ressource constrained devices. But if someone wants to try my benchmark scripts, I'm available for any help.

2020-08-21 02:41 UTC, jarun commented
I have one. I'll run it sometime.

2020-08-21 02:45 UTC, merged

2020-08-21 02:45 UTC, jarun commented
Thank you!