Add cmdline and runtime options to not move to next entry after select key
jarun/nnn pull request #713
Opened 2020-08-27 17:17 UTC by FriendlyNeighborhoodShane

I just found it more intuitive to work with, understandable if you don't want to support this workflow in upstream. Also the keybinds maybe could be better, I feel.

2020-08-27 17:35 UTC, FriendlyNeighborhoodShane commented
Typos fixed.

2020-08-27 19:22 UTC, jarun commented
We can't have a new keybind for this. If becomes unmanageable if everyone is looking for a keybind for minor behavioral aspects they don't like.

We can consider having the program option and you have to stick to a choice for the session.

What problem do you see with auto move on selection? Asking this because it was specifically added on a user request and I personally consider it a better user experience.

2020-08-28 02:23 UTC, FriendlyNeighborhoodShane commented
Well, sometimes you're just moving up while selecting, or sometimes you're just carefully thinking about what to select and it's a little jarring to the brain that you don't need a `down` key after `space`.

Just silly little opinionated things, like all UI/UX stuff is.

2020-08-28 02:24 UTC, FriendlyNeighborhoodShane commented
Well, sometimes you're just moving up while selecting, or sometimes you're just carefully thinking about what to select and it's a little jarring to the brain that you don't need a `down` key after `space`.

Just silly little opinionated things, like all UI/UX stuff is.

2020-08-28 20:59 UTC, jarun requested changes

2020-08-28 20:59 UTC, jarun commented on src/nnn.h
> +	/* Don't move to next entry on select */
Please remove the keybind.

2020-08-28 20:59 UTC, jarun commented on src/nnn.h
> +	SEL_STAYSEL,
Please remove the keybind.

2020-08-28 20:59 UTC, jarun commented on src/nnn.c
> +		  "cy  Toggle stay on sel\n"
Please remove the keybind from help.

2020-08-28 20:59 UTC, jarun commented on src/nnn.c
> +	uint stayonsel	: 1;  /* Don't move to next entry on select */
Please add to the `runstate` structure.

2020-08-28 20:59 UTC, jarun commented on src/nnn.c
> +	0, /* stayonsel */
Please remove from here.

Note: everything in `g_state` is initialized to 0 (auto).

2020-08-28 20:59 UTC, jarun commented on nnn.1
> +	don't move to next entry after pressing select
disable auto-proceed on selection

2020-08-28 20:59 UTC, jarun commented on src/nnn.c
> +		" -j      don't move to next entry after pressing select"
disable auto-proceed on selection

2020-08-28 21:00 UTC, jarun commented
I understand. Please take care of the review comments and update the PR.

2020-08-29 03:30 UTC, FriendlyNeighborhoodShane commented
@jarun Amended the first commit and dropped the second 👍

2020-08-29 23:02 UTC, jarun requested changes

2020-08-29 23:02 UTC, jarun commented on nnn.1
> +.Op Ar -j
Please make this capital `J`. So far I am using the capital to disable things.

2020-08-29 23:02 UTC, jarun commented on src/nnn.c
> +		" -j      disable auto-proceed on select"
no auto-proceed on select

saves a few bytes.

2020-08-29 23:55 UTC, merged

2020-08-29 23:55 UTC, jarun commented
Thank you! I'll make the rest of the changes.

2020-08-30 04:23 UTC, FriendlyNeighborhoodShane commented
Thanks! Really love all the work put into this project!

2020-08-30 04:49 UTC, jarun commented
Me too! ;)

2020-09-01 16:31 UTC, jarun commented on src/nnn.c
>  	uint reserved   : 14;
@FriendlyNeighborhoodShane we should have made the reserved field 13 bits in width. We both missed this.

2020-09-01 18:34 UTC, FriendlyNeighborhoodShane commented
Whoops. haha. Thanks for informing me about this, didn't even realise that was futureproof padding at the end of the struct.

I'm no C veteran, but I think both experienced and new hackers would benefit from a comment explicitly stating its purpose there.

2020-09-01 18:42 UTC, FriendlyNeighborhoodShane commented on src/nnn.c
>  	uint reserved   : 14;
Whoops. haha. Thanks for informing me about this, didn't even realise that was futureproof padding at the end of the struct.

I'm no C veteran, but I think both experienced and new hackers would benefit from a comment explicitly stating its purpose there.

2020-09-01 19:09 UTC, jarun commented on src/nnn.c
>  	uint reserved   : 14;
Yes. we should have a comment.