Small plugin for jump
jarun/nnn pull request #714
Opened 2020-08-28 22:03 UTC by snide

Hello! Thank you for this fantastic little program. I like using jump, which is very similar to auto-jump. Figured I'd add a small plugin for it.

Here is a small mp4 showing it working (exactly the same as autojump). I'm primarily a designer, so yell if I missed something!

https://snid.es/2020AUG/GlygMMHKZTW9hBrU.mp4

2020-08-28 22:22 UTC, KlzXS approved these changes
@jarun we should add the `NNN_PIPE` check in `autojump` plugin as well.

2020-08-28 22:29 UTC, snide commented
@KlzXS Added it for you.

2020-08-28 22:31 UTC, jarun requested changes

2020-08-28 22:31 UTC, jarun commented on plugins/autojump
> +  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
I think the indent is 2 chars, we use 4. Can you please update it in both the plugin changes?

2020-08-28 22:31 UTC, snide commented on plugins/autojump
> +  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
Absolutely! My bad.

2020-08-28 22:32 UTC, jarun commented on plugins/autojump
> +  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
No problem! You got most of the things right! Even I miss sometimes. ;)

2020-08-28 22:32 UTC, snide commented on plugins/autojump
> +  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
Done.

2020-08-28 22:33 UTC, merged

2020-08-28 22:33 UTC, jarun commented
Thank you for your contribution!

2020-08-28 22:34 UTC, jarun commented
I missed something... why not just merge these 2 plugins into one?

Keep jump as default and autojump as fallback.

2020-08-28 22:36 UTC, jarun commented
We do combine near-similar-functionality utilities in a single plugin.

2020-08-28 22:42 UTC, jarun commented
@snide you can follow the `fzopen` plugin to combine these 2 into a single one.

2020-08-29 00:07 UTC, jarun commented
Took care of it.

2020-08-29 00:07 UTC, snide commented
@jarun Ah. Thanks. That makes sense. Good to know for next time!