Modified dups to allow selecting files for removal
jarun/nnn pull request #765
Opened 2020-10-21 15:48 UTC by KlzXS

The script displays all the duplicate files in a directory grouped by md5 hash and size displayed above each grouping. Each grouping is followed by a newline. To keep a file remove it from the temp file, the script will attempt to remove every line not beginning with "md5sum".

If anyone has suggestions to improve performance they are more than welcome.

2020-10-21 15:56 UTC, KlzXS commented
Don't merge until I benchmark another approach I want to try.

2020-10-22 04:37 UTC, jarun commented
Some thoughts:

1. We need to ask at some point in the workflow whether the user wants to delete the lines left in the tmp file or not? This should be a cumulative question based on which the whole deletion process can be aborted.

2. It would also be a good idea to add a commented (hashed note) in the top of the tmp file that the lines left will be deleted.

3. I think we can take an approach of omitting hashed lines in the tmp file. So the user has another choice to hash out the files he wants to keep. To make things simple, we can show the hash + size line commented as well.

2020-10-22 04:56 UTC, KlzXS commented
> cumulative question

What do you mean by cumulative?

Also please don't use hash as in # and has as in hashsum in the same context. It took me a second. :)

2020-10-22 05:27 UTC, jarun commented
I meant a overall/general prompt that allows the user to abort the whole process or removing files one by one. Or you can provide an option in the per 

> file prompt to abort the remaining process.

Hehe, I meant skip the lines beginning with a `#`

2020-10-24 13:17 UTC, jarun commented
@KlzXS any update on this?

2020-10-24 19:40 UTC, KlzXS commented
I've been struggling to find much time to work on this lately but I'll try my best.

2020-10-24 21:34 UTC, jarun commented
Sure thing!

2020-11-04 18:51 UTC, jarun commented
@KlzXS any update here? I will plan for the next release once this is in.

2020-11-06 02:30 UTC, jarun commented
shellcheck fails:

```
sed -e $sedcmd "$tmpfile" | tr '\n' '\0' | xargs -0 sh -c "$rmcmd"
       ^-- SC2086: Double quote to prevent globbing and word splitting.
```

Also, please remove the _work in progress_ label once you are done.

2020-11-07 13:11 UTC, jarun commented
I see the following issue:

Created a file abc with character i in it. Created a duplicate name def.

Ran the plugin and commented both abc and def as follows:

```
# ./abc
#./def
```

Then I did the following:

```
Remove commented files? (yes/no/abort) [default=a]: y
Remove with force or interactive? (f/i) [default=i]: i
#md5sum: 372e25f23b5a8ae33c7ba203412ace30 size: 2 bytes: 1: rm -i "$0" "$@" < /dev/tty: not found
```

Finally, none of the 2 files are removed. Please take a look.

2020-11-07 13:12 UTC, jarun commented
Note that there is a space before `./abc` but not before `./def`. That's intentional.

2020-11-07 21:41 UTC, KlzXS commented
That should no longer be a problem, I tried some test similar to yours.

2020-11-08 03:04 UTC, jarun commented
I just want to ensure we are doing this right as it has potential to remove unwanted user data.

@leovilok @0xACE @snide can you guys spend some time on some random tests on this plugin?

2020-11-08 03:09 UTC, jarun requested changes

2020-11-08 03:09 UTC, jarun commented on plugins/dups
> +## You can choose between removing all the commented out files, all the uncommented ones or none at all.
We need better documentation. Please explain more. Are the commented files removed or uncommented ones?

> commented out files

Single comment of double comment?

The next line indicates commented lines are ignored. From what I see, files in commented lines are deleted.

2020-11-08 09:16 UTC, jarun commented on plugins/dups
> +# If the size of a file has more that $size_digits digits the file will be misplaced
Also does it indicate files lesser than or greater than 931 GiB will be correctly detected?

2020-11-08 10:22 UTC, KlzXS commented on plugins/dups
> +# If the size of a file has more that $size_digits digits the file will be misplaced
We want to filter all the files with duplicate filesizes, `uniq` doesn't have an option to filter by a specific space separated field, it only has an option to compare by the first `n` characters. So I need `find` to print the filesize with a constant number of characters. I chose 12, no real reason, we could go with less as you probably aren't going to be using this plugin on such huge files.

> Why can't we ignore such file (instead of misplacing)?

We could, but do you really expect someone to use this on a TB file? I haven't seen such a large file. Ever.

2020-11-08 10:31 UTC, KlzXS commented on plugins/dups
> +## You can choose between removing all the commented out files, all the uncommented ones or none at all.
I've simplified this a bit.

All the double comment lines (`##`) are always ignored, now the hash and size are also double commented.
Of the remaining non-empty lines the user has a choice to remove all the commented ones (`#`) or all the uncommented ones. (`Remove commented files? (yes/no/abort) [default=a]:`)

2020-11-08 10:53 UTC, jarun commented on plugins/dups
> +# If the size of a file has more that $size_digits digits the file will be misplaced
Ahh OK. I thought it had to do with file size limit (rather than file size print length limit). ;)

2020-11-08 11:01 UTC, jarun commented on plugins/dups
> +## You can choose between removing all the commented out files, all the uncommented ones or none at all.
So `no` to the question means remove uncommented files?

If that's the case, I would say we stick to remove commented files and remove the `no` option. In any batch delete case, a man should be forced to be extra careful.

By default all the results are uncommented so I would say we don't delete uncommented as a fixed strategy. If the user wants to delete something he has to explicitly comment it.

2020-11-08 11:05 UTC, jarun commented on plugins/dups
> +## You can choose between removing all the commented out files, all the uncommented ones or none at all.
Trust me, being a little less smart here is far better than a user coming back complaining he lost his files even before he understood clearly how the plugin works.

And _Comment the files you want to delete_ is a simple and clear instruction.

2020-11-08 12:04 UTC, jarun commented on plugins/dups
> +printf "Remove commented files? (yes/no) [default=n]: "
Would it be a good idea to provide an option `export` to export and exit? In case the user wants to inspect and act manually?

2020-11-08 12:18 UTC, KlzXS commented on plugins/dups
> +printf "Remove commented files? (yes/no) [default=n]: "
I mean when in the editor the user can save the file wherever they like. And then they can just abort. I don't really see much of a reason to add an export.

2020-11-08 12:20 UTC, jarun commented on plugins/dups
> +printf "Remove commented files? (yes/no) [default=n]: "
I agree. Missed that. We are good!

2020-11-08 12:21 UTC, merged

2020-11-08 12:21 UTC, jarun commented
Thank you so much @KlzXS! This is a significant value addition.

2020-11-08 16:04 UTC, jarun commented
I see an issue if I do not comment any file for removal. Editor is vim. Without changing the tmp file I did `:q`.

Then:

```
Remove commented files? (yes/no) [default=n]: y
Remove with force or interactive? (f/i) [default=i]: i
rm: cannot remove 'sh': No such file or directory
```

I think when there is no file to remove rm is still invoked.

2020-11-08 17:43 UTC, KlzXS commented
Since we are already using GNU sed, let's use the `-r` aka `--no-run-if-empty` flag from GNU xargs.

2020-11-08 18:07 UTC, jarun commented
Sure thing!

2020-11-09 19:08 UTC, jarun commented
Took care of it at commit 1418ecde0dc28dc7d32a9ffdcf0721db7bd2d624.