Plugin readme improvement
jarun/nnn pull request #768
Opened 2020-10-29 23:41 UTC by voodoologic

I've been recently attempting to leverage nnn.  I think this addition to the plugin readme would help people who are starting out.

2020-10-30 05:47 UTC, jarun requested changes

2020-10-30 05:47 UTC, jarun commented on plugins/README.md
> +Two things stand out in the above example:
Please make this:

Note:

2020-10-30 05:47 UTC, jarun commented on plugins/README.md
> +- It will honor a path to a sub-folder.
Instead of "It", please mention the variable which does this.

2020-10-30 05:47 UTC, jarun commented on plugins/README.md
> +- Only the first defined keybindng will work, any subsequent keybinding defined on the same key won't work.
We can omit this as it's elementary.

2020-10-30 05:47 UTC, jarun commented on plugins/README.md
> +- Only the first defined keybindng will work, any subsequent keybinding defined on the same key won't work.
Without this there will be only one note so probably you can add a single line note.

2020-10-31 05:02 UTC, voodoologic commented
Modified for your consideration.

2020-10-31 06:02 UTC, merged

2020-10-31 06:02 UTC, jarun commented
Thank you!