deactivate INOTIFY for CYGWIN
jarun/nnn pull request #796
Opened 2020-11-20 18:03 UTC by magomi

inotify is a Linux kernel feature. It is not available within CYGWIN.

2020-11-20 18:15 UTC, jarun requested changes

2020-11-20 18:15 UTC, jarun commented on src/nnn.c
> +#if !defined(__CYGWIN__)
How about the MINGW, MINGW32 and MINGW64 families?

2020-11-21 15:01 UTC, jarun commented on src/nnn.c
> +#if !defined(__CYGWIN__)
I'll add these. Just try to keep an eye out when you raise a PR. `nnn` is a very responsive project.

2020-11-21 15:01 UTC, merged

2020-11-21 16:52 UTC, magomi commented on src/nnn.c
> +#if !defined(__CYGWIN__)
> 
> 
> How about the MINGW, MINGW32 and MINGW64 families?

I think this should also be checked. I'm sure these platforms too have no inotify support. 

But I have no environments other than linux and cygwin to test this. Therefore I decided to take the save way for this change.

2020-11-21 16:54 UTC, magomi commented on src/nnn.c
> +#if !defined(__CYGWIN__)
> 
> 
> I'll add these. Just try to keep an eye out when you raise a PR. `nnn` is a very responsive project.

Sorry for that. Didn't expected this PR to be merged this fast. 

Thanks for the work on nnn. It's an awesome tool.

2020-11-21 17:15 UTC, jarun commented on src/nnn.c
> +#if !defined(__CYGWIN__)
No problem! Thank you for your contribution.

I did sanitize this at commit 6f7a4f723b44d8a6abe4ee9e037da2cc5ca910b6.