Updated the Preview-Tabbed ,
jarun/nnn pull request #834
Opened 2021-01-09 15:25 UTC by wimstockman

Changed the mime detector to xdg-mime this offers support for symlinks which file doesn't
and added support for postscript files with zathura

2021-01-09 17:47 UTC, leovilok reviewed
The postscript part looks good.

2021-01-09 17:47 UTC, leovilok commented on plugins/preview-tabbed
> -if which xterm >/dev/null 2>&1 ; then
In the in-file docs (top of the file), we say that we default to `xterm`, not `st`. We could change the priority, but do you have a reason for that?

2021-01-09 17:47 UTC, leovilok commented on plugins/preview-tabbed
> +                $TERMINAL "$XID" -e $TREEVIEW "$FILE" &
Well I touht that nnn itself is a good folder preview app. It's fast and its probably already what the user is used to.

Also it emulates a kind of 2 panel view.

I can understand why you'd want to have a tree view there, but I'm not sure I agree…

2021-01-09 17:47 UTC, leovilok commented on plugins/preview-tabbed
> +       if which xdg-mime >/dev/null 2>&1 ; then
xdg-mime looks interesting, is it as wide spread as `file` though?

2021-01-09 17:49 UTC, leovilok commented on plugins/preview-tabbed
> +       if which xdg-mime >/dev/null 2>&1 ; then
Oh you fallback on file?
It's fine in that case...

2021-01-09 20:30 UTC, wimstockman commented on plugins/preview-tabbed
> +                $TERMINAL "$XID" -e $TREEVIEW "$FILE" &
O the Treeview, is a personal setting.
Wasn't went for the commit.
But FYI , the Treeview is piped with bat to less gives it a nice touch and easy to search :-)

2021-01-09 20:32 UTC, wimstockman commented on plugins/preview-tabbed
> +       if which xdg-mime >/dev/null 2>&1 ; then
Xdg-mime is a tool from xdg-utils.
So if you have xdg-open you probably have xdg-mime.

2021-01-09 20:39 UTC, wimstockman commented on plugins/preview-tabbed
> -if which xterm >/dev/null 2>&1 ; then
Yes, I do have a reason. I think users of ST also set their colors scheme fonts etc hard coded in st. xterm then uses completely other colors. For me personal I use black background in st. Never use xterm and when using the preview-tabbed I first didn't no why the background was white. 
So it makes more sense to make the default the one used mostly by the user.

2021-01-12 13:59 UTC, jarun commented
CI fails. Please check.

2021-01-17 22:21 UTC, jarun requested changes

2021-01-17 22:21 UTC, jarun commented on plugins/preview-tabbed
> +                $TERMINAL "$XID" -e $TREEVIEW "$FILE" &
Please leave treeview out of the mix.

2021-01-17 22:22 UTC, jarun commented
@wimstockman 

This is a 8-day old PR. If I do not get a response in the next 2 days, Ill be closing it. Thanks!

2021-01-19 21:14 UTC, jarun requested changes

2021-01-19 21:14 UTC, jarun commented on plugins/preview-tabbed
> +	        $TERMINAL "$XID" -e nnn "$FILE" &
Please fix the alignment. This is elementary.

2021-01-19 21:16 UTC, jarun requested changes

2021-01-19 21:16 UTC, jarun commented on plugins/preview-tabbed
> +
Please do not add unnecessary newlines.

2021-01-20 02:40 UTC, jarun commented
The new PR seems to be #842... has the same problems.

2021-01-20 02:40 UTC, closed without merging