Wimstockman patch 1
jarun/nnn pull request #842
Opened 2021-01-19 20:14 UTC by wimstockman

Left The Treeview out

2021-01-19 21:19 UTC, jarun requested changes

2021-01-19 21:19 UTC, jarun commented on plugins/preview-tabbed
> +          MIME="$(xdg-mime query filetype "$FILE")"
Alignment.

2021-01-19 21:19 UTC, jarun commented on plugins/preview-tabbed
> +	        $TERMINAL "$XID" -e nnn "$FILE" &
Alignment.

2021-01-19 21:19 UTC, jarun commented on plugins/preview-tabbed
> +
Please remove this newline and the blank line above.

2021-01-20 02:43 UTC, jarun commented
It would have been good enough to update the old PR. I am closing this.

Also, please do not raise PRs on `nnn` if you do not understand the importance of alignment and cannot do it without redundant newlines. At this stage of the project, it's too difficult for us to waste time on these trivial things which should not have been there in the first place.

It's not too difficult to have your own personal preferences in some plugins as `nnn` asks to merge when you install a new version.

2021-01-20 02:43 UTC, closed without merging

2021-01-20 05:44 UTC, wimstockman commented
Hi, Jarun,
Thanks for your comment.
I updated the previous PR.
I'm sorry for the trouble. Will pay more attention in the future.
Keep up the good work.
Kind regards
Wim