Improve consistency/spelling in some comments
jarun/nnn pull request #924
Opened 2021-03-27 18:17 UTC by salutis

2021-03-27 18:24 UTC, jarun requested changes

2021-03-27 18:24 UTC, jarun commented on src/nnn.c
> +	/* set up first context */
Set-up

2021-03-27 18:28 UTC, salutis commented on src/nnn.c
> +	/* set up first context */
Fixed.

2021-03-27 18:42 UTC, jarun commented on src/nnn.c
> +#define NAMEBUF_INCR 0x800 /* 64 dir entries at once, avg. 32 chars per file name = 64*32B = 2KB */
Both filename and file name are fine. Can you change back these to `filename`?

2021-03-28 01:55 UTC, merged

2021-03-28 01:55 UTC, jarun commented
Thank you!