Add new plugin
jarun/nnn pull request #928
Opened 2021-03-28 21:07 UTC by exoton

2021-03-28 21:34 UTC, KlzXS requested changes
Address the comments. I see you've submited a commit while I was looking the changes over, I'll take a look at that now.

2021-03-28 21:34 UTC, KlzXS commented on plugins/cdpath
> +                printf "%-24s :" "${name:0:24}"
CI fails
```
In plugins/cdpath line 26:
printf "%-24s :" "${name:0:24}"
^----------^ SC2039: In POSIX sh, string indexing is undefined.
```

2021-03-28 21:34 UTC, KlzXS commented on plugins/cdpath
> +#          ${XDG_CONFIG_HOME:-$HOME/.config}/bookmarks will be used.
Make it `${XDG_CONFIG_HOME:-$HOME/.config}/nnn/bookmarks` to keep it compativle with the other plugin and also to keep all things `nnn` in one place.

2021-03-28 21:57 UTC, luukvbaal commented
Uhm isn't this exactly the same as the [bookmarks](https://github.com/jarun/nnn/blob/master/plugins/bookmarks) plugin?

2021-03-28 22:00 UTC, luukvbaal commented
Forgive me, you already mention it in the description. What does it add exactly?

2021-03-28 22:12 UTC, KlzXS commented
@luukvbaal as far as I cam see it widens the search looking through everything in `CDPATH` not just in `nnn/bookmarks`. Seems useful enough for people who use that env.

2021-03-28 22:18 UTC, luukvbaal commented
I see, might make more sense to add that to the existing `bookmarks` plugin?

2021-03-28 22:31 UTC, exoton commented
It also includes regular directories, not just the symbolic links. I don't want to add anything to the existing plugin. My version is very short and clean and it has differences that are important to me: display format, field separator, etc.

2021-03-28 23:24 UTC, exoton commented
It also allows for spaces in the basename / bookmark name.

2021-03-28 23:26 UTC, KlzXS commented on plugins/cdpath
> +                [ -h "$entry" ] && entry="$(readlink -f "$entry")"
I missed this originally. `readlink` is not POSIX. Either mention that or remove it. I think it might be better to remove it, I personally like it more when a symlink doesn't get resolved.

2021-03-28 23:28 UTC, KlzXS commented
One more comment from me. If nobody objects after that I think we can merge.

2021-03-28 23:29 UTC, exoton commented on plugins/cdpath
> +                [ -h "$entry" ] && entry="$(readlink -f "$entry")"
It's used in the `bookmarks` plugin too.

2021-03-28 23:37 UTC, KlzXS commented on plugins/cdpath
> +                [ -h "$entry" ] && entry="$(readlink -f "$entry")"
Well leave it then if you will. When I get the time to work on these things I'll go through all the plugins and document that stuff. Not that it would matter to basically anyone, but still.

2021-03-28 23:38 UTC, KlzXS approved these changes

2021-03-29 01:20 UTC, exoton commented
I've removed the `readlink()` call.

2021-03-29 01:36 UTC, exoton commented on plugins/cdpath
> +                [ -h "$entry" ] && entry="$(readlink -f "$entry")"
I don't know how important it is to stay strictly POSIX compliant nowadays. Anyways, I've found a way around it. I personally like the resolved symbolic link - it's an extra piece of information that can be useful.

Thanks for the quick review and approval on a Sunday night.

2021-03-29 02:39 UTC, merged

2021-03-29 02:40 UTC, jarun commented
Thank you! I would also have wanted this functionality in the bookmarks plugin but I see why it's different.

2021-03-29 03:09 UTC, exoton commented
If you set your `CDPATH` to `$HOME/.cache/nnn/bookmarks` you can use it as a bookmarks replacement.

2021-03-29 03:15 UTC, jarun commented
Can you please mention that in the plugin explicitly?

2021-03-29 03:17 UTC, exoton commented
Do you want this comment as an additional commit or as a new PR?

2021-03-29 08:00 UTC, jarun commented
In this PR.

2021-03-29 22:22 UTC, exoton commented
It's already merged and closed. I'll create a new one.