Improve mdoc markup
jarun/nnn pull request #929
Opened 2021-03-29 02:25 UTC by sjmulder

- Replace in-line styling with semantic macros (Ev, Pa, etc)
 - Mark up tables and lists with Bl
 - Add cross references and links (Xr, Sx)
 - ..lots more
 - Make mandoc -Tlint (mostly) happy.

2021-03-29 02:50 UTC, jarun requested changes

2021-03-29 02:50 UTC, jarun commented on nnn.1
> +.Nd The unorthodox terminal file manager
Oh, we need that end `.`. I says - _enough said_. ;)

2021-03-29 02:54 UTC, jarun requested changes

2021-03-29 02:54 UTC, jarun commented on nnn.1
> +.An Sijmen J. Mulder Aq Mt ik@sjmulder.nl
After the existing 3 entries, I prefer to add new contributors names in the project main page. Can you please add your entry there instead of here? Please add it in the current PR.

2021-03-29 07:51 UTC, sjmulder commented on nnn.1
> +.An Sijmen J. Mulder Aq Mt ik@sjmulder.nl
Ah, I thought that was just about the manual. Never mind then, I'll remove it.

2021-03-29 08:26 UTC, sjmulder commented on nnn.1
> +.Nd The unorthodox terminal file manager
Actually `mandoc -Tlint` flagged that:

    mandoc: nnn.1:6:41: STYLE: trailing delimiter: Nd The unorthodox terminal file manager.

In fact looking at other manuals it's not just without trailing full stop but also without initial upper case:

    $ apropos print
    arch (1)             - print machine hardware name (same as uname -m)
    asprintf (3)         - print to allocated string
    base32 (1)           - base32 encode/decode data and print to standard output
    base64 (1)           - base64 encode/decode data and print to standard output
    blkid (8)            - locate/print block device attributes
    bsd-from (1)         - print names of those who have sent mail
    cat (1)              - concatenate files and print on the standard output
    date (1)             - print or set the system date and time
    ...

So I've made it align with that.

2021-03-29 15:03 UTC, jarun requested changes

2021-03-29 15:03 UTC, jarun commented on nnn.1
> +.Nd the unorthodox terminal file manager
Please keep the capital `T` in the and the full stop and the end. We do not want to change the tagline.

2021-03-29 15:03 UTC, jarun commented on nnn.1
> +.Nd the unorthodox terminal file manager
Basically do not change anything in this line.

2021-03-29 15:26 UTC, jarun commented
We have increased around 200 lines and I see that now to add a single word I have to look up what is the syntax. We are not doing this,

2021-03-29 15:26 UTC, closed without merging

2021-03-30 03:43 UTC, jarun commented
@sjmulder I have picked up some changes in commit 34f20ea67895c8954d10011f0bcb195e8b5586cb. I am not comfortable with the other changes. Don't really have the time to understand a new man page format and maintain it.